### ISSUE TITLE
Install.bat error

### ISSUE THREAD

**Issue by YI-YEE** [RCVolus/league-prod-toolkit#102]
![image](https://user-images.githubusercontent.com/91971709/164506264-aef2aea2-3ab6-41fb-ad39-41b16c84236b.png)

Install.bat isn't working.

**Comment by Himyu** [comment]
we are aware of it and are working on it

**Comment by Himyu** [comment]
please follow the new [Install Guide](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation) to get it properly running

**Comment by YI-YEE** [comment]
ty :)))
