### ISSUE TITLE
Add a best of two mode

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#103]
So far there is a best of 1, 3 or 5 mode for the league prod toolkit.
But there might be leagues where you only play 2 games and can achieve a draw.
So a best of two mode would be nice, or maybe even a generic selection.

**Comment by sdomi4** [comment]
I might be overlooking something, but setting the match to bo3 should cover everything:
- Shows scores for 0-0 and 1-0
- Highlights winner on 2-0
- Doesn't highlight winner on 1-1

I'll have to check, but the matchup history should be fine with leaving a bo3 at a 1-1 scoreline. The only situation this might be tricky in is the tournament tree, but I don't think bo2 format works for knockout brackets :)

**Comment by MaximilianRu** [comment]
You are mostly correct, a Bo X system isn't there to show a draw anyway.
The only thing what came into mind is, that in a Bo3 the overlay would make you think there would follow a third game

**Comment by Himyu** [comment]
As mentioned in issue #43 there will be a possibility to just set the number of games instead of the drop-down menu.
Therefore, I gonna close this issue and would ask you to have an eye out for #43. To see when we implemented that.
