### ISSUE TITLE
Issues with ingame and postgame

### ISSUE THREAD

**Issue by sdomi4** [RCVolus/league-prod-toolkit#109]
Hello there!
i tried to test it after your last comment, with the new version, but for me was not working properly.
<img width="896" alt="Screenshot_6" src="https://user-images.githubusercontent.com/105013306/166996527-c0891840-b3dd-4001-9c3f-f009f4128e13.png">
![unknown](https://user-images.githubusercontent.com/105013306/166993089-7ae6e2ce-2346-4368-8323-c87f7c6fa1b6.png)
at some point it started to show me data from ingame, but not showing any level up or item bought on the browser source,just on test button.
<img width="251" alt="Screenshot_7" src="https://user-images.githubusercontent.com/105013306/166996419-18e56667-ea16-4e2c-8e10-bbc5f6692a41.png">
but after the game ended, there was nothing
![unknown](https://user-images.githubusercontent.com/105013306/166993089-7ae6e2ce-2346-4368-8323-c87f7c6fa1b6.png)
<img width="1033" alt="Screenshot_5" src="https://user-images.githubusercontent.com/105013306/166994144-530fde93-65d3-47b9-86f0-414858146441.png">

_Originally posted by @Marunc1 in https://github.com/RCVolus/league-prod-toolkit/issues/107#issuecomment-1118923937_

**Comment by sdomi4** [comment]
https://github.com/RCVolus/league-prod-toolkit/issues/107#issuecomment-1118980006

**Comment by sdomi4** [comment]
As far as I can tell, there are multiple things at play here:
- To find a live game, you do need to search for a player currently in that game, searching for spectators does not work
- Not all games are available on the API (specifically custom games without tournament codes). The game from your example is not present in the matchv5 API, probably due to the game type
- Since tower kills are showing up properly, there should not be any issues in displaying level ups / item purchases (I just tested this on the latest release). Could you confirm that you are running the newest version (1.1.0) with all modules up to date and have items and levels configured?

**Comment by Marunc1** [comment]
Sure, this is the version of it
```
"name": "league-prod-toolkit-core",
  "version": "1.1.0",
```
as for items and lvl config
```
{
  "plugin-webapi": {
    "apiKey": "deleted",
    "server": "EUN1"
  },
  "module-league-champselect-ui": {
    "backend": "ws://localhost:8999"
  },
  "module-league-static": {
    "last-downloaded-version": "12.8.1"
  },
  "plugin-database": {
    "clusterUrl": "localhost",
    "port": 27017,
    "user": "deleted",
    "password": "deleted"
  },
  "module-league-in-game": {
    "items": [
      "Consumable",
      "Epic",
      "Legendary",
      "Mythic"
    ],
    "level": [
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17"
      "18"
    ]
  },
  "auth": {
    "enabled": true,
    "secreteKey": "deleted",
    "super-api-key": "deleted"
  }
}
```

**Comment by Marunc1** [comment]
The show inhibitors buttons are working, and as i see the config is reseting, i restarted it , and now is like this
```
"module-league-in-game": {
    "items": [],
    "level": []
```

**Comment by Marunc1** [comment]
so...... i restarted the the "start.bat" like 10 times, and now it's working

**Comment by Himyu** [comment]
Did you reconfigure the events and levels you want to see in the in-game module in the browser?

**Comment by Marunc1** [comment]
nope, just restarted it, now is not reseting enymore, and works perfectly now

**Comment by Himyu** [comment]
ok perfect thanks for the feedback :)
