### ISSUE TITLE
[Question] Had a problem about database during installation process

### ISSUE THREAD

**Issue by logiclol** [RCVolus/league-prod-toolkit#113]
Hello, to be honest, I am not sure but I assume I finished the installation process correctly and I got the API key from the Riot developer website but whenever I tried to log in to http://localhost:3003/ this text shows up in cmd, and it said "key does not exist" in the localhost. I don't know what did I do wrong, could you guys help to fix my problem?
![aa](https://user-images.githubusercontent.com/53151242/167595795-be719573-4052-4c4d-b529-380c53f6c36f.PNG)
![gh](https://user-images.githubusercontent.com/53151242/167595800-f303672c-be72-4798-8c92-ab570ea11c68.PNG)

Also, I was confused during the installation process because I wasn't sure about what to type to the database questions as an answer in the cmd. Do I need a MongoDB cluster, which I can create through their website? or does the toolkit create a new database for me from the answers I typed? Sorry if I am so dumb.

Another Question: I am using the riot API for the first time and I saw the key expires every 24 hours and I have to get a new one every time it expires. What is that mean? Do I have to do the installation of the toolkit every time I got a new key? or is it enough to do once?

**Comment by sdomi4** [comment]
Hello :)

There are multiple things at play here:
- The toolkit expects an installation of mongoDB (local or remote, however you prefer, download link is in the [wiki](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation)) to store teams, casters, and matchups. A cluster hosted by them directly should work, but we have no experience using the toolkit with those. The toolkit then takes care of everything inside the databse.
- There are 2 different API Keys, one is for the Toolkit (starts with `RCVPT-`) if authentication is enabled, one is for the Riot API (starts with `RGAPI-`). To log in to the toolkit, you can find the key in the console when starting the toolkit, after that you can configure additional keys in the Api keys menu.
- Development keys need to be refreshed every 24 hours and are for testing only. We have applied for a production key, so configuring an API key locally will no longer be necessary in the future (any updates on this will be in #98)
