### ISSUE TITLE
Can I change the sizes of font?

### ISSUE THREAD

**Issue by kdoo4000** [RCVolus/league-prod-toolkit#114]
I knew how to customize my own theme, but I couldn't change the size of fonts.
During champ select, font size of summoner's name was too small, so I want to make it bigger.

Sorry for my bad English :(

**Comment by sdomi4** [comment]
Unfortunately, there is no easy way to change fonts, as larger text would not fit inside (and we didn't think anyone wanted to change it).
You can download the whole source including submodules manually, change the source, and then manually configure and build things.
The steps should be:

1. `git clone` the current main branch
2. change to the toolkit folder and run `git submodule update --init --recursive` to download all submodules
3. run `npm install` to download dependencies
4. manually set the config by copying `...\league-prod-toolkit\modules\plugin-config\config.dist.json` and saving it as `config.json` (set anything you previously entered in the install script)
5. manually change the font sizes to your desired size (if you have players with maximum length names, these probably will not fit properly) in `...\league-prod-toolkit\modules\module-league-champselect-ui\src\europe\style\picks.less`
6. build the toolkit and the modules by running `npm run build` and `npm run build:modules`
7. start the toolkit with `npm start`

For every change you make to the source, you will have to re-run `npm run build:modules`.

**Comment by kdoo4000** [comment]
I'll try it. Thank you :)
