### ISSUE TITLE
[module-league-end-of-game] LCU Fallback for postgame stats when matchv5 data can't be loaded

### ISSUE THREAD

**Issue by sdomi4** [RCVolus/league-prod-toolkit#117]
Reference: #116 

For games not available in matchv5 (custom games, possibly also for TR), at least some stats can be obtained through LCU (/lol-end-of-game/v1/eog-stats-block (h/t availablevic)). We should create a fallback option which only uses LCU stats.

**Comment by Himyu** [comment]
With the newest update for module-league-state and module-league-end-of-game, the is a rudimentary fallback for end-game stats. There is no gold graph but all the rest is working.
