### ISSUE TITLE
Whenever I try and join a game my toolkit crashes and loses connection

### ISSUE THREAD

**Issue by ChaosMagicChuck** [RCVolus/league-prod-toolkit#120]
I am very very green when it comes to code and things of this nature so I apologize if the solution is staring me in the face.

But every time I run the toolkit, it starts up no problem, mongoDB works great, all modules seem to be operational. but as soon as I click past the "Play" button on the client, the npm start window closes and the observer loses connection and nothing works. what info do I need to try and gather to show where I'm going wrong? I see no errors anywhere besides the lost connection one

okay I tried relaunching client while in the lobby and this error message kept popping up from the League Observer Tool
![possible errors](https://user-images.githubusercontent.com/108960262/178081375-0ac4c974-e1a0-4dbf-93e7-450479c8907a.JPG)
.

**Comment by Himyu** [comment]
Would you please provide us with the version of the tool you have installed and a screenshot of your module page so we can see which versions of modules you are using?

**Comment by ChaosMagicChuck** [comment]
![toolkit version](https://user-images.githubusercontent.com/108960262/178118246-954f5ac7-df18-44c9-b483-6ad06667b1e2.JPG)
![module versions](https://user-images.githubusercontent.com/108960262/178118248-22d3642a-3045-4d70-b014-340ceb1a1a41.JPG)
![loltoolkit screencap](https://user-images.githubusercontent.com/108960262/178118251-943c4d9d-c5c7-4b37-8ad2-ac3d952c8a77.JPG)

this was after I redownloaded and installed/ran the 1.1.0 package

**Comment by Himyu** [comment]
After reinstalling, do you still get the same error?

If so which client do you use and in which region are you located?

**Comment by Himyu** [comment]
This probably was due to a missing release for the observer tool. Please try to update you observer toll by just restarting it and trying again.
