### ISSUE TITLE
Choosing server on installation for Garena servers

### ISSUE THREAD

**Issue by vn-nthh** [RCVolus/league-prod-toolkit#121]
If I'm playing on VN server, which is not a Riot server, how can I specify that in the installation process?

**Comment by sdomi4** [comment]
As far as I am aware, Garena Servers do not have any public APIs, so the API-dependent features will not work (runes and postgame). To use the other features, you can just select any server, this will not cause any issues.

**Comment by vn-nthh** [comment]
I see, and I assume this is also true for the Riot API part, too. Thank you for your time.

**Comment by PLAK-Pyramid** [comment]
Cơ bản thì cứ dùng mặc định, nếu muốn đổi thành tiếng việt thì kiếm chỗ server chuyển thành VN_vn là xong
