### ISSUE TITLE
[ Question ]

### ISSUE THREAD

**Issue by jy7112** [RCVolus/league-prod-toolkit#123]
Hi,
I have a problem when I launch start.bat file.
![3](https://user-images.githubusercontent.com/109685209/180033433-b37ea2fd-dac6-4017-a576-fb38fff65b6b.png)
This is a screenshot of cmd when I launch it, and it closes automatically instantly.
I had a problem during installation process which it could not locate package.json and some files in module folder (I don't remember them all), so I manually moved them to designated locations in windows/system32 folder.
The installation was done without any error after that, but I don't think my toolkit is working properly.
Could you help me with this?

Thank you very much!

**Comment by Himyu** [comment]
There seems to be an issue with the authentication in the tool
To use the tool, for now, please deactivate it if you don't need it.
You can do that in module -> plugin-config -> config.json 

There will be a patch in a few days to fix that. So you will be able to use auth again.

**Comment by Himyu** [comment]
Oh and pls move the tool out of the System32 folder somewhere else 
Since this is a security concern.

**Comment by jy7112** [comment]
Thank you so much it works now!

Also, I extracted all files to C:\Program Files\Riot Community Volunteers\League Observer Tool.
I only moved a few necessary files mentioned during installation process (install.bat) to system 32 folder.
Do I still remove all the files I moved from system32?

**Comment by jy7112** [comment]
![4](https://user-images.githubusercontent.com/109685209/180130420-6f0f0dfe-d4c5-41a3-9c18-7d6146e7f3e8.png)
This is what happens if I don't put folders or files to system32

**Comment by Himyu** [comment]
You should create a folder only for the prod-tool somewhere on your hard drive and all files from this repository need to be in the same folder. There should not be any files in system 32

**Comment by sdomi4** [comment]
Just to reinforce; install.bat must not be moved from the extracted directory. If a Windows security message pops up, you can safely ignore this (or double check the contents of install.bat if you want to be sure).
The installer relies on the required files/folders to be present, this is why it failed when it was moved out of the toolkit folder.

**Comment by jy7112** [comment]
Ok,
I have extracted all files to C:\league-prod-toolkit-1.1.0 and ran install.bat without adding any files to system32
![5](https://user-images.githubusercontent.com/109685209/180162572-e545d551-d279-438b-a28e-62415647f1b5.png)
and I get this message which is the first one I got yesterday.
So I put package.json to system32 and it told me it cannot locate dist and module folders, so I put folders again and it worked well.
If I am not supposed to add anything to system32 then  I think it is a installation bug if I have done everything correct.
I am also attaching the log files if it helps.
Thank you.
[2022-07-20T10_27_27_142Z-debug.log](https://github.com/RCVolus/league-prod-toolkit/files/9157470/2022-07-20T10_27_27_142Z-debug.log)
[2022-07-20T10_49_39_090Z-debug.log](https://github.com/RCVolus/league-prod-toolkit/files/9157474/2022-07-20T10_49_39_090Z-debug.log)
[2022-07-21T08_02_59_541Z-debug.log](https://github.com/RCVolus/league-prod-toolkit/files/9157502/2022-07-21T08_02_59_541Z-debug.log)

**Comment by sdomi4** [comment]
Are you running the installer as admin? This should not be necessary and can cause this problem. Please try running the installer in your normal user context.

**Comment by jy7112** [comment]
Yes I have been running as admin. For some reason I thought it was necessary.
![6](https://user-images.githubusercontent.com/109685209/180168518-74ada33b-41f9-41fd-bda6-e6bcc5ec801c.png)
This is what I see when I run the installer in normal user context

**Comment by jy7112** [comment]
Oh nevermind about the one above.
I just forgot to extract other folders.

**Comment by jy7112** [comment]
I think it is all fixed now!
Thank you very much for your time and help guys!!

**Comment by jy7112** [comment]
Hi,
I have another question about api keys.
I am getting error messages  when I access API keys in localhost:3003.
![1](https://user-images.githubusercontent.com/109685209/180482160-62a6523b-c9af-489d-b82d-5a29329c8f3e.png)

I have looked issues regarding API keys and please correct me if I am wrong, that API key is not RIOT API but related to authentication which has some issues right now.
Is the tool still can be used without the authentication?
Also, can I get an idea when the next patch will be?

Thank you very much

**Comment by Himyu** [comment]
Oh yea that's related to the same issue with auth I mentioned before 
This still needs fixing on our side.

**Comment by Himyu** [comment]
If you update the database plugin this issue should also be gone now.

**Comment by jy7112** [comment]
Thank you it works!
![2](https://user-images.githubusercontent.com/109685209/180853529-d298830a-ae8c-4873-b244-69f0fc72d7cf.png)
However I don't think my End of Game page is fetching correct font or default theme..

**Comment by jy7112** [comment]
Thank you it works now!
![2](https://user-images.githubusercontent.com/109685209/180858057-41ac571c-7e8e-4c78-b0e6-c25abd24869f.png)
However I don't think it is fetching the right font or default theme...can I get a help on this?

Thank you
