### ISSUE TITLE
Advice on modifying champselect.ui module for 1v1

### ISSUE THREAD

**Issue by TroubledPrawn** [RCVolus/league-prod-toolkit#125]
Hi there!

I was trying to modify the champselect.ui module for 1v1 and 2v2 overlay instead of the 5v5. I have been looking through the scripts to see where I could attempt this but have not had much success. I was able to change dimensions of the box width but was hoping to just remove the other player positions from the overlay entirely whilst retaining the pick and ban functionality. 

Any suggestions or advice would be massively appreciated!

**Comment by sdomi4** [comment]
I have just made a [repository](https://github.com/RCVolus/lol-pick-ban-ui-3v3) with a quick 3v3 modification public, you can check out the changes made in the latest [commit](https://github.com/RCVolus/lol-pick-ban-ui-3v3/commit/a44507245a0aba684a0767813a0158efab5e2876) there to view the necessary changes for other team sizes.

**Comment by TroubledPrawn** [comment]
Amazing thanks! Ill check it out, do you know if its possible to run this pick and ban ui while also using league-prod-toolkit for other game events? I only ask because it looks like this is a modification of a standalone pick and ban ui as opposed to the whole prod tool kit

**Comment by sdomi4** [comment]
Sorry, I didn't see this was in relation to the toolkit at first :(

The modifications should be the same or comparable in the module code. The relevant files in the toolkit module should be `/src/europe/Overlay.jsx` and `/src/europe/style/picks.less`

**Comment by TroubledPrawn** [comment]
No worries! You are awesome, I'll try making those adjustments in the two files you mentioned! I was not even close to looking in the right place to make the edits.. Just wondering. it looks like you removed the bans, is that correct?

**Comment by sdomi4** [comment]
Yes, this removes bans as the 3v3 format we modified for had no bans. If your format has bans, just leave them in (or modify accordingly) :)

**Comment by TroubledPrawn** [comment]
Yep I figured that's why you did it, just wanted to check! Thanks again for your help

**Comment by VillyGH** [comment]
[UPDATE] I just forked your project @sdomi4 and updated it to create a working 1v1 graphic with toggleable music in champion select [https://github.com/VillyGH/lol-pick-ban-ui-1v1](https://github.com/VillyGH/lol-pick-ban-ui-1v1)
