### ISSUE TITLE
What server to select I'm from SEA

### ISSUE THREAD

**Issue by cedrickalegroso** [RCVolus/league-prod-toolkit#126]
Hi, I'm trying League-prod-toolkit with the valorant-observer-tool but on the installation(install.bat) it's asking me to select a server. Is this related to the server where I use my Valorant Account? if yes, SEA is not shown on the list what should I select? Thank you!

**Comment by Himyu** [comment]
There are still some issues with that regarding the valorant observer tool
But there should be a patch in the next couple of days to fix this issues.

**Comment by Himyu** [comment]
And the Server selection is only relevant for League of Legends and not valorant
