### ISSUE TITLE
Is there an easy way to run the installation on an ubuntu server?

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#127]
I would like to run the toolkit on an external ubuntu server, but I am unsure about the npm install.bat since this seems like a windows thig. 

Is there still an option to run this?

**Comment by figyl** [comment]
Hey, 

Create a directory for the latest release:
`mkdir ~/league-prod-toolkit`

Download the latest release:
`wget -O ~/league-prod-toolkit/prod-toolkit.zip https://github.com/RCVolus/league-prod-toolkit/releases/download/v1.2.11/prod-toolkit.zip
`

Unzip the latest release
```
cd ~/league-prod-toolkit
unzip prod-toolkit.zip
```

As for the install you can issue these commands one by one or save them in an install.sh file for later execution.
```
npm i --production
node ./dist/scripts/install.js -plugins theme-default
node ./dist/scripts/setup.js
```

After the install you can run the application with
`npm start`

If you run into errors make sure your nodejs version is 16.16.0 (LTS). You can do this by issuing:
`node -v`

If its not the above version you can issue the command below to change it
`sudo n stable`

**Comment by MaximilianRu** [comment]
Error: Cannot find module '/root/.dist/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Sadly the server can't find the correct module.. what am I missing?

**Comment by sdomi4** [comment]
looks like you are either running the command as root (should work fine without if permissions are set up) or your install.sh is saved outside of the toolkit directory.

You should be fine if you either include a `cd /path/to/toolkit/` in your install.sh or if you save the script in the toolkit directory and run it without sudo
