### ISSUE TITLE
Valorant Static not working

### ISSUE THREAD

**Issue by Himyu** [RCVolus/league-prod-toolkit#128]
**Describe the bug**
Apparently, in some cases, the module for valorant static gets not loaded properly or the static files them selves get not downloaded properly

**Screenshots**
https://user-images.githubusercontent.com/59684822/183310927-c8b5d592-2604-4965-83c5-baf2d90ef5d9.png

**System:**

- OS: Windows
- Version: 1.2.0

**Additional context**
This is a reference to the issue https://github.com/RCVolus/valorant-observer-tool/issues/2 form @sod101316
But since the original problem has nothing to do with the new problem it will be tracked here from now on.

**Comment by Himyu** [comment]
We cant reproduce that problem internally could you please verify that you still have that problem .

**Comment by sod101316** [comment]
yes this issue is still going on

**Comment by Himyu** [comment]
@sod101316 can you please update the prod toolkit and all the modules to the newest version and try it again? If the issue is not fixed feel free to reopen this issue :)
