### ISSUE TITLE
Api Keys don't work

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#129]
**Describe the bug**
I added some Api keys and tried to log in with them, but it failed (no such api key found)

**Expected behavior**
easy login per generated api key

**Additional context**
Actually I am not quite sure, whether the login to the tool is only for the admin key, or all the generated keys

**Comment by Himyu** [comment]
Could you please tell us which version of the prod tool you downloaded and which node version you currently use?

**Comment by MaximilianRu** [comment]
Oh yeah sure, 
current release (v1.2.0)
and node version 16.16.0
