### ISSUE TITLE
Currently, none of the modules under Game State are running

### ISSUE THREAD

**Issue by GeNeRaLcArRoT** [RCVolus/league-prod-toolkit#130]
All of the modules display "Not Running". 

I try to type in game codes and they don't do anything, the cmd displays:
 [info ] module-league-state: Loading livegame failed for gameId=xxxxxxxxxxx
 [info ] plugin-webapi: Fetching match data for matchid=undefined
 [error] plugin-webapi: Failed to get match information for matchId=undefined. Maybe the match is not over yet? error=Error: Request failed with status code 403

I did however check the Riot API status and it says that everything is working except Match-V4:
![image](https://user-images.githubusercontent.com/112106245/186740049-950baed8-7bfa-478a-bb19-96e9bb5bd1c6.png)

I wanted to ask if this is the part of the API that the code utilizes even though it doesn't say the EUW API is down?

**Comment by sdomi4** [comment]
Hello :) The game state module status isn't a good indicator of whats working and what isn't...
The 403 status code indicates that the match lookup didn't work due to an expired/invalid API key.
The modules relying on the riot API need a valid API key configured in the config file (`...\prod-toolkit\modules\plugin-config\config.json`). We are working on providing a backend so this will no longer be needed.

**Comment by GeNeRaLcArRoT** [comment]
Hello, thanks for the quick response. So if I go to the Riot developer api website and I see my api key has expired, do I have to generate a new one and just insert it into the config file? That would mean that I would have to get a new key and insert it every 24 hours ( I noticed they expire after 24 hours)? - I just did this and it's working now

So yesterday when I made the message, the champ select module and end of game wouldn't work. So champ select wouldn't show up on the graphic and post game wouldn't load for any games. We also tested it yesterday on 3 PCs in 3 different countries and it didn't work. I tried champselect before I changed the api key today and it worked.
So I'm guessing that the champ select isn't actually processed by the api and it just takes the info from the client while post game (obviously) needs the api. And I guess champselect didn't work yesterday because of a problem on riot's side?

Thanks a lot for the help!

**Comment by sdomi4** [comment]
Yes, the development key is for testing only and has to be updated every 24 hours. We are working on a backend for these API queries, see #98 for progress.
[This wiki page](https://github.com/RCVolus/league-prod-toolkit/wiki/2.-Using-Prod-Toolkit) lists which module needs the API.

It's hard to say retroactively why champ select wouldn't have worked. Champion select only relies on the LCU API which is present locally.

**Comment by GeNeRaLcArRoT** [comment]
Ok, great, thank you so much for the help!
