### ISSUE TITLE
rcv-gfx

### ISSUE THREAD

**Issue by RealShavy** [RCVolus/league-prod-toolkit#131]
![Unbenannt](https://user-images.githubusercontent.com/112900251/188502152-470e571f-c51b-4f37-8759-4804dd1c7abf.PNG)
I am missing a data for rcv-gfx it's called  plugin.js

**Comment by sdomi4** [comment]
rcv-gfx is an old module which is no longer used; you can safely ignore this error.
Are you seeing this on the latest release? This shouldn't show up when launching the toolkit from the prebuilt version.

**Comment by RealShavy** [comment]
I got this error when I updated the modules. And what do you mean by ignore I'm not so good with it!

**Comment by sdomi4** [comment]
Did you download the raw code or the [release version](https://github.com/RCVolus/league-prod-toolkit/releases/latest)? The release version should not include rcv-gfx.
In any case, you should not encounter any issues besides the console error with rcv-gfx, so you can ignore it.
