### ISSUE TITLE
[module-teams] Assigning players to teams

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#132]
**Is your feature request related to a problem? Please describe.**
This might be an issue to our specific broadcast needs, however during smaller tournaments (without tournament realm access or special renames/accounts by Riot) in-game player names (summoner names), and the nickname they wish to have displayed/called as during the broadcast can be different.

Currently we bridge this issue using a static overlay image and text combo:
![image](https://user-images.githubusercontent.com/73833646/188729228-b1ac21f5-16ce-44c4-8cee-658be1806c21.png)

This approach has its issues, since during an unexpected early lane swap, we have to do additional work to reassign the player name after swapping the teams in-game on the scoreboard to their proper position.

**Describe the solution you'd like**
I believe creating in-game name and nickname pairs for teams in the teams module (or in a separate module) could be used to enable smaller tournaments to override nicknames.

After linking in-game names with preferred nicknames precisely [module-league-in-game] could also include an overlay for the preferred nickname for each player.
If a team doesn't have a list of preferred nicknames but their opponent does, it could just show the in-game name resulting in an even look throughout the tournament.

**Describe alternatives you've considered**
As for alternatives I can only think of worse ways to do this. Currently we pull these names from a google sheet which is semi-automatic.

**Additional context**
in-game name: league of legends summoner name (eg.: |||III|I|||I|)
nickname: players' established nickname in the(ir) community (eg.: BigJohn23)

**Comment by figyl** [comment]
A nice addition to this would be the possibility to override these nicknames in the pick-ban phase as well.

**Comment by Himyu** [comment]
This is also related to #36

**Comment by Himyu** [comment]
with the newest version for the module-league-state (https://github.com/rcv-prod-toolkit/module-league-state/releases/tag/v4.9.0) we added the option to give players a nickname from the lobby, champ select, and in-game. (Not working in end of game yet)
