### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ledainghia** [RCVolus/league-prod-toolkit#136]
Error: Cannot find module install.js and setup.js? how to fix it?

there are not dist folder  In league-prod-toolkit-main folder

**Comment by sdomi4** [comment]
I am unable to reproduce this with the newest release.
Did you extract the toolkit directory? If you launch the install.bat within the zipped folder, this error can occur.

**Comment by ledainghia** [comment]
In install.bat use powershell -Command "& {node ./dist/scripts/install.js -plugins theme-default}"
powershell -Command "& {node ./dist/scripts/setup.js}"

But in newest version you moved all folder the entire folder out of the dist  folder  
![image](https://user-images.githubusercontent.com/92242188/191143252-db6617ab-0ab8-4779-bca2-13eb32b2b801.png)


And all .js files changed to .ts

So I cannot run start.bat

**Comment by sdomi4** [comment]
The installer is intended for use with the prebuilt [release version](https://github.com/RCVolus/league-prod-toolkit/releases/latest). If you are downloading the source, please refer to the build instructions in the readme.

I have tested the installer on a fresh download of the current release and can confirm everything is working as intended.
