### ISSUE TITLE
Font issue and champ select crash

### ISSUE THREAD

**Issue by discodanz** [RCVolus/league-prod-toolkit#137]
Font not loading accurately - Console log below:

"Refused to apply style from 'http://localhost:3003/pages/op-plugin-theming/active/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

When selecting champ select module the system crashes reporting this error:

[Error: ENOENT: no such file or directory, open 'C:\League of Legends\modules\module-league-champselect-ui-main\build\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\League of Legends\\modules\\module-league-champselect-ui-main\\build\\index.html'

After looking at the directory there seems to be a missing file?

**Comment by Himyu** [comment]
This error should be fixed in the newest version of the champselect-ui v1.5.3

**Comment by discodanz** [comment]
Thank you Himyu, Did you have an ETA on this patch?

Cherers

**Comment by sdomi4** [comment]
The new version is already released :) You can update it in the module overview and then relaunch the toolkit.
