### ISSUE TITLE
TR api support

### ISSUE THREAD

**Issue by discodanz** [RCVolus/league-prod-toolkit#138]
Would be great to have post match API support for the TR clients for official private matches being played

**Comment by Himyu** [comment]
Unfortunately, there is currently no way to do that but we have a look into it

**Comment by discodanz** [comment]
Thank you, Happy to test once / if you manage to get it up and running.

**Comment by figyl** [comment]
A year ago I was able to get some data via the `/lol-end-of-game/v1/eog-stats-block` LCU endpoint on every tournament realm.
Had to poll it really fast though (every 1ms). Not sure if this still works, I currently have no way to test it.

**Comment by Himyu** [comment]
Technically ```lol-end-of-game/v1/eog-stats-block``` is an option to get game data. the problem with that is it does not include any timeline, which means there would only be normal stats and maybe a damage graph but no gold graph or anything like that.

**Comment by figyl** [comment]
That I am perfectly aware of. 
Here is a graphic we used based on the available data:
![image](https://user-images.githubusercontent.com/73833646/194113164-952fabd5-7de4-4399-9d86-f97194da8f31.png)
We had to fill the dragons / towers by hand though.

**Comment by Himyu** [comment]
With the newest update for module-league-state and module-league-end-of-game, the is a rudimentary fallback for end-game stats. There is no gold graph but all the rest is working. if that works in TR as well has to be tested.
Drakes and Bans are not yet included

**Comment by Himyu** [comment]
Since we now know that our in-game features are working in the tournament realm as well, wi will try to generate some end screen with data from  the in-game API

**Comment by Freeedooo** [comment]
> Since we now know that our in-game features are working in the tournament realm as well, wi will try to generate some end screen with data from the in-game API

Did Riot Games synced the offsets for farsight with the live server? Is it irrelevant for the farsight module if we play on live servers or on TR?

**Comment by sdomi4** [comment]
No, offsets depend on the game version, but the observer tool _should_ automatically detect the game version and use the correct offsets.

**Comment by Freeedooo** [comment]
@sdomi4 ok, got it! So it should work on TR even with older versions of the game since there are any offsets available?

**Comment by sdomi4** [comment]
Yes, we have offsets covering every version that should currently be on TR. Can't say for sure it will work on a specific version since we rarely/never test on TR.

**Comment by Freeedooo** [comment]
All right! I will test next week on the TR and report back to you after the weekend. I got a big offline tournament running next weekend.

**Comment by Himyu** [comment]
Is there any update regarding that testing @Freeedooo?

**Comment by Freeedooo** [comment]
First of all: **IT DID WORK!**

But there is a downside to my testing. There was this major bug in the observer tool [https://github.com/RCVolus/league-observer-tool/issues/21](url) you fixed afterwards. But at the time of my offline-event it was there and crashed. But as i said: It worked quite fine until then!

**Comment by Himyu** [comment]
ok perfect, thanks for the information
