### ISSUE TITLE
[ Question ] What could i do wrong?

### ISSUE THREAD

**Issue by Superasny** [RCVolus/league-prod-toolkit#139]
Everything work correctly (lobby, champ select, in game overlay) but for some reason module league state can't can't get information for  summoners tested on eune euw and kr 
![problem](https://user-images.githubusercontent.com/114825227/193449506-e0a80346-e344-44c4-913e-797589c1d7c5.png)

**Comment by figyl** [comment]
Hey, please make sure you are using a correct riot API key.


Usually developer keys are only valid for 24 hours. You can either register an application, or use your developer key. Please make sure however that you update your API key in the following file:
_modules/plugin-config/config.json_
