### ISSUE TITLE
League Observer Tool not connecting

### ISSUE THREAD

**Issue by gabepontes** [RCVolus/league-prod-toolkit#140]
I am trying to connect to the observer tool I have LoL client open and everything, but it does not connect. I think it could be the server API key I used. For it I used the riot RGAP api key. 
![Screenshot (3)](https://user-images.githubusercontent.com/92276505/194653318-9c14cda1-959f-4ef4-9abc-913ce0a8dfb9.png)

**Comment by Himyu** [comment]
Can you please try to turn off the authentication at the prod toolkit? And if that fixes the issue, it is caused by the server API key.

**Comment by ghost** [comment]
I'm having a similar issue, idk if I'm doing anything wrong

(I've also posted this here to avoid creating another thread)

![Screenshot_5](https://user-images.githubusercontent.com/36971306/196055576-ff7181b9-32ab-44ff-a81d-55d3407c0144.png)
![screenshot_6](https://user-images.githubusercontent.com/36971306/196055577-906425f8-cc98-46ea-8589-a4b01fd6b6be.png)

**Comment by sdomi4** [comment]
Could you confirm you have a correct Toolkit key configured (starts with "RCVPT-")?
Does it work with the default admin key?

If you are only running the toolkit locally, you should be fine to turn of authentication anyways :)
