### ISSUE TITLE
Stuck on "installing dependency for plugin theming"

### ISSUE THREAD

**Issue by stXwinter** [RCVolus/league-prod-toolkit#141]
Just stuck on this while running the install.bat file on prod-toolkit
![Capture](https://user-images.githubusercontent.com/44768100/194698263-c5a293e4-22d5-4dc1-b970-13ce4396ea46.PNG)

**Comment by Himyu** [comment]
As far as I can see you have node version 10.x and we recommend using node version 16.x 
Please check if that can fix this issue

**Comment by stXwinter** [comment]
> 

Hi thanks it finally installed but now when I run the start.bat file this comes up
![Capture](https://user-images.githubusercontent.com/44768100/194749069-5847f86e-b380-4983-af00-2c6a4c863cae.PNG)

**Comment by Himyu** [comment]
This is because there is no config file. Just run the install.bat once more and finish all the setup steps within and you should be good to go.

**Comment by stXwinter** [comment]
> This is because there is no config file. Just run the install.bat once more and finish all the setup steps within and you should be good to go.

Thanks once again lol for the help but now getting this on the start.bat
![Capture](https://user-images.githubusercontent.com/44768100/194749997-5a600195-1f1a-4b77-b854-ea93f54733f6.PNG)
I just keep running into errors sorry

**Comment by stXwinter** [comment]
> This is because there is no config file. Just run the install.bat once more and finish all the setup steps within and you should be good to go.

![Capture](https://user-images.githubusercontent.com/44768100/194750073-75d0d6eb-270d-402e-acda-4a01b1b78cce.PNG)

**Comment by stXwinter** [comment]
> This is because there is no config file. Just run the install.bat once more and finish all the setup steps within and you should be good to go.

Ended up just running start.bat again and I think it is working but now getting an unexpected server response:403

![Capture](https://user-images.githubusercontent.com/44768100/194750467-bd7e3aa5-2560-4c78-b862-d4064b4b0330.PNG)

**Comment by sdomi4** [comment]
This looks like an issue with authentication, please make sure the Observer Tool has a valid key configured or disable authentication and try again.

**Comment by Himyu** [comment]
All the problems mentioned in this issue should be fixed now with version v1.2.6.
