### ISSUE TITLE
[ Question ] Post game stats on custom game

### ISSUE THREAD

**Issue by BlossomSysteme** [RCVolus/league-prod-toolkit#143]
Hey all! I'm a broadcast manager for a collegiate esports org, and we love your tool! Recently we just had our first broadcast with it, and we were struggling to set up post game stats for custom games specifically, as they arent technically in the riot games server as stats we can pull. we tried setting the game using a username during the live game, however it didnt seem to use the stats for the post game graphics system. Any thoughts/ideas? Am I dumb and it just wont work for custom games? Anyways thanks again!

p.s. We do have a riot games dev account and api key, and it was updated in the program for this event.

**Comment by Himyu** [comment]
Yes, custom games are not included in the riot API. But we are currently working on a fix for that See #117 for more information and updates .

**Comment by figyl** [comment]
We have just completed a tournament series with this tool. We used battlefy to manage the bracket and used the tournament codes for the lobbies. It worked like a charm.

**Comment by Himyu** [comment]
That's because custom games created as a tournament game are included in the API and therefore can be fetched after the game and as a live game as well

**Comment by OrionCodeDev** [comment]
wdym "as a live game as well"? It's will response with current state of game ?

**Comment by Himyu** [comment]
Yes, the spectator v4 API includes some tournament code games as well although we starting to notice it depends on the setting with such the code was created.
We are still in the process of figuring out the right setting.

**Comment by Himyu** [comment]
With the newest update for module-league-state and module-league-end-of-game, the is a rudimentary fallback for end-game stats. There is no gold graph but all the rest is working. if that works in TR as well has to be tested.
Drakes and Bans are not yet included
