### ISSUE TITLE
Crashed while Starting Toolkit on Fresh Install 

### ISSUE THREAD

**Issue by Rookie001MC** [RCVolus/league-prod-toolkit#147]
**Describe the bug**
After downloading and installing LoL Toolkit, I executed `start.bat`. All was going well until I hit some kind of permission error:
![image](https://user-images.githubusercontent.com/22286534/199085368-11c89515-cfd2-417f-b40f-f57e4e5424d6.png)

I even tried to downgrade to v1.2.9 but still got the same error.

**System:**

- OS: Windows 11 x64
- Node: v18.12.0
- Version: v1.2.10 and v1.2.9

**Comment by sdomi4** [comment]
We develop and test on Node 16.7. Could you try downgrading and see if the same issue occurs?

**Comment by Rookie001MC** [comment]
Yep, still occurs after switching to 16.7.
![image](https://user-images.githubusercontent.com/22286534/199088441-e2634a6c-dccf-4dab-9cd7-91f18eed5b50.png)
![image](https://user-images.githubusercontent.com/22286534/199088555-9eee724a-2069-48dd-a837-2b8cd01a0c47.png)

**Comment by Rookie001MC** [comment]
Since this is some kind of permission error, I went ahead and tried to:
- [disable indexing](https://stackoverflow.com/questions/27845251/npm-install-give-error-eperm-unlink/51092497#51092497) - still doesn't work
- set "Full Access" permission to Everyone just for testing - doesn't work
- running it as Admin - doesn't even work

**Comment by sdomi4** [comment]
This is a bug in the league-static module, I can reproduce it as well.

As a short term workaround, you can downgrade the module to [3.6.11](https://github.com/rcv-prod-toolkit/module-league-static/releases/tag/v3.6.11) by downloading the release and copying the files into `...\prod-toolkit\modules\module-league-static` and overwriting the existing files.

We will update here once a new release with a fix is available.

**Comment by Rookie001MC** [comment]
> This is a bug in the league-static module, I can reproduce it as well.
> 
> As a short term workaround, you can downgrade the module to [3.6.12](https://github.com/rcv-prod-toolkit/module-league-static/releases/tag/v3.6.11) by downloading the release and copying the files into `...\prod-toolkit\modules\module-league-static` and overwriting the existing files.
> 
> We will update here once a new release with a fix is available.

Downgraded to 3.6.11 worked for me. Looking forward to you guys pushing the new patch soon!

P.S. You mistyped 3.6.11 as 3.6.12 😅

**Comment by sdomi4** [comment]
The issue should be resolved with [3.6.14](https://github.com/rcv-prod-toolkit/module-league-static/releases/tag/v3.6.14). You can install the update manually as before or update through the module page in the toolkit.
