### ISSUE TITLE
LeagueProdKit can't be started : error Module not found

### ISSUE THREAD

**Issue by VictorMartin-fr** [RCVolus/league-prod-toolkit#148]
Hello,

Since 2 days when I tri to start a fresh new league Prod Kit instance, I have the error "Module not found" at the step "finish moving files to frontend"

![image](https://user-images.githubusercontent.com/73833511/199221907-8096a76d-d96f-4e25-8f8a-44b85f87656a.png)

I tried to install other version : 
=> 1.2.11 : NOK
=> 1.2.10 : NOK
=> 1.2.9 : NOK
=> 1.2.8 : NOK

For information, I don't encountered any errors when I use "install.bat", I install all themes and modules for League of Legends and valorant.

Do you know how can produce this error ?

Step to reproduce : 
1. download last release
2. execute "install.bat"
3. execute "start.bat"

Thanks you in advance for your help :)

**Comment by sdomi4** [comment]
This was a bug in the league-static module (unrelated to the toolkit version).
The bug is fixed with v3.6.15 of module-league-static and the toolkit should start without issue on a fresh install.
