### ISSUE TITLE
Can't launch the Prod Kit (it can't find the config.json and new patch from CDragon)

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#149]
**Describe the bug**
Clear install of Windows and the Prod Kit (most recent package available). After installing everything, when I try to launch the install.bat, I can't access the localhost. When I press a key, the start.bat closes. If I try to reopen it, it restart all the process, same errors. (I tried to wait and to restart my PC, even downloaded the predecent version, same error.

**System:**

- OS: Windows 10
- Node: 16.7
- Browser: Edge

I've highlighted two errors that maybe are related to this problem...

![image](https://user-images.githubusercontent.com/89284738/199360320-6eb67e09-e07e-418e-ae51-d18cf8dca626.png)

**Comment by Himyu** [comment]
Can you use the install.bat without any problems or can you post a screenshot of that on a fresh install?

**Comment by Himyu** [comment]
And for the second issue with the missing item.bin.json, that's because this file is from the community Dragon and that takes a few days after a new patch before it's updated 
To fix this issue set the static version to the last patch for now 
We wiki for more info

**Comment by FireFoXz09** [comment]
Fresh install with the install.bat

![image](https://user-images.githubusercontent.com/89284738/199363833-964c3484-65df-46b0-ac34-ba1a563aa563.png)

**Comment by Himyu** [comment]
And for the second issue with the missing item.bin.json, that's because this file is from the community Dragon and that takes a few days after a new patch before it's updated 
To fix this issue set the static version to the last patch for now 
We wiki for more information

**Comment by Himyu** [comment]
Ok there was a patch for the prod toolkit to fix this issue please try updating it and try again

**Comment by FireFoXz09** [comment]
No more errors during a fresh install, but now I got this...

![image](https://user-images.githubusercontent.com/89284738/199365304-5d93ef48-b96e-4425-92ac-fb8ee5184a74.png)

When I go into the config files ( prod-toolkit/modules/plugin-config/config.json) the last-downloaded-version is still empty. (So I cannot force a redownload, or I can't seem to find where to ask them to download a previous patch...)

![image](https://user-images.githubusercontent.com/89284738/199365471-268a8d2d-6031-4f26-90c9-dcabc3b7748c.png)

**Comment by Himyu** [comment]
This issue can be ignored and the static download itself is fine .
Does your tool automatically show you the message 'press any key to continue " or if you do nothing an just wait a bit longer, would it finish up and starts normally ?

**Comment by FireFoXz09** [comment]
The "press any key to continue" show automatically after the last line appears. :/ I'll try leaving it running for like 15 minutes...

**Comment by Himyu** [comment]
Ok I will have a look at this tomorrow morning and I think I already know how to fix this issue 
For now you, unfortunately, have to wait until I fix this :/ 
Sorry for that inconvenience and thanks for the feedback .

**Comment by FireFoXz09** [comment]
No stress, thanks for the update! I'll wait :D

**Comment by Himyu** [comment]
If you download the toolkit and make a fresh install, it should be fine. Please send feedback if or if not that's the case

**Comment by FireFoXz09** [comment]
First test, everything seems to work! :) Fresh install without any issues. I'll test the toolkit to see if I find any crash or bugs! Thanks for the fast help and troubleshooting!
