### ISSUE TITLE
[Feature Request][Caster module] Add "lower third only" browser source

### ISSUE THREAD

**Issue by ManuelRoyBo** [RCVolus/league-prod-toolkit#152]
**Is your feature request related to a problem? Please describe.**
Yes. The size and spacing of each lower third are fixed and cannot be easily moved/modified in OBS since the lower thirds are all on 1 webpage.

**Describe the solution you'd like**
A browser source dedicated to lower thirds (1 for each caster) so that you can import it in OBS and quickly move and scale it.

**Describe alternatives you've considered**
- Creating 2 browser sources in OBS and cropping the source only to see the lower thirds.
- I tried modifying the CSS for my personal needs. Without success.

**Additional context**
![example](https://user-images.githubusercontent.com/48164038/200096473-06b2581a-edec-4c58-afea-8f22c5dd1e40.gif)

**Comment by Himyu** [comment]
you can technically create a theme or use the obs CSS property to change the space between the two. 
But I see the point and we will look into it.

**Comment by Himyu** [comment]
with the newest version of the module caster (2.0.0), there is a link to embed each caster individually.
