### ISSUE TITLE
[ Question ] no Connection via the links 

### ISSUE THREAD

**Issue by RealShavy** [RCVolus/league-prod-toolkit#153]
The problem I have is that I can't access the websites I got via the link, either via OBS or via vMix or via my browser.

![1](https://user-images.githubusercontent.com/112900251/200141685-46f9628d-ed23-4088-b253-4118632c4d61.PNG)
![2](https://user-images.githubusercontent.com/112900251/200141686-c758c3d7-59d7-4dcf-81c3-bf9e65f0a6d3.PNG)
![3](https://user-images.githubusercontent.com/112900251/200141687-ac2312ee-d5d3-4852-abba-dc85d75d2836.PNG)

**Comment by sdomi4** [comment]
There seems to be something funky with the URL.
Can you copy&paste the link of the ingame page and the non-working overlay page for me?

They should work if you set the link to `http://localhost:3303/...`

**Comment by Himyu** [comment]
This is also due to your prod-tool version being outdated please update to a newer version to fix this issue

**Comment by RealShavy** [comment]
hi the problem was that i update it via http://localhost:3003/modules and not via Github my bad :)

**Comment by RealShavy** [comment]
it is working fine now, thx
