### ISSUE TITLE
Twitch Module does not create a prediction

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#154]
**Describe the bug**
Entering all the information as described in the wiki and saving everything, message error appears when I try clicking on the predictions buttons (start, stop, etc) and nothing else happen on the preview or on Twitch.

**System:**
- OS: Windows 10
- Browser: Edge

![image](https://user-images.githubusercontent.com/89284738/201250784-8092ba17-2bcd-460d-a50a-519d6cbe3582.png)

**Comment by sdomi4** [comment]
Do you have the newest version of the twitch module installed? There have been some updates which might resolve this.
If you are on a current version I will try to reproduce the issue tonight or tomorrow.

**Comment by FireFoXz09** [comment]
I did a fresh install of the league-prod-kit and the League Observer software yesterday, so I guess I am on the latest version. But I can double check tonight to be sure.

**Comment by Himyu** [comment]
If there still is a problem please make sure that you put in the user name for the twitch channel not the display name.
The user name can just be taken from the twitch channel URL

**Comment by FireFoXz09** [comment]
Thanks for the tip Himyu, I did try with both names yesterday (display name with capital letters and twitch channel all in lowercase) But I'll try again tonight to be sure.

**Comment by Himyu** [comment]
You were right there was still a bug in the code due to a hardcoded appId. I now fix that issue in the module's newest patch (1.0.5).

**Comment by FireFoXz09** [comment]
Good. I'll try it tonight and keep you updated!

**Comment by FireFoXz09** [comment]
Same error, "Request failed with status code 401". I updated to the latest version of the module to be sure. v1.0.5
I double checked that I have two teams selected in my module-team and they are, but I can't start a prediction. I've tried both comment above (lowercase letter like in the url (firefoxz) instead of "FireFoXz", reset the application in twitch dev, and in two differents browsers just to be sure.

**Comment by Himyu** [comment]
I am sorry that it is not working for you but to get to the bottom of that problem I added a better error login to the twitch module. if you would try to install the newest version (v1.0.6) and try again and send us the error message you are receiving, we will get closer to the solution to this problem.

**Comment by FireFoXz09** [comment]
Don't be sorry haha! I'm also trying to help the best I can! :D I'll try it again tomorrow since I'm not home for now but thanks for the fast feedback and help! :D

**Comment by FireFoXz09** [comment]
Error problem :  Resquest failed with status code 401: Unautorized. Client ID is missing.

I tried a fresh install to be sure, same thing. Following the exact steps from the Wiki to be sure.

![image](https://user-images.githubusercontent.com/89284738/201555640-1b7cda14-4c3f-4643-8c53-f9551c805219.png)

**Comment by Himyu** [comment]
Ok on which step is that happening exactly?

**Comment by FireFoXz09** [comment]
Oh sorry! Yeah when I try to start a prediction, by clicking on the green button (start a prediction) the same error appear if I click to "stop the prediction" (red button) or choose a result (but there's no result to choose from since no prediction started).

Also, when I click on the button to link my Twitch account and authorize the app to use my account, if I click on it again, I must authorize again, I dunno if it's normal or not...)

**Comment by Himyu** [comment]
Please make sure that when you first save the settings for the module you only fill in the appId and nothing else 
After that authorize with twitch and then fill in the channel name.
If you do not stick to that order there might be some issues.

**Comment by FireFoXz09** [comment]
I did this in this order yes. This is why I did a fresh install to be sure that there was no older svefiles or parameter still saved somewhere.

**Comment by Himyu** [comment]
Can you go to the plugin-config folder and check out what is in the config file for the twitch module ?

**Comment by FireFoXz09** [comment]
I'll check this and post it here when I'll be back home tonight.

**Comment by Himyu** [comment]
I deployed a new patch today maybe try that out as well and see if that does anything. for you.

**Comment by FireFoXz09** [comment]
Everything seems to work! I'll test it during our game tonight and bring feedback.

**Comment by FireFoXz09** [comment]
No problem at all during the stream. Thanks! ;)

**Comment by Himyu** [comment]
Ok perfect thanks for your feedback :)
