### ISSUE TITLE
InGame events repeating

### ISSUE THREAD

**Issue by ManuelRoyBo** [RCVolus/league-prod-toolkit#158]
**Describe the bug**
[inGame] After a player purchases an item or kills an objective, the overlay displays the event more than once. I did not notice it at the beginning because it replayed the animation 2 or 3 times. I later had to stop the League Observer Tool mid-game in order to prevent the killed herald animation from repeating. 

**To Reproduce**
I do not know. It was my first time using this tool live. I did 2 games. I did not restart anything between the 2 games. It went fine during the first game (or I haven't noticed any bugs). For the second one, a level-up appeared 2 times. Then, most level up appeared twice for the next 1-2 minutes until they started appearing three times, then four. After that, I shut down the League Observer Tool because it became annoying for the stream.
Sorry I could not give further explanations. You can question me no problem

**Twitch stream timestamps**
[Twitch stream redifusion](https://www.twitch.tv/videos/1652936844)
- 1:43:55 > Beginning of game 2
- 1:49:30 > 3 champs. Level 6 (Swain level animation replays twice)
- 1:51:15 > Kayn Lvl 6 (Replays twice) followed by Vayne LVL 6 (replays twice) followed by Brand (replays 3 times)
- 1:53:35 > Drake slain. The animation repeats.
- 1:55:15 > Herald slain. Animation repeats and stops after I shut down the League Observer Tool.

**System:**
- OS: Windows 10 Education
- Node: v16.7.0
- Browser: Chrome
- Windows Version: 21H2

**Additional stuff**
League Observer Tool cannot reconnect while In game. It needs to wait for the launcher. (That's not the issue here)

**Comment by Himyu** [comment]
First of all thanks for the detailed explanation.
I'm assuming you are using OBS? We saw that behavior when 'Refresh browser source when the scene becomes active' was checked on the browser sources.
If that is not the case for you, we have to look further into it.

**Comment by ManuelRoyBo** [comment]
> First of all thanks for the detailed explanation.
> I'm assuming you are using OBS? We saw that behavior when 'Refresh browser source when the scene becomes active' was checked on the browser sources.
> If that is not the case for you, we have to look further into it.
> 

Yes it was checked. Thank you.

**Comment by Himyu** [comment]
ok then pls try it again and if there is still a problem I am happy to have another look.

**Comment by ManuelRoyBo** [comment]
> ok then pls try it again and if there is still a problem I am happy to have another look.

I will do some more testing.

My next "serious" stream is next monday (with 3 games in a row). I will stress test it there.

**Comment by FireFoXz09** [comment]
> > ok then pls try it again and if there is still a problem I am happy to have another look.
> 
> I will do some more testing.
> 
> My next "serious" stream is next monday (with 3 games in a row). I will stress test it there.

I can confirm that I did not have this issue yesterday during our stream (we both stream for the same league, different teams tho). And I had the "Refresh browser source when the scene becomes active" unchecked. Sounds like this could be the issue. I'll also keep an eye on my side for this issue and bring updates if needed.

**Comment by Himyu** [comment]
That's good to hear. please keep us posted :)
I will close this issue for now.
If the problem still remains feel free to reopen it.
