### ISSUE TITLE
[ Bug ] KILLFEED - Missing picture if a champion is killed by something else than an enemy champion

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#163]
**Describe the bug**
If a champion is executed (killed by a dragon or baron, for example), the killfeed return an empty image for who killed the champion.

UPDATE : Fountain and Turrets execution seems to show the turret icon properly. It also works with minions. Only neutrals monsters (Drake, Baron, Herald and jungle) cause the bug/error.

![image](https://user-images.githubusercontent.com/89284738/202940276-3cf23cfb-4213-4f34-a276-2f6b571dd8ad.png)

**Comment by Himyu** [comment]
i just released v3.3.12 for the module-league-in-game. If you could test it again at best in the same game and could let us know if it worked that would be great :)

**Comment by FireFoXz09** [comment]
Strange, when I tried to update the module, there was no button to download it or update.
![image](https://user-images.githubusercontent.com/89284738/203143645-00564567-977d-4afc-9778-8e83905de117.png)

So I did a fresh install elsewhere on my PC, and after double checking that I have the 3.3.12 version...
![image](https://user-images.githubusercontent.com/89284738/203143786-e37e9294-9120-44b9-94c6-b20ceb3acfa4.png)

Still an error with Baron, Dragon, or jungle monsters.

Killed by the blue buff (Blue Sentinel)
![image](https://user-images.githubusercontent.com/89284738/203143994-bda8a594-5e8a-45b9-b520-3c518ab0f5da.png)

Killed by the Baron
![image](https://user-images.githubusercontent.com/89284738/203144099-d523a82b-d82a-423e-a525-cb25de3fff38.png)

...and the dragon
![image](https://user-images.githubusercontent.com/89284738/203144206-5d6c5d75-502b-4c59-80f2-0790fa5a0bd8.png)

**Comment by Himyu** [comment]
I will have a look at that thx for letting us know!

**Comment by Himyu** [comment]
When you have checked the kill feed, please let us know as well.

**Comment by FireFoXz09** [comment]
(pressed enter too fast, updated my post)

**Comment by Himyu** [comment]
can you please export the game data from your observer tool and send it here?
![image](https://user-images.githubusercontent.com/63208379/203144536-b88cbb78-44c4-4c3f-a591-4822cd2536ee.png)

**Comment by FireFoXz09** [comment]
There you go. I had to put it in a zip file cause it won't let me upload it (and I didn't wanted to copy paste everything)

[InGame-data.zip](https://github.com/RCVolus/league-prod-toolkit/files/10060081/InGame-data.zip)

**Comment by Himyu** [comment]
Ok i found the problem and fixed that in the newest version. if you can not downloaded just go to https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.3.13 and dowload the newest release and put it in your modules folder. and i have a look at the update tools in the module page.
I also have to add new icons for Jungle Creeps, for now the will be displayed as minions.

**Comment by Himyu** [comment]
Update issues should be fixed with https://github.com/RCVolus/league-prod-toolkit/releases/tag/v1.3.4

**Comment by FireFoXz09** [comment]
Well we are going somewhere! :D Now we have something, but Baron, Dragons AND Jungle Creeps shows the "minion" icon when they kill a champion. Still better than nothing. :)

**Comment by Himyu** [comment]
Ok, my bad :) next patch it is I promise :)

**Comment by Himyu** [comment]
https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.3.14

**Comment by FireFoXz09** [comment]
BARON : it shows an empty icon and someone have slain the Baron (lol)
![image](https://user-images.githubusercontent.com/89284738/203172490-343e957d-39c6-49e3-95c8-cb30a9672e3f.png)

DRAGON : it shows an empty icon and someone have slain the Dragon
![image](https://user-images.githubusercontent.com/89284738/203172539-03715750-40a4-40b6-86da-697a4d644451.png)

Jungle works as intented for now (minion have slain a champion.
![image](https://user-images.githubusercontent.com/89284738/203172711-3d318555-9490-4d57-95cc-43ef9ce8042c.png)

And don't stress out, I'm just trying to help and test as many things I can haha, no rush to update everything now if you're busy <3

**Comment by Himyu** [comment]
No, all good I am working on it anyways and I found the problem with that as well and fixed that as well https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.3.15
Thanks for your help and all your feedback :)

**Comment by FireFoXz09** [comment]
Haha you rocks! All seems good now! I'll give it a deep test tonight during a broadcast but so far, I think you got it! ;)

**Comment by Himyu** [comment]
Perfect thank you so much ❤️

**Comment by FireFoXz09** [comment]
![image](https://user-images.githubusercontent.com/89284738/203179571-aaf03ceb-a790-45cc-aa5f-8b8ac664a7f8.png)

Now everytime a champion dies, it says that a minion killed it instead of the actual champion who killed it (with assists from champions...) xD

**Comment by Himyu** [comment]
https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.3.16
