### ISSUE TITLE
[ Bug ] Wrong amount of CS in end-game screen

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#164]
**Describe the bug**
In the end screen scene, the number of CS is wrong. It only counts minions, and not the jungle creeps/neutral minions.

**The scoreboard**
![image](https://user-images.githubusercontent.com/89284738/203325251-14897319-ac30-44a1-aece-9ade5bbc1915.png)

**The end-game screen (module)**
![image](https://user-images.githubusercontent.com/89284738/203325601-18f6c156-ba14-47af-b7e6-74fc1d1e1f54.png)

**League of Graph detailled informations**
![image](https://user-images.githubusercontent.com/89284738/203325956-2fb1ca18-b012-4a46-b5b2-2da0dbfdd062.png)

**Comment by Himyu** [comment]
there is an update including neutral creeps as well with https://github.com/rcv-prod-toolkit/module-league-state/releases/tag/v4.9.1

**Comment by FireFoXz09** [comment]
Same error of CS with 4.9.1

**Comment by Himyu** [comment]
Is that for custom games or also for games with tournament codes?

**Comment by FireFoXz09** [comment]
In both case (the original post and the bump yesterday), it was tournament code games.

**Comment by sdomi4** [comment]
The issue should be fixed when updating module-league-end-of-game and module-league-state to the newest releases.
We used the TotalMinionsKilled field, which (of course) doesn't include neutral minions :)
