### ISSUE TITLE
[ Bug ] plugin-config release v3.0.0 missing plugin.js

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#165]
**Describe the bug**
I've opened an issue on the plugin repo as well, the release does not contain the plugin.js file

**Comment by figyl** [comment]
Temporary fix is to manually roll back the module version to release v2.0.0

**Comment by Himyu** [comment]
Thanks for the feedback we fixed that with the current patch https://github.com/rcv-prod-toolkit/plugin-config/releases/tag/v3.0.1
