### ISSUE TITLE
[ Bug ] New patch or update crashed the module-league-in-game ?

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#166]
Fresh install, the "module-league-in-game" doesn't seem to work, no killfeed, level up, itemps, baron/dragon kills appears.

I get this error everytime I refresh the web source in OBS or if I refresh in the command center (localhost:3003...)

![image](https://user-images.githubusercontent.com/89284738/203665029-7909d7a0-4c63-4a97-a10a-583b0621fde1.png)

The testing page does work tho as intended, showing the testing level up, testing items, testing killfeed, etc.

![image](https://user-images.githubusercontent.com/89284738/203665701-fbc566f7-7e30-45ff-a725-8e338fc823fd.png)

**Comment by Himyu** [comment]
this is due to a bug in the plugin module and in league static, the bug in the config plugin was fixed with a new patch and the fix for the issue with static is just restarting the tool. And for it looks strange, that's most probably due to no selected or applied theme.

**Comment by FireFoXz09** [comment]
Updated the modules, same error when I go to the module-league-in-game screen.
 Oh and yeah for the looks, I know it's because I have the default theme. I always want to test new patch/builds before taking the time to add my custom theme.

After the update and restarting prod-toolkit.
![image](https://user-images.githubusercontent.com/89284738/203678516-feec13fc-df7b-44e7-8240-08b229d678df.png)

**Comment by FireFoXz09** [comment]
Wait now I doesn't do it anymore?!?!

I'll try a fresh install and reboot my PC to be sure. DON'T PANIC!

UPDATE: Everything seems to be fine. Maybe I had a bug or something but after a restart, everything works.
