### ISSUE TITLE
[ Bug ] TypeError: Cannot read property 'gameData' of undefined

### ISSUE THREAD

**Issue by RealShavy** [RCVolus/league-prod-toolkit#167]
hey i have the problem that when i load a game the scrimt keeps smearing i have already tried to change the script but it didnt work i have also downloaded and installed the latest version
![Unbenannt](https://user-images.githubusercontent.com/112900251/203786028-b8b845b6-2bfe-4490-84a2-5cf8e2c371a7.PNG)
![Bild_2022-11-24_133652820](https://user-images.githubusercontent.com/112900251/203786231-0ad4a9b2-0c30-46cb-a9b8-7282f949cc0a.png)

**Comment by Himyu** [comment]
Are you using this on a normal league server or in the tournament realm?

**Comment by RealShavy** [comment]
i'm using it on a normal League server and i will use it on a Tournament

**Comment by RealShavy** [comment]
but its buggi on both

**Comment by Himyu** [comment]
Can you make a screenshot of your observer tool especially the I'm game page to show us how it looks?

**Comment by RealShavy** [comment]
![1](https://user-images.githubusercontent.com/112900251/203789796-815970dc-70da-4177-9c93-a0397f5dfac9.PNG)
![2](https://user-images.githubusercontent.com/112900251/203789799-f294a4c0-c480-4503-85ec-ad23d867ee57.PNG)
![3](https://user-images.githubusercontent.com/112900251/203789802-52001fb8-2d24-4181-850e-6d97c92d055e.PNG)
the 3rd picture is when i'm ingame

**Comment by Himyu** [comment]
Can you please export youz game data for us like this

![image](https://user-images.githubusercontent.com/63208379/203793227-20298446-547f-4790-b921-5f2e7ea6a642.png)

so we can have a better  look at what's going on

**Comment by RealShavy** [comment]
[InGame-data.zip](https://github.com/RCVolus/league-prod-toolkit/files/10084927/InGame-data.zip)

**Comment by Himyu** [comment]
At which point does your tool crash or do you have an idea what ingame event is crashing it?

**Comment by RealShavy** [comment]
it is crashing when i load in to a game. pic and ban works .

**Comment by RealShavy** [comment]
i think it crash bc off the new obj-timer you guys did

**Comment by Himyu** [comment]
Is that happening every game when you spectate it from the beginning or just when you load into it mid-game? And is it happening when you load into the game or sometimes during it?

**Comment by RealShavy** [comment]
it happen every game even when i get a Tournament code to spectate

**Comment by Himyu** [comment]
Is this happening right when you load into the game or at some point during the game?

**Comment by RealShavy** [comment]
no it happen right when i load the game, so in the loading screen

**Comment by Himyu** [comment]
ok can you check out what's in your ```\Riot Games\League of Legends\Config\LiveEvents.ini``` that might also be a reason for it

**Comment by RealShavy** [comment]
[LiveEvents.zip](https://github.com/RCVolus/league-prod-toolkit/files/10085210/LiveEvents.zip)

**Comment by Himyu** [comment]
yea ok that's the reason why it keeps crashing on you. you just have every event in there and the toolkit can't handle that. I will do a fix for that, that only event we can handle will go through.

**Comment by Himyu** [comment]
This patch https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.4.0 should stop that from happening
