### ISSUE TITLE
[ Bug ] module-league-end-of-game total damage dealt by team is equal on both sides

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#168]
**Description**
When loading the end of game stats via LCU, the total damage dealt by the teams is perfectly equal even though the damage dealt by the players individually doesn't add up to equal amounts.

**Reproduction steps**
Create a custom game with tournament draft settings.

**Vods**
[Example 1](https://www.twitch.tv/videos/1663060384?t=4h31m40s) - Total for left team is indeed 53.6k however the total for the right team is 65.9k
[Example 2](https://www.twitch.tv/videos/1663060384?t=10h7m54s) - Total for left team is indeed 81.6k however the total for the right team is 97.4k

**System:**
- OS: Ubuntu 22.04.1 LTS
- Node: v16.16.0
- Prod Tool Version: 1.3.4
- Observer Tool Version: 3.1.5
- Streaming Software : vmix
- Browser: vmix integrated browser

**Comment by Himyu** [comment]
this issue is fixed with the newest update of the end-of-game module (https://github.com/rcv-prod-toolkit/module-league-end-of-game/releases/tag/v1.4.3)
