### ISSUE TITLE
[ Bug ] League Prod Toolkit crashes when the game ends 

### ISSUE THREAD

**Issue by Dommarsantiago** [RCVolus/league-prod-toolkit#173]
I am currently planning a small Esports broadcast and was hoping to use the toolkit for the production. For the tournament, we will be running with the spectator delay because I have not found any easy way to host a tournament in the tournament realm to eliminate the spectator delay. 

I was testing the system in some custom games and kept noticing that the software would crash as the game ended on the player's computer, thus leaving me with 3 minutes of no game data graphics or the end of-game graphics.

The main error that continues to cause it is:
Type Error: Cannot read property 'Barracks_Killed' of Null

<img width="1908" alt="Capture" src="https://user-images.githubusercontent.com/119574161/206088994-6fa843ed-6534-4e1f-b9da-9991553d897a.PNG">

I'm not sure what is causing the issue other than the lol observer application is not synced with the real-time game data because of the delay for spectators.

I'll also attach the full game run if that will help you. There are time stamps in the description so you don't have to sit through all of it.

[https://www.youtube.com/watch?v=p8mySH5BWyg]
https://www.youtube.com/watch?v=p8mySH5BWyg

Is there a way to fix this? Do I need access to the tournament realm? If so is there an easy way to access it for a tournament?

Any help you can provide would be greatly appreciated! And let me know if I can clarify anything. This is an awesome project that I would love to use for my production.

Thank you for your time.

**Comment by Dommarsantiago** [comment]
Not sure if this matters but when I do "press any key" it closes the terminal window.

**Comment by Dommarsantiago** [comment]
One more thing, these are the league observer data files.

[LOL Issue Leauge Observer files.zip](https://github.com/RCVolus/league-prod-toolkit/files/10172953/LOL.Issue.Leauge.Observer.files.zip)

**Comment by sdomi4** [comment]
It looks like there might be a few things adding up here, I'll have to try and see if I can reproduce the issue.
- The error message at the beginning of the spectator delay indicates no valid API key is set (this should hopefully no longer be necessary soon-ish)
- Same with the error message when the game ends for players
This of course absolutely shouldn't crash the toolkit – We will have a look at what causes this.

In general, the toolkit is primarily made for live server games with spectator delay. Tournament Realm has its advantages, but also disables multiple APIs we rely on for data. I would not recommend using Tournament Realm for any online tournaments. If you need access, you will need to contact Riot directly.
On the live server, only custom games created with tournament codes are available in the API for postgame stats. While there is some data available without this, we strongly recommend using tournament codes (available through tournament platforms like Battlefy / others).

**Comment by Himyu** [comment]
We tried to prevent this with the newest update to the league-state module (https://github.com/rcv-prod-toolkit/module-league-state/releases/tag/v4.9.3), which ultimately leads to now end of game data in the tournament realm because there is no data provided from an API or the client.

**Comment by Dommarsantiago** [comment]
Okay, thank you for your help with this issue. I think I have everything sorted out. I appreciate your dedication and hope to use the toolkit more in the future.
