### ISSUE TITLE
undefined Error on installation

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#196]
![Screenshot 2023-01-02 103903](https://user-images.githubusercontent.com/23660832/210214949-7461ea66-1c0c-4784-aaff-1d10c58cdbc0.png)
**Describe the bug**
Installing latest version (1.3.6 atm) crashes on installing modules (League of Legends)

**To Reproduce**
See screenshot

**Expected behavior**
Working installation

**Screenshots**

**System:**

- OS: [ubuntu]
- Prod Tool Version: [1.3.6]

**Comment by MaximilianRu** [comment]
If you're wondering whether we entered an API-Key, yes i just blacked it out, thats why it's not visible.

**Comment by Himyu** [comment]
This seems to be an issue with one of our dependencies. I will have a deeper look into it later this day.

**Comment by MaximilianRu** [comment]
Is there any update on this issue?

**Comment by Himyu** [comment]
We are currently working on the installer and there is no update arm.
We will let you know as soon as possible.

**Comment by Himyu** [comment]
we could not reproduce this issue anymore on the newest version, if you're still facing this issue please come back to us.
