### ISSUE TITLE
 Cannot read properties of undefined (reading 'elo')

### ISSUE THREAD

**Issue by Marunc1** [RCVolus/league-prod-toolkit#202]
i did manage to start it once, after i pressed the connect button in  the league observer tool, this error appeared, and now when start, i appears directly

![Screenshot_1](https://user-images.githubusercontent.com/105013306/210667522-7c5ce731-8be6-4e95-8174-b1ab087da858.png)

**Comment by Himyu** [comment]
Are you using the tools in the tournament realm and which version of the prod tool and the modules do you use?

**Comment by Marunc1** [comment]
is not in realm , and i use the latest version of the prod tool

**Comment by Marunc1** [comment]
now works for some reason, but now i have another problem, whatever i edit into the ingame.css , save it, start again the bat, but the update is not there, i tried to put a background to the level up, does not apply

**Comment by Himyu** [comment]
The changes you make are overwritten by any updates that's why we have a theming system to give the tool customer styling please refer to https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation for further information.

**Comment by Marunc1** [comment]
i am trying to move this to the left for example, but any font size i change , not applying 
![image](https://user-images.githubusercontent.com/105013306/211168265-3c90ffa6-25d3-4531-a0bd-f1bb639d6bbc.png)

**Comment by Marunc1** [comment]
![image](https://user-images.githubusercontent.com/105013306/211168355-55190832-f040-44e3-b86d-b32ae6fcf6c8.png)
or this

**Comment by sdomi4** [comment]
Any customization should be done through themes (see the link Himyu posted above to get started).
To modify objective event banners use the `event-name` and `event-time` CSS classes, for example:
```css
.event-name {
  color: #123456;
  font-size: 12px;
}
.event-time {
  color: #123456;
  font-size: 12px;
}
```

To modify power play banners, use the `pp-text` CSS class, for example:
```css
.pp-text {
  color: #BEEEEF;
  font-size: 28px;
}
```

**Comment by Marunc1** [comment]
thank you!
