### ISSUE TITLE
[ Bug ] MongoDB never shows up during installation or starting the tool

### ISSUE THREAD

**Issue by VXLTCasts** [RCVolus/league-prod-toolkit#217]
**Describe the bug**
on installing the prodkit, mongoDB installation doesn't work when starting the bat or through powershell, nor does it state it requires the user to source the software in thewiki

**To Reproduce**
1. Go to prodkit location
2. Click on start.bat

**Expected behavior**
MongoDB install popout or a notification of that limitation in the wiki

**Screenshots**
![bug](https://user-images.githubusercontent.com/123594044/214686174-f4774ea3-b866-4975-8b26-d168a67a4846.png)

**Comment by sdomi4** [comment]
mongoDB is no longer needed for the prod-toolkit (and hasn't been for a while).

**Comment by VXLTCasts** [comment]
I actually looked over the whole thing, apparently had something to do with my port configuration

Thanks for the heads up though
