### ISSUE TITLE
[ Question ] The dragon pop up not working

### ISSUE THREAD

**Issue by DrEnslaved** [RCVolus/league-prod-toolkit#220]
Before the issue: 
When I start up the program without any errors and I proceed into the in-game overlays I am provided the choice of multiple features that would show on the OBS like Level up, Item purchase, Herald kill. 
From the menu provided in [[Localhost](alhost:3000)](http://localhost:3003) I have the ability to enable those features.  
I make sure to refresh everything before using anything. I put the links in OBS and almost everything seems to work.

WHERE THE ISSUE COMES:
I select the options for the in-game tool to see an overlay when: Herald and Dragon are spawned. For some reason only the Herald appears.
There are no issues with - Level ups, Kill feed, Item purchases for now. Its only the Dragon Kill event that does not pop up even if it is selected within the localhost.

 
I am new with the program so this issue could be fully on me but I don't know how to resolve it.

**Comment by sdomi4** [comment]
Could you double-check the [LiveEvent config](https://github.com/RCVolus/league-observer-tool#setting-up-liveevents-api) and make sure all necessary events are set?
`LiveEvents.ini` should contain all of these:
```
OnKillDragon_Spectator
OnKillRiftHerald_Spectator
OnKillWorm_Spectator
OnTurretPlateDestroyed
OnDragonSoulGiven
```
