### ISSUE TITLE
Display Team Logo's in In-Game Overlay

### ISSUE THREAD

**Issue by Coow** [RCVolus/league-prod-toolkit#226]
Hi!

Is there any way to diplay the Team Logo's ingame next to their score, or as a replacement of the score?
The same also applies to the various overlays in the teams module

If it is a feature, preferably I would like to add it to the Documentation aswell.

**Comment by sdomi4** [comment]
This is currently not (trivially) possible. Adding individual elements controlled through the toolkit is planned with #162. I will close the issue here to keep it all in one place.
