### ISSUE TITLE
[ Question ] Is it possible to change the design of the WebUI?

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-prod-toolkit#227]
Hey Guys, at first AWESOME work of all contributing. I played around a little with the UI and wanted to alter the design a little. Is this possible? And if yes, what do I have to do?

Regards,
Fredo

**Comment by sdomi4** [comment]
Hi Fredo

Just to make sure we understand this correctly: You want to modify the UI of the toolkit itself? Or the way the overlays look?

**Comment by Freeedooo** [comment]
I want to change the way it looks, when I go to localhost:3003 in my Browser :) basically said. 
So yes, I want to change the ui of the toolkit itself. Overlays are perfectly clear to me.

**Comment by sdomi4** [comment]
There is no way to modify that other than modifying the source directly (keep in mind any updates will overwrite these kinds of changes).
Do you have any specific changes in mind? If it isn't anything huge we can put it into the backlog for a future version.

**Comment by Freeedooo** [comment]
I was thinking about custom colors, some custom BG image, fonts and a logo for example! Thanks for helping me. Maybe you will think about that one.
