### ISSUE TITLE
[ Question ] Working together with Lars Eble from LeagueBroadcast

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-prod-toolkit#229]
Hey Guys, 
did you think about working together Lars Ebles LeagueBroadcast code in your production toolkit. I texted him about that idea and he would highly appreciate if you reach out to him. His tool is memory reading so he gets the gold etc. Maybe you´ll have a look in his work [floh22/LeagueBroadcast](https://github.com/floh22/LeagueBroadcast)

His main features which are better than yours are:
- Live Gold (with Baron/Drake Powerplay)
- Custom Scoreboard
- Level per Player stats like in LEC
and so on.

Your control GUI is just better then his. Maybe this would be the league breoadcasting coorperation of the century :D

Regards,
Fredo

**Comment by sdomi4** [comment]
No promises but we'll look into it :)
