### ISSUE TITLE
Can't lunch league-toolkit since 13.3 patch

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#230]
**Describe the bug**
Impossible to launch the toolkit. Longs errors codes appears everywhere since 13.3 patch. (maybe not related but maybe worth to check out if it's related or because of a module update)

**To Reproduce**

1. Double click on start.bat
2. Observe the leading
3. Profit from the bugs
4. Close and try again

I tried deleting everything, fresh install, reboot, install on another drive, etc. Same problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/89284738/218493758-bf99d881-2349-4694-b1fa-2840fd4f97d7.png)
![image](https://user-images.githubusercontent.com/89284738/218494373-3bc009db-de49-430b-9ca2-5633ec3533f3.png)
![image](https://user-images.githubusercontent.com/89284738/218494451-33f39490-a961-4c86-9fd9-c110d3111c82.png)
![image](https://user-images.githubusercontent.com/89284738/218494534-ba300318-fd16-40dc-9b70-5eb2ecc36a1c.png)
![image](https://user-images.githubusercontent.com/89284738/218494697-646f33dd-2dbf-4544-8f45-969a620d0168.png)
![image](https://user-images.githubusercontent.com/89284738/218494785-0dc745c5-974d-4c75-88d3-38ca6f6dcf85.png)
![image](https://user-images.githubusercontent.com/89284738/218494894-4f10be86-3bf2-4d3d-81bc-6abaced2ec8e.png)
![image](https://user-images.githubusercontent.com/89284738/218495296-eaed91ba-c063-465a-bb1d-b7e187ebff3f.png)

**System:**

- OS: Windows 10
- Prod Tool Version: 1.3.7

**Comment by sdomi4** [comment]
This is due to the certificate expiring on Riots side :(
https://github.com/RiotGames/developer-relations/issues/591 might be updated once its fixed.
