### ISSUE TITLE
[ Question ] Install fails with missing modules

### ISSUE THREAD

**Issue by baigojahanzaib** [RCVolus/league-prod-toolkit#235]
i keep getting these errors

![image](https://user-images.githubusercontent.com/42896984/219400760-d268abba-fc84-4d3d-b22a-20458190176c.png)

![image](https://user-images.githubusercontent.com/42896984/219400961-ef6a7777-2e69-415d-9907-9e84833cfc8d.png)

i dont even get chance to add my api and stuff skips that

**Comment by Himyu** [comment]
You are using node. version 19, but we recommend node 16 in our wiki, please consider downgrading it since newer versions of node break the code.

**Comment by baigojahanzaib** [comment]
Still having the same errors

**Comment by Himyu** [comment]
Wich node version are you using now?

**Comment by baigojahanzaib** [comment]
16.7 as per the wiki

**Comment by baigojahanzaib** [comment]
![image](https://user-images.githubusercontent.com/42896984/219411511-e4bc4548-05e5-4216-a75d-04f8fb811c59.png)

**Comment by sdomi4** [comment]
Could you post the error messages you see after downgrading to 16.7?

**Comment by baigojahanzaib** [comment]
![image](https://user-images.githubusercontent.com/42896984/219426973-c85722d3-4019-45bd-9253-d5f5a1e68cf7.png)
![image](https://user-images.githubusercontent.com/42896984/219427043-ceea58d3-88d9-40de-a93b-52fc33ccf121.png)

**Comment by sdomi4** [comment]
It looks like some files are missing. Is it possible you downloaded the source code instead of a [release](https://github.com/RCVolus/league-prod-toolkit/releases) ?

**Comment by baigojahanzaib** [comment]
Still same issue, Can someone hop into a dc call and help me?

Jazy#9710

**Comment by sdomi4** [comment]
We do not provide support through discord, sorry.
I am unable to reproduce the issue on a fresh install.
I can however reproduce the exact error message by downloading the source code and running the installer there. Please double-check if you have downloaded the release containing the necessary files and not the source code.
If you are unsure what you have downloaded, post a screenshot of the toolkit directory contents :)

**Comment by baigojahanzaib** [comment]
![image](https://user-images.githubusercontent.com/42896984/219645234-2026a45f-a20a-414c-bc9d-de49b2ddc163.png)
this is what is in the file

**Comment by sdomi4** [comment]
This looks like the source code; not the release which is ready to run. Please download the [latest release](https://github.com/RCVolus/league-prod-toolkit/releases/tag/v1.3.7) and follow the installation instructions.

**Comment by GizmoSup** [comment]
I had the same issue for ages
Turns out I downloaded a clone of the repository instead of the download.
Click to download the latest version of the program not the repository
https://github.com/RCVolus/league-prod-toolkit/releases/tag/v1.3.7
