### ISSUE TITLE
[ Champion icons not loading ]

### ISSUE THREAD

**Issue by Dantecamo** [RCVolus/league-prod-toolkit#240]
**Describe the bug**
When champion icons should be previewed in champion select and in kill feed etc, we see a blank icon appears instead.

**Screenshots**
[https://ibb.co/xzDdBWf](url)
[https://ibb.co/dLFpYZ5](url)

**System:**

- OS: [Windows]
- Node: [16.7]
- Prod Tool Version: [1.3.7]
- Observer Tool Version: [4.0.0]
- Streaming Software & Version: (OBS)
- Browser: [chrome]

**Additional context**
I am new

**Comment by sdomi4** [comment]
Do you see any errors in the toolkit console? This probably is down to an issue with the download of static data.

**Comment by Dantecamo** [comment]
Nope, no error messages in the command prompt

**Comment by sdomi4** [comment]
Do you see the champion images in `\league-prod-toolkit\modules\module-league-static\frontend\img\champion`?

**Comment by Dantecamo** [comment]
Yes I see them

**Comment by sdomi4** [comment]
Do you see any errors when opening the developer console (F12) when opening the overlays directly in the browser?

**Comment by Dantecamo** [comment]
Yet again nothing

**Comment by sdomi4** [comment]
The toolkit not loading images and showing no errors / messages anywhere should be more or less impossible.
Please follow these steps:
1. Stop the toolkit
2. Redownload static data by clearing the last downloaded version in `league-prod-toolkit\modules\plugin-config\config.json` by setting `"last-downloaded-version": ""` in `module-league-static`
3. Restart the toolkit once the download is completed
4. If the issue persists:
- Copy the full output of the toolkit so we can take a look
- Take a screenshot of the full dev tools for affected overlays

**Comment by pintosobs** [comment]
I do everything that you said, and i took this error.

![image](https://user-images.githubusercontent.com/69796025/222934324-85a557f0-23da-4ee0-8e67-768ef06b01ba.png)

**Comment by sdomi4** [comment]
> I do everything that you said, and i took this error.

It looks like you are running node 18.14. – the toolkit is built and tested on node 16.7. Please try reinstalling with the intended node version.

**Comment by pintosobs** [comment]
still same
![image](https://user-images.githubusercontent.com/69796025/222979519-23ba6a99-5f05-4efb-a1d9-771b29d62af9.png)

**Comment by sdomi4** [comment]
Which address is noted in the error message? The IP of the toolkit?

**Comment by pintosobs** [comment]
I think it is my computer's ip

**Comment by sdomi4** [comment]
We are unable to reproduce this issue. Could you provide some more information?

- OS 
- Node Version
- Prod Tool Version
- Install Path
- Does the issue also occur with authentication disabled?
