### ISSUE TITLE
Error while starting start.bat

### ISSUE THREAD

**Issue by ItayKisous** [RCVolus/league-prod-toolkit#242]
While opening up Start.bat file im hitting this error after "finish downloading centered images"

```
undefined:1
<html>
^

SyntaxError: C:\Users\itay6\Downloads\prod-toolkit\modules\module-league-static\frontend\data\item.bin.json: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
```

**Comment by Himyu** [comment]
There will be a patch for the league static module to address this issue in a few minutes after installing that it would work fine again
