### ISSUE TITLE
Bug or missing feature on the new scoreboard

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#249]
Elder Dragon Powerplay doesn't show on the new scoreboard (Baron does). I don,t know if this is intented as we had a powerplay timer for both on the old system.

Also, for BO5 and higher, is it normal that the team with 2 wins have only the middle dot highlighted (see screenshot for the red team)

![image](https://user-images.githubusercontent.com/89284738/222036694-bdaf9417-43bc-4084-bc12-170083c7d208.png)

**Comment by shinilee** [comment]
for that scoreboard background. is that code edit? or just apply background img on obs? sorry for the random question.

**Comment by FireFoXz09** [comment]
> 

You just need to edit/load your own theme. It's the basic design, I just changed the colors in the theme (they added a new line for a new color, go check the default theme folder)

**Comment by sdomi4** [comment]
Elder powerplay is currently disabled, as we have no way of displaying both baron + elder buff. We're having a think on how to show both buffs at once (if you have a good idea let us know).

The bo5 score is a bug, we'll take a look at it.

**Comment by FireFoXz09** [comment]
Well not sure how to show both of them at the same time in an efficient way, but you could still display the first PP and if a second one comes for the same team, you show it after the first one is done? (if it's one for the blue team and one for the red team, no problem for the display I guess)

For example, Red team slay the Baron Nashor, so the power play HUD goes on and show the gold diff and timer for the baron. One minute later, the Red Team also kill the Elder Dragon. You keep the Baron Power Play on display, but when it ends and close, you show the Elder Power Play with the time remaining and gold diff (since it's still calculated I suppose, just not displayed).

To be sure that there's no bug on the displays, or to know if a power play is done, we could check if a team is in Power play mode, if yes, don,t display the new PP info. If no, then display the PP informations (elder or baron, timer, gold, etc).

...or something like that? I'm just throwing an idea haha!

**Comment by JoanJuan10** [comment]
Maybe to show both of them at the same time, you could split the zone where it is shown in half horizontally. For example when both are slayed, on the upper half it shows the Baron power play and on the bottom half it shows the Elder Dragon.

**Comment by Freeedooo** [comment]
The most efficient way in my opinion is to show Baron power play in the upper right corner and the dragon PP in the upper left.

Just like the neutral timers in the standard hud

**Comment by Himyu** [comment]
> The most efficient way in my opinion is to show Baron power play in the upper right corner and the dragon PP in the upper left. Just like the neutral timers in the standard hud

We had done this before but noticed that it was sometimes hard to tell who has the baron/elder that why we wanted to integrate it into the scoreboard.

**Comment by MDvorky** [comment]
Maybe you can do it as it is done in Ice Hockey. You let the first end and then with the rest of the time will pop up elder timer or vice versa.

**Comment by benholness** [comment]
Having the glow behind player borders is one way of achieving this (purple for baron and light blue for elder), however it could be even a case of saying something as simple as having their team tag (see the screenshot I've attached were you can see EDG have their tag for the baron buff). It's simple and conveys the info needed to the viewer well 👍

I agree with @Freeedooo, having them on opposite sides at the top is a good solution and it is a common way this is shown on multiple professional broadcasts. The glow behind player icons and/or team tag is an additional visual cue to let viewers know who the buff.

<img width="1920" alt="1 - Copy" src="https://github.com/RCVolus/league-prod-toolkit/assets/28854222/a8c93799-5301-4959-9102-3473bf1c329b">

**Comment by Himyu** [comment]
Dragon Power play was added again with one of the last updates to the in-game module, and the score issue was also fixed.
