### ISSUE TITLE
provider-webapi failed

### ISSUE THREAD

**Issue by OrionCodeDev** [RCVolus/league-prod-toolkit#25]
Hey, one plugin not working. What's can be wrong?
```
2021-09-24T12:42:09.412Z [info ] plugin-provider-webapi: Fetching livegame data for summoner=Joep
2021-09-24T12:42:09.412Z [error] plugin-provider-webapi: Failed to get information for summoner=Joep. Maybe this summoner does not exist? error=TypeError: Cannot read property 'Summoner' of undefined
2021-09-24T12:42:09.418Z [info ] plugin-state-league: Loading livegame failed for summoner=Joep
2021-09-24T12:44:35.883Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-09-24T12:44:35.884Z [error] plugin-league-end-of-game: Uncaught error in league-end-of-game: request timed out
```
Best Regards

**Comment by Himyu** [comment]
That might be related to Riot changing Match-API v4 to v5 and we will fix this in an upcoming update

**Comment by Laraakaa** [comment]
Hey, was the summoner really ingame, and did you set up the correct riot games API key in the config?

Thank you in advance for assisting us in troubleshooting this issue!

**Comment by ManuelHenao** [comment]
get this same problem. summonner is ingame. this works with any server? NA-EU-LAN-ETC?

**Comment by Himyu** [comment]
At the moment we only support EUW

**Comment by Himyu** [comment]
Closing this issue since we now also support other regions see [here](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation#install-prod-toolkit)

**Comment by Himyu** [comment]
Closing this issue since we now also support other regions see [here](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation#install-prod-toolkit)

**Comment by ManuelHenao** [comment]
Tested with ther change of region. AMERICAS LA1 and show this (User is in game)

![lol prod toolkit error 4](https://user-images.githubusercontent.com/64715702/142780140-24d9158c-8bcc-4602-806d-5f0cadcb1274.png)

**Comment by Himyu** [comment]
I will have another look at that

**Comment by Himyu** [comment]
you are right. it should be fixed now. Please Try again :)

**Comment by ManuelHenao** [comment]
need to download again? or it updates?

**Comment by Himyu** [comment]
you need to download it again

**Comment by ManuelHenao** [comment]
Try with AMERICAS, americas, LA1, la1, LAN, lan and i got this error. is different.

![lol prod toolkit error 5](https://user-images.githubusercontent.com/64715702/142782193-227b6294-cbdb-4603-902b-d62a8a0ff23f.png)

**Comment by Himyu** [comment]
Did you provide a valid API key? since this error comes from The Riot-API and is thrown when you don't provide a API Key or the key is invalid

**Comment by ManuelHenao** [comment]
opps. was my bad. now worked. thanks

**Comment by Himyu** [comment]
You are welcome :) Thank you for the feedback

**Comment by ManuelHenao** [comment]
Again me haha. it worked fine in game state module when i search for a player on ranked qeue. but now i have a 5v5 custom game. Championselect worked fine but later i got this error.

![lol prod toolkit error 6](https://user-images.githubusercontent.com/64715702/142785500-fae79318-b56b-426d-b515-a5667fd79a7b.png)

**Comment by ManuelHenao** [comment]
And if i try to search any user of this game, it doesnt appears in game. maybe it doesnt works on customs games? so what i need to do a tournament with this hehe

**Comment by ManuelHenao** [comment]
Ok, my bad again. the custom game need to be on all spectators.
