### ISSUE TITLE
[ Bug ] Baron and Dragon events do not work.

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#250]
**Describe the bug**
Using the new version with the new overlay. Herald event seems to pop up when defeated but dragons and barons do not work.

EDIT: Now that I see it. The dragon elemental icon below the team side at the scoreboard does not appear either.
EDIT 2: This was already reported on the #244 

**To Reproduce**
Using a replay of a recent game and testing it.

**Expected behavior**
Baron event when defeated and baron timer appear, but do not.

**Screenshots**
What happens (Dragon):

https://user-images.githubusercontent.com/37046841/222120823-6adbd445-22c7-423b-b40b-8d008ce9f36c.mp4

What happens (Baron):

https://user-images.githubusercontent.com/37046841/222122132-e2bd4b9c-cc2b-4239-b3b0-75c10af0d68d.mp4

Config:
![brrgC5h](https://user-images.githubusercontent.com/37046841/222121096-c228e007-d546-4baa-8820-6e6052d1a1f0.png)

**System:**

- OS: Windows 10
- Node: 8.13.2
- Prod Tool Version: 1.4.1
- Observer Tool Version: 5.0.0
- Streaming Software & Version: OBS
- Browser: Chrome

**Comment by FireFoXz09** [comment]
For the dragon icon under the team, you must leave the default in-game scoreboard on and edit your theme to add a color background to your new scoreboard, so your scoreboard ovverlay hide the in-game scoreboard, but still show the dragons icons...

Althought I would love to have the custom scoreboard magane dragons slains, so we can create custom icons for them (or custom placement and totally hide the in-game scoreboard)

For the pop-up dragon/herald/baron slain, I had no issue on my side yesterday while testing it... I'll double check to be sure, maybe yuo need to load a theme for it to work? Be sure you loaded the default theme (or your own)

**Comment by JoanJuan10** [comment]
In the example I am using a custom theme with only the default options in the .json (the ones the documentation specifically tell you). I have made no other edits to it.

What is weird is that the Herald popup works but do not for the dragons or baron.

**Comment by sdomi4** [comment]
Objective Events still rely on the LiveEvent API. Could you double check your configuration matches the required events listed in the [observer tool readme](https://github.com/RCVolus/league-observer-tool#readme)?

**Comment by JoanJuan10** [comment]
Oh. I guess I forgot the step about registering the events in the .ini.

The only remaining problem I have is #249 but I am closing my issue. Thank you.
