### ISSUE TITLE
[ Bug ] Text wrapping in scoreboard when it shouldn't

### ISSUE THREAD

**Issue by shir0xyz** [RCVolus/league-prod-toolkit#251]
As you can see the gold text is wrapped.

![image](https://user-images.githubusercontent.com/48430352/222297324-86ac91c9-4e72-494c-8aae-ac0fc14064c4.png)

**Comment by FireFoXz09** [comment]
For now, you can use a smaller font OR ajust the font size in the ingame.css file of the in-game module. (or a better option on long term, modify it with your theme files) But yes It would be nice if on both side the spacing was the same, so we don't have a wrap ;)

**Comment by shir0xyz** [comment]
I tried playing with font size but it didn't make any change at all

**Comment by shir0xyz** [comment]
Getting rid of padding of sb-stat seems to be fixing this issue

**Comment by sdomi4** [comment]
We already noted this internally, should hopefully be fixed with the next update :)

**Comment by Coow** [comment]
@sdomi4 This bug/behaviour should also be expanded to the End of Game Damage Graph, where the highest damage players Damage Text, is also wrapped around like the Scoreboard

**Comment by TRristan** [comment]
![image](https://github.com/RCVolus/league-prod-toolkit/assets/116945812/a34fdc9e-d1b1-47de-9c94-81001b7f7e8f)
There is a similar bug with the title and the time of the inhibitors

**Comment by Himyu** [comment]
This issue where fixed with the newest update to the ingame module v5.3.0
