### ISSUE TITLE
Does it support TW (TW2) servers?

### ISSUE THREAD

**Issue by syuanlyu** [RCVolus/league-prod-toolkit#258]
Does it support TW (TW2) servers?
I can't find my servers when i getting install.

**Comment by sdomi4** [comment]
Yes, it should – we just haven't updated the installer to accommodate for the new-ish servers in asia.
You can manually set TW2 by selecting any region with the installer and then changing the `server` value in `...\prod-toolkit\modules\plugin-config\config.json` to "TW2"

**Comment by syuanlyu** [comment]
THANKS!
