### ISSUE TITLE
The In-Game Information won't update every second

### ISSUE THREAD

**Issue by syuanlyu** [RCVolus/league-prod-toolkit#260]
I have successful capture the In-Game Information, but  it won't update the information every second.
It only change when i reload the website.

**Comment by sdomi4** [comment]
Could you give us some info on versions/programs involved?

- OS
- Node Version
- Prod Tool Version
- Observer Tool Version
- Streaming Software & Version
- Browser

**Comment by syuanlyu** [comment]
OS: Windows 10
Node: 16.14.0
Prod Tool Version: 1.4.1
Observer Tool Version: 5.0.0
Streaming Software & Version: OBS 28.1.2
Browser: Chrome

**Comment by syuanlyu** [comment]
The Item Display and Level Display both  successfully appear through the game, but the Scoreboard still won't update through the game.
And the dragon icon below the Scoreboard won't appear too.

**Comment by sdomi4** [comment]
Do you see the same behaviour in Chrome and the OBS browser source?
Are there any errors in the dev console in Chrome (F12)?

**Comment by RealShavy** [comment]
i have the same issue with the scoreboard ,

OS: Windows 10
Node: 16.15.0
Prod Tool Version: 1.4.1
Observer Tool Version: 5.0.0
Streaming Software & Version: vMix 26.0.0.40
Browser: OperaGX/Chrome

**Comment by syuanlyu** [comment]
Yes I see the same behaviour in Chrome and the OBS browser source.
Yes there are some errors in the dev console in Chrome.

![image](https://user-images.githubusercontent.com/107873438/224209022-387ea56c-cf51-4334-80ba-a8cf695d470f.png)

**Comment by Himyu** [comment]
This happens when you do not set up teams in the team's module, you can fix that by setting teams in the module-teams then the issue should go away.

**Comment by syuanlyu** [comment]
The errors in the dev console in Chrome were gone away.
But the Scoreboard still won't update through the game every second.
It only updates when i refresh the website.

**Comment by syuanlyu** [comment]
Is there anything wrong when i observing the game?
![image](https://user-images.githubusercontent.com/107873438/224639718-704e4e4c-f18c-4398-8628-9d49bf674f8a.png)

![image](https://user-images.githubusercontent.com/107873438/224639802-8182c12f-a092-4bc4-8232-e22ba815207c.png)

![image](https://user-images.githubusercontent.com/107873438/224639333-d98ed016-b69d-4e6b-aa9d-d28547ca4adc.png)

**Comment by sdomi4** [comment]
I am able to reproduce this when Farsight isn't synced in the observer tool. Could you confirm Farsight is active in the observer tool and check if the issue still is present?
Farsight is required for the custom scoreboard as some data is only available through memory reading.

**Comment by syuanlyu** [comment]
The problem is solved when  the Farsight is active.
But the dragon icon below the Scoreboard still won't appear.

**Comment by FireFoXz09** [comment]
_But the dragon icon below the Scoreboard still won't appear_

As far as I know, there is no Dragon Icon below the Scoreboard. You use the icons from the in-game/spectator HUD. (The RCVolus scoreboard goes OVER the in-game/spectator HUD scoreboard, but you must leave a space to show the dragons)

Like in this example:
![image](https://user-images.githubusercontent.com/89284738/225019620-70b0d651-6ffe-4414-a399-a634c6873c28.png)

**Comment by syuanlyu** [comment]
Thanks all for your patience and help.
My problem  is solved.
