### ISSUE TITLE
can someone help me [ Question ]

### ISSUE THREAD

**Issue by overkido** [RCVolus/league-prod-toolkit#261]
can someone help me, does anyone know how to remove the team and put the time running on top in the team color as in the msi, and put the bans on top?

and put the team's acronym in the middle as it is in the image?

![image](https://user-images.githubusercontent.com/89580284/223744949-3b5f8923-5bc4-4293-bd38-4f5708d05310.png)
![image](https://user-images.githubusercontent.com/89580284/223745291-ea836b89-dd96-45fb-9402-3f5653585353.png)

**Comment by sdomi4** [comment]
Modifying the champ select module is non-trivial, as its code is based on an older project. To achieve the desired modifications, your best bet is probably building the module from the ground up on top of LPTE data.
You can check out the source code for the default UI for reference: https://github.com/rcv-prod-toolkit/module-league-champselect-ui/tree/main
