### ISSUE TITLE
[ Feature ] Add Support Singapour [SG2]

### ISSUE THREAD

**Issue by RedOver4** [RCVolus/league-prod-toolkit#262]
Good morning

Is it possible to add support on Singapore servers?

(sorry my english is bad)

**Comment by sdomi4** [comment]
The newer servers in asia should all work (not that we can test it, but nothing speaks against it), but aren't added to the installer yet.
You can set any region in the installer and then change the configration to your server in `...\prod-toolkit\modules\plugin-config\config.json` by updating the `server` value.

**Comment by RedOver4** [comment]
Alright, thanks, I'll try that and report back if it works.

**Comment by Himyu** [comment]
With the newest update to the plugin-webapi and the prod-tool itself, we added the new OCE servers to the setup.
