### ISSUE TITLE
[ Question ] Any way to swap around the sides of nametags?

### ISSUE THREAD

**Issue by MordredXYZ** [RCVolus/league-prod-toolkit#272]
Currently testing out the tools, and I'm spectating a live game, but I've run into a consistent problem: I've got absolutely ZERO way to reverse the sides of the nameplates in the in-game UI.

In the Game State panel of the prod toolkit, it's telling me I've not setup a game, even though if I load the game by a Summoner Name who is in it, and I can see the console telling me I've loaded the game, I can't edit nametags or what side they're on.

This is a huge problem, is there any way to resolve this?

**Comment by MordredXYZ** [comment]
Just also noting that if I move the champions around on the scoreboard, the UI updates correctly, and then resets to the wrong names again immediately.

**Comment by sdomi4** [comment]
Is this happening with a game you are spectating (a replay or live through the friendslist) or a custom game where you are in the lobby, see champ select and then the game?

Which modules do you have synced in the observer tool while spectating? (specifically, is Farsight enabled?)

**Comment by MordredXYZ** [comment]
It happens with a live game I'm spectating, or with a replay where I myself were in the game as well. I can just hide the nicknames, but that then removes the styling options we get :(

I have all of the modules synced on the Observer Tool, and Farsight is enabled yes, otherwise my in-game UI doesn't update at all.

If there's any other info I can provide to assist, please let me know!

**Comment by sdomi4** [comment]
Do the nametags also jump back into position when changing the scoreboard without Farsight enabled? (I know this means the scoreboard doesn't work but bear with me...)

It's worth noting the nicknames are meant to be set during the lobby before the game starts, the feature was never intended for replays/live games.

**Comment by MordredXYZ** [comment]
![prod_toolkit_wrongside2](https://user-images.githubusercontent.com/99334199/226533735-1f353300-b35c-4b6f-9ae6-ec8401eeb0d6.png)
![prod_toolkit_wrongside](https://user-images.githubusercontent.com/99334199/226533745-1a4a92b2-1b2a-4d99-a5cd-b103c3aacbc4.png)

**Comment by MordredXYZ** [comment]
I've got these screenshots from an initial test run I did last week, showing what I see on both views, with every Sync enabled and Farsight running. This is in a game I was present in for champ select and everything, but had to rejoin after.

At this point I've just ditched the nicknames feature as it's never worked as intended with sides.

**Comment by sdomi4** [comment]
After some testing, this is an issue with Farsight conflicting with the ingame API.
Nicknames work as expected when Farsight is not enabled.

**Comment by MordredXYZ** [comment]
Ah, so Farsight is in the back of the bar having a fistfight with the API, essentially?

I'm glad I could uncover a bug at least, thank you for looking into it!

**Comment by Himyu** [comment]
This problem should be fixed with some of the newer versions of the prod tool and the ingame module
