### ISSUE TITLE
Twitch guesses / poll how to configure? [ Question ]

### ISSUE THREAD

**Issue by overkido** [RCVolus/league-prod-toolkit#275]
twitch guesses / poll how to configure?

I tried to configure mine here but it doesn't take the link authentication or save the id.

**Comment by FireFoXz09** [comment]
The wiki section explain it step by step... I have no issues with this plugin (have you used it before and now it doesn't work?)

https://github.com/RCVolus/league-prod-toolkit/wiki/2.-Using-Prod-Toolkit

**Comment by overkido** [comment]
> A seção wiki explica passo a passo ... Não tenho problemas com este plugin (você já o usou antes e agora não funciona?)

. I haven't used it yet because I'm not getting access and authorization from the Twitch app, I did the step by step but it didn't work

**Comment by sdomi4** [comment]
At which step are you encountering issues?
Note that not all Twitch accounts have access to polls, IIRC you need to be at least affiliate.

**Comment by overkido** [comment]
> Em qual etapa você está encontrando problemas? Observe que nem todas as contas do Twitch têm acesso às enquetes, IIRC você precisa ser pelo menos afiliado.

I haven't used it yet because I'm not getting access and authorization from the Twitch app, I did the step by step but it didn't work, I'm going to use another account to try again.

**Comment by FireFoXz09** [comment]
Maybe provide screenshots of what happen, or a video, to better see how you do the steps. I also had problem in the past but it was because of me, I was skipping a step in the tutorial provided in the wiki.

But yes you must be a Twitch Affiliate at least to use this option.

**Comment by overkido** [comment]
> Maybe provide screenshots of what happen, or a video, to better see how you do the steps. I also had problem in the past but it was because of me, I was skipping a step in the tutorial provided in the wiki.
> 
> But yes you must be a Twitch Affiliate at least to use this option.

![image](https://user-images.githubusercontent.com/89580284/226068372-f1f6200e-ec7c-44ce-9409-b5e87b964437.png)

**Comment by overkido** [comment]
I put it exactly as it is in the usage mode written there, but it's not working here, the authentication box doesn't tick I click on the purple twitch box it redirects and everything but when I check the box and save it doesn't tick, I used 2 different accounts and I don't work. @FireFoXz09 @sdomi4

**Comment by FireFoXz09** [comment]
The check box doesn't do anything for now. It's a feature not yet implemented to automate the prediction when the game start or the draft start, depending of the dev. Don't click it.

For now, You need to manually start the prediction by clicking START PREDICTION. You also need to have two teams entered in your Team panel. Also, make sure both team names are less than 25 characters, since Twitch cannont make preduction with an option having more than 25 letters.

What happen when you click Start Prediction? Any error on the webpage?

**Comment by overkido** [comment]
> What happen when you click Start Prediction? Any error on the webpage?

it just doesn't show, I have transmission today I'm going to sit down and take a print to show it here

**Comment by overkido** [comment]
> What happen when you click Start Prediction? Any error on the webpage?

![image](https://user-images.githubusercontent.com/89580284/226465434-0fa406dc-b9b2-4c05-ad67-e3d4a276cb4b.png)

**Comment by sdomi4** [comment]
Are you trying to create the prediction for the same Twitch channel you set up the Twitch App / Authorization with?

**Comment by overkido** [comment]
> Are you trying to create the prediction for the same Twitch channel you set up the Twitch App / Authorization with?

yes it's the same twitch channel it doesn't create the guess

**Comment by sdomi4** [comment]
Could you double-check this and/or reset the Twitch app? The error messages you receive indicate a mismatch between the Twitch app and the configuration in the toolkit.

**Comment by 238SAMIxD** [comment]
Hey @overkido!
I implemented predictions by using Twitch poll, try updating the app and use the new feature!
