### ISSUE TITLE
[ Question ] Custom scoreboard ?

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#276]
Please i have this background - 
![score_background](https://user-images.githubusercontent.com/104410235/225807447-87397077-32c4-4a25-b777-3545b270b095.png)
 and i would love to have this default scoreboard changed to this - can someone please help me?

**Comment by sdomi4** [comment]
The quick and dirty way to do this would be setting the image as a background and adjusting the scoreboard to fit.
Check out #264, it has the necessary theming changes to set a background image for the scoreboard.

Alternatively, you can also do this by [creating a theme](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation) and using CSS to replicate your background.
The steps would roughly be:
- Change Team colors in the global variables
- Change the color gradient by changing the `.sb-team.sb-red`/`.sb-team.sb-blue` `background` parameters
- Add box-shadows to the necessary scoreboard elements for glow/shadow effects
For reference, the default CSS for the scoreboard is [here](https://github.com/rcv-prod-toolkit/module-league-in-game/blob/567041950773225214ccd6493ac9eef491b48741/frontend/gfx/ingame.css#L631).

**Comment by MDvorky** [comment]
Would it be possible to add logos to the scoreboard? For example - like they have in LCK - we found out the way to put name and score below - but we don't know where we should start with this feature - can you please somehow help ? :D 
![obrázok_2023-03-18_052644493](https://user-images.githubusercontent.com/104410235/226084658-02cec7e2-7fe2-46f3-b924-11cc5ea828bd.png)

**Comment by JoanJuan10** [comment]
> Would it be possible to add logos to the scoreboard? For example - like they have in LCK - we found out the way to put name and score below - but we don't know where we should start with this feature - can you please somehow help ? :D ![obrázok_2023-03-18_052644493](https://user-images.githubusercontent.com/104410235/226084658-02cec7e2-7fe2-46f3-b924-11cc5ea828bd.png)

This has been already requested in #226
