### ISSUE TITLE
[ Feature ] Test Data for Theme Designing

### ISSUE THREAD

**Issue by MordredXYZ** [RCVolus/league-prod-toolkit#286]
Heyo!

Just a query, I see there's #82 however it links to another issue that links back to it and both are closed with no resolution nor indication of anything actually being implemented? I can't find anything in the github either.

Is there a way of generating test data so that I can continue working on a custom theme? Ideally champ select, in-game for events, and most importantly post-game, as downloaded replay files aren't working for end of game for me.

Thanks!

**Comment by MordredXYZ** [comment]
Nevermind I see the in-game events tests, which are GREAT! (Somehow forgot about those?)

However I'd still love to test post-game stats and champ select if possible!

**Comment by sdomi4** [comment]
For testing champ select, you can either just open a custom lobby as a player or use the draft recording feature.
For postgame data, the intended way is using matchv5 data, not the LCU (this is meant as a fallback in case matchv5 doesn't work and doesn't give complete information).
To test, just set a match ID in game state using `set by match id` (example match ID: 5903856888)

**Comment by MordredXYZ** [comment]
Awesome, I'm getting results now from a game I was in earlier, but one thing that's peculiar: I can get a gold graph in the All in One view, but absolutely _nothing_ in the Gold graph view.

**Comment by sdomi4** [comment]
This is a bug; set up teams in the teams module and it works

**Comment by MordredXYZ** [comment]
Luckily there's enough to go by with the All in One view to get an idea of it, I think that's all the questions I had with test data, thank you for your brilliant work!
