### ISSUE TITLE
[ Question ] Timer on scoreboard does not counting time

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#288]
I upload the scoreboard, did everything but after the match started kills and golds were counted. But time was not counting or uploading, i needed to refresh the picture - can you please somehow help me?

**Comment by sdomi4** [comment]
A new league patch dropped today, memory offsets are not yet updated. An update should be available shortly.

**Comment by MDvorky** [comment]
For how long should i wait? Should I do it manually?

**Comment by MDvorky** [comment]
and does it evolve also dragons and barons? Because i tried it today but dragons and barons did not pop up :( but heralds did

**Comment by sdomi4** [comment]
At the moment, offsets can't be updated/set manually (see RCVolus/league-observer-tool#22). I will take a look and update offsets tonight.

Dragons/Barons don't necessarily rely on Farsight. Double-check your LiveEvents configuration and see if all events are configured as listed in the observer tool readme.

**Comment by MDvorky** [comment]
Where should I check it or where can i found it? In the readme of League Observer Tool or you mean this? 
![image](https://user-images.githubusercontent.com/104410235/227003044-ea0781ea-1acc-488d-8119-9a0aeb38733b.png)

**Comment by MDvorky** [comment]
But i wonder if herald working why baron and dragons not working. Plus is there any possibility to set up inhib pop up when inhib destroys or it also involve live event to be turn on?

**Comment by sdomi4** [comment]
- Only Herald events showing up often happens when LiveEvents arent set up properly. The necessary settings are listed in the [observer tool readme](https://github.com/RCVolus/league-observer-tool#readme).
- This should be doable, but no promises on when it will happen

**Comment by MDvorky** [comment]
I tried to update the port on the League but now not even connect wit Observer Tool

**Comment by sdomi4** [comment]
I'm not sure which port you updated – the configuration for LiveEvents needs to match in the observer tool and `game.cfg`.

**Comment by MDvorky** [comment]
Okay, so i did check everything - port is matching, everything is running until i run the game but time is not moving or counting at all

**Comment by sdomi4** [comment]
Does the time update when refreshing the page? Are gold values for the teams updating?
Is Farsight enabled?

**Comment by MDvorky** [comment]
I turned the Farsight on in the League Observer Tool and it suddenly started to work - did you update the Farsight?

**Comment by sdomi4** [comment]
Yes, memory offsets for Farsight were updated last night. The scoreboard is driven entirely by memory reading, so Farsight needs to be enabled for it to work properly.

**Comment by MDvorky** [comment]
And when the timer will stop working i know that farsight needs to be updated?

**Comment by sdomi4** [comment]
Farsight needs to be updated with every League patch, so about every two weeks. Updates should usually arrive within a day or two of the patch being released.

**Comment by MDvorky** [comment]
Thank a lot :)
