### ISSUE TITLE
[ Bug ] Killfeed - Rift Herald icon missing when destroying structures

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#290]
**Describe the bug**
When Shelly destroys a structure her icon is missing from the killfeed.

[Clip](https://clips.twitch.tv/FurtiveHomelyBeefUWot-bI8DRjjWLPoGhShj)

- OS: Ubuntu Server 22.04 LTS
- Node: v16.16.0
- Prod Tool Version: 1.5.1
- Observer Tool Version: 5.0.0
- Streaming Software & Version: OBS Studio 29.0.2

**Comment by Himyu** [comment]
With the newest patch (4.0.5), we added a Herold icon to tower and inhibitor kills.
