### ISSUE TITLE
[ Bug ] Baron Powerplay never shows up on ingame overlay.

### ISSUE THREAD

**Issue by Jadiac5** [RCVolus/league-prod-toolkit#292]
Baron Powerplay doesn't show up when baron is slain, even tho I enabled the option in the Ingame module.

I don't know how to "reproduce" this on your side, it just doesn't show for me idk.
I streamed multiple games with the option on, but everything else worked. Just power play never showed.

Can someone maybe help me out, is there something I can change / adjust that it works?

The powerplay timer looks great and I'd love to be able to see it on stream again.

Just to avoid this question: Yes, I used a working Riot Api Key, and set up the programm like usual.

Aprechiate any help.

Cheers 
Jannis

**Comment by Jadiac5** [comment]
Update:
It shows up... like this:
![image](https://user-images.githubusercontent.com/114788069/227270586-4765851e-033f-44c5-b800-3a794908fb98.png)

**Comment by sdomi4** [comment]
It looks like you may not have a theme set.
Could you try going to the theming page, applying the default theme, and refreshing the overlay?

**Comment by Jadiac5** [comment]
Still looks the same with the defualt theme:
![image](https://user-images.githubusercontent.com/114788069/227295415-007c98bc-7cbf-4f5d-b20a-da407f367209.png)
(I changed bg color between the posts)
Ill check the .css, maybe the padding or box size make it look like this. Had the same thing with the red side gold on 10+k where the text moved upwards)

**Comment by Jadiac5** [comment]
I got it to delign and fit with setting .sb-red.power-play and blue:
(839 + 847)
right:-400px and left: -400px

![image](https://user-images.githubusercontent.com/114788069/227320624-37ced147-68c9-41ef-98c0-6e51aca7f6f4.png)

Now the team score is on it tho :(

**Comment by sdomi4** [comment]
Based on your other issue you are using the overlays at 1440p, this might cause some issues with the CSS.
If this is the case, could you try setting the image size / browser source size in OBS to 1920x1080 and check if the issue is also present (without the modifications if possible).

**Comment by FireFoXz09** [comment]
> I got it to delign and fit with setting .sb-red.power-play and blue: (839 + 847) right:-400px and left: -400px
> 
> ![image](https://user-images.githubusercontent.com/114788069/227320624-37ced147-68c9-41ef-98c0-6e51aca7f6f4.png)
> 
> Now the team score is on it tho :(

You also need to modify the score position during power plays. I don't remember where but the score moves to a number of pixels to the right or left during a power play. I had the same issue and this is how I solved it.

Also, like sdomi4 said, try using it at 1920x1080 in obs. We almost never stream above 1080p anyway so there's almost no need to go above this (tho if you have a reason to do so, share it and we'll maybe find a turnaround to help you.)

**Comment by Jadiac5** [comment]
Ill try the 1080p today. But if you remember where the score position during power play line is so i could change it it would be great.

Thanks for the tip :)

**Comment by Jadiac5** [comment]
So I tried the 1080p method but I still get the same problem. Not sure how to fix this at this point.

**Comment by sdomi4** [comment]
- The event never showing in the first place (if not resolved): Make sure your client is set up with the correct events for the LiveEvents API
- The powerplay banner looking wonky is down to theming. We'll try to release an update for the default theme to make sure everything looks fine. For now, you can get things to fit by changing font sizes using these in a theme (I'll leave fiddling with font sizes to you):
```css
.power-play {
  font-size: 15px;
}

.power-play h3 {
  font-size: 15px;
}
.power-play h2 {
  font-size: 15px;
}

.power-play h1 {
  font-family: var(--primary-font-family);
  font-weight: 400;
  letter-spacing: 1.5px;
}
```
This should also make sure the score is moved to account for the powerplay banner properly.

**Comment by Jadiac5** [comment]
Changing the Values made it work.
I went with:
h3: 25px
h2: 25px
h1: font-weight: 600
h1: font-size: 15px

Got it to this:

![image](https://user-images.githubusercontent.com/114788069/228080600-5cd44b35-b82a-4eac-a32e-eff84fcb8899.png)


Thanks for the help. 
Now I only need to find out why the overlay (only top section, items and level work) isn't refreshing unless I manually do it haha.
maybe farsight switching on and off every 1 second has sth to do with it.

**Comment by sdomi4** [comment]
Yes, this is due to an issue with Farsight and memory offsets, this should hopefully be fixed within a few days.
