### ISSUE TITLE
[ Feature ] In-Game Dragon and Baron animation from PNG to GIF

### ISSUE THREAD

**Issue by RealShavy** [RCVolus/league-prod-toolkit#296]
Where can I change it from png to gif in the code or do I have to write something new?

**Comment by sdomi4** [comment]
Assuming you mean the kill events: Modifying these is non-trivial and not doable with a theme, as the images are set dynamically.
If you wish to use different images, you will need to modify [ingame.js](https://github.com/rcv-prod-toolkit/module-league-in-game/blob/1b04b23055a4e36dec97705106fbc53cebd12975/frontend/gfx/ingame.js#L419) and have the new images present in the `img` folder.
You might need to fiddle with the ingame HTML/CSS to make things work. Keep in mind these changes are overwritten when updating the toolkit/module, make sure to back up any changes you make.
