### ISSUE TITLE
[ Question ]  Obtaining Old Scoreboard

### ISSUE THREAD

**Issue by Miblizzard** [RCVolus/league-prod-toolkit#303]
Sorry if this has already been answered, Is there any way to obtain the old scoreboard from below, I've gone back to version 1.2 and i cant seem to obtain the old one. 

![image](https://user-images.githubusercontent.com/84755973/228032302-19d08771-957d-4560-a7fb-cab6860c2e0c.png)

**Comment by sdomi4** [comment]
No need to downgrade :)
You can just set the scoreboard to inactive in the ingame configuration and use the [teams overlay](http://localhost:3003/pages/op-module-teams/gfx/in-game-gfx.html) to get there:
![image](https://user-images.githubusercontent.com/84572334/228033251-0a14940a-4e2a-4816-be15-ccd376441a10.png)

**Comment by Miblizzard** [comment]
That worked Thanks for the quick responce!
