### ISSUE TITLE
[ Question ] overlay's timer and stat not updating automatic

### ISSUE THREAD

**Issue by brunogracco** [RCVolus/league-prod-toolkit#304]
I started using the League Production Tool 3 day's ago... i have everything update and kinda working correctly.... Just the In-Game status seems to don't work properly...

Everything else is working fine, the level up popup, the item buy popup, the drakes, harold, the baron power play shows up but the gold doesn't count, the towers, team total gold, match timer, team scores only work when i refresh the browser source...

i'm have the farsight on, and synced, but they keep swapping between "Standby" and "Sync" every ~second

**Comment by Jadiac5** [comment]
I got answered this on my thread already:
"> Yes, this is due to an issue with Farsight and memory offsets, this should hopefully be fixed within a few days."
https://github.com/RCVolus/league-prod-toolkit/issues/292#issuecomment-1488415907

Looks like they are already looking into it.

**Comment by Himyu** [comment]
See this issue for more information https://github.com/RCVolus/league-observer-tool/issues/9
