### ISSUE TITLE
[ Bug ] Caster cockpit OP.GG overview link broken for EUNE

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#309]
The link to OP.GG is does not have the parameters for a successful redirect.

Images:

![castercockpitbug1](https://user-images.githubusercontent.com/73833646/229905368-e26725fc-d222-4b99-a9fe-332ec9a1d433.png)

![castercockpitbug2](https://user-images.githubusercontent.com/73833646/229904846-81ec0a62-5c89-4ea8-8ecd-120224c2a722.png)

Correct link should look like this:
https://www.op.gg/multisearch/eune?summoners= [summoner list]

Also wouldn't hurt to encode space characters to %20.

- OS: Ubuntu Server 22.04 LTS
- Node: v16.16.0
- Prod Tool Version: 1.5.1
- Observer Tool Version: 5.0.0
- Streaming Software & Version: OBS Studio 29.0.2

**Comment by Himyu** [comment]
Apparently OP.GG has different server shorts then riot them self that why its not matching up, we will look into a fix for that issue.

**Comment by Himyu** [comment]
issue is fixed with the newest version of the caster cockpit
