### ISSUE TITLE
[ Bug ] Tower count does not reset when spectating a new game.

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#310]
**Describe the bug**
When spectating back to back games, the tower counter does not reset on the in-game-overlay.

**To Reproduce**
Spectate a game (ideally) from start to finish, when finished, start to spectate a new one.

[Video](https://www.youtube.com/watch?v=IEcK9re9mpA)

Refreshing the browser source makes the powerplay disappear at least, however the towers remain the same.

The only solution that I found so far is to restart the toolkit and the observer tool between games.

**System:**
- OS: Ubuntu Server 22.04 LTS
- Node: v16.16.0
- Prod Tool Version: 1.5.1
- Observer Tool Version: 5.0.1
- Streaming Software & Version: OBS Studio 29.0.2

**Comment by Himyu** [comment]
This happens when the ingame is not reset before by a new champ select, if you want to spectate games without champ select or without champ select sync in the observer tool, for now, you have to restart the tool yes. we might add a button to reset the game manually without restarting thee tool

**Comment by figyl** [comment]
I was pretty sure it wasn't a one time thing, so I tested it with a random lobby i found in the client in the custom games list.

[Video](https://www.youtube.com/watch?v=CGWhz3kAhig)

Even with a champselect it doesn't seem to reset.

**Comment by figyl** [comment]
Toolkit logs:
[lpt.log](https://github.com/RCVolus/league-prod-toolkit/files/11153648/lpt.log)

Observer tool: Everything synced.

**Comment by Himyu** [comment]
With the newest update to the tools and the modules, this issue should be resolved. But in case there are still any issues we also added a reset button to the module page where the in-game data can be resetted. if there are still any issues with that please let us know.
