### ISSUE TITLE
The In-Game Information won't update every second happen again

### ISSUE THREAD

**Issue by syuanlyu** [RCVolus/league-prod-toolkit#311]
I see the same behaviour in Chrome and the OBS browser source.
When i in the game, farsight is active in the observer tool but it show standby not sync.

OS: Windows 10
Node: 16.14.0
Prod Tool Version: 1.5.2
Observer Tool Version: 5.0.1
Streaming Software & Version: OBS 28.1.2
Browser: Chrome

**Comment by sdomi4** [comment]
This is down to missing updates to Farsight. This is taking longer than usual due to the move from 32bit to 64bit with 13.7.

**Comment by syuanlyu** [comment]
ok thanks.
