### ISSUE TITLE
Is there any way to change the size of the champselect UI pick champion image size ?

### ISSUE THREAD

**Issue by syuanlyu** [RCVolus/league-prod-toolkit#323]
Is there any frontend or config can adjust the champselect UI pick champion image size?

**Comment by sdomi4** [comment]
Champ select is not trivial to customise as it's an older codebase. You can modify the relevant files (`prod-toolkit\modules\module-league-champselect-ui\src\europe`) directly, just make sure to back up any changes you make before updating the toolkit/modules.

**Comment by syuanlyu** [comment]
Thanks!

**Comment by syuanlyu** [comment]
I'm a little confused that the file I download is different from the website I see.
![image](https://user-images.githubusercontent.com/107873438/233901033-628855af-9cd3-4ba2-ab4e-f32ae5cf35b7.png)
![image](https://user-images.githubusercontent.com/107873438/233901090-95b8329d-97da-4289-9136-b1dc98bc5032.png)
So I paste the second picture's files to the first picture folder and modify the relevant files (prod-toolkit\modules\module-league-champselect-ui\src\europe) directly, but nothing change.
I think that maybe I'm missing some steps.

**Comment by sdomi4** [comment]
Sorry, I should have been a bit more specific. The toolkit download consists of pre-built modules, so it looks different than the source.
To modify, download the source folder for the module, place it in the modules directory (or copy the source contents into the existing folder), and [build the module](https://github.com/RCVolus/league-prod-toolkit/wiki/4.-Developer-Documentation#building-modules) after making desired changes.

**Comment by sdomi4** [comment]
Update/correction: you'll need the whole repository to build changes, you can refer to the link above on how to set up the submodules after cloning the repo.

**Comment by syuanlyu** [comment]
Thanks! I will do my best to try it.
