### ISSUE TITLE
[ Question ] What happens to customised gfx/css files

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-prod-toolkit#324]
I customised some of the CSS Files (e.g. the ingame module css) to get a better overlay for my usecase. What happens if there is a update to LPT? Will they be gone? Should i save them? Or will they stay?

**Comment by Himyu** [comment]
If you install an update your changes will be lost, please have a look at https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation where we explain how you can customize things in a safe way

**Comment by Freeedooo** [comment]
Yeah i read that one. Since I am unexperienced in HTML or CSS, i dont get how that one works. Do you have a use case which you can share with me?

**Comment by sdomi4** [comment]
Besides the example in the wiki, you can find example modifications in past Issues:
- [Changing font size in the scoreboard](https://github.com/RCVolus/league-prod-toolkit/issues/292#issuecomment-1485570587)
- [Changing the scoreboard background](https://github.com/RCVolus/league-prod-toolkit/issues/264#issuecomment-1466659805)
- [Changing colors in overlays](https://github.com/RCVolus/league-prod-toolkit/issues/170#issuecomment-1340962272)

If you have specific customisations in mind, feel free to ask and I'll check the necessary theme changes.

**Comment by Freeedooo** [comment]
Yeah that's awesome. I might get it now with these examples. I'll close this issue and reopen it in case of any problems. Thanks for your help <3
