### ISSUE TITLE
how do I work on a custom ui or theme?

### ISSUE THREAD

**Issue by willenglishiv** [RCVolus/league-prod-toolkit#325]
**Is your question related to a problem? Please describe.**

I'm trying to clone and start working on this repo, and I'm aware there are private submodules.

I saw in another issue to ignore submodule updates for those private repos. That works for the top level ones, but the plugin-theming one has hidden submodules, and I can't update my main project without dealing with that...

I'm not as experienced with submodule based projects, so if there is an easier way to do this I'm all ears.  The StackOverflow that was linked in the previous issue was not very in-depth to my current problem

**Describe alternatives you've considered**

**Additional context**

**Comment by sdomi4** [comment]
The theme submodules have their own `.gitmodules` config where you can exclude the themes in question: `\league-prod-toolkit\modules\plugin-theming\.gitmodules`.
I don't have a device handy where I can test, but just adding `update = none` to each private submodule in both `.gitmodules` files should do the trick (If it does, let me know and I'll add this to the docs).

Depending on what customisations you have in mind, [themes](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation) might be all you need; which means no need for messing with git/manual builds :)

**Comment by willenglishiv** [comment]
yeah, I know the themes exist but I would like to build something custom for our team. Knowing it's webpages ultimately being served I would like to learn how it all works.

Btw, I put the update = none line under all the submodules.  The new problem is that since the initial 'git submodule init' failed it's not updating the other submodules, not sure if I have to manually pull them in myself or how to fix that.

**Comment by sdomi4** [comment]
We've updated the .gitmodules config and excluded the private repos by default. It should work without issue / additional changes on a fresh clone :)

**Comment by willenglishiv** [comment]
sweet, thank you!
