### ISSUE TITLE
[ Question ] Action-Buttons with http/post

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-prod-toolkit#328]
On every button in LPT there´s an "action-link". I get what these do, but i want to use them with my stream deck for example. Does anyone know what to do?

**Comment by sdomi4** [comment]
You can configure any of the action links with a website action, just make sure you tick the background option:
![image](https://user-images.githubusercontent.com/84572334/233774291-51955ee1-5b1f-4a37-8aca-d2b845bbec7e.png)

We might add this to the streamdeck plugin directly at some point, but this should work well enough for now.
