### ISSUE TITLE
Load match (postgame) throws Uncaught error in Handler

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#33]
`2021-11-08T16:20:57.378Z [error] lpte-svc    : Uncaught error in handler: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at Registration.handle (C:\Users\Maxim\Desktop\league-prod-toolkit-develop\modules\league-end-of-game\dist\plugin.js:53:33)
    at C:\Users\Maxim\Desktop\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:95:29
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (C:\Users\Maxim\Desktop\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:93:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
`
![Unbenannt](https://user-images.githubusercontent.com/23660832/140781050-f0ef11d0-b697-4d3d-9d75-e6b8c5532858.PNG)

**Comment by sdomi4** [comment]
Hi Maxim

A few questions to try and identify the issue:
- Do you have a valid API key configured?
- What type of game were you spectating? (Custom, Custom with Tournament Code, ...)
- Did you have the Observer Tool synced during the whole game?

**Comment by MaximilianRu** [comment]
- Yes, a personal API Key is in use
- When I remember correctly, I tried it on a Custom game with Tournament Code and on a ranked game from the friendliest.
- Yes, the Observer Tool was synced and showed no errors.

But I didn't set any Teams or match in the production tool

**Comment by sdomi4** [comment]
Were the games in question on EUW?
If yes, we'll try to reproduce and solve the issue.

**Comment by MaximilianRu** [comment]
Yes, the games were in EUW

**Comment by sdomi4** [comment]
Hi Maxim

Unfortunately, we haven't been able to reproduce the issue so far.
We suspect it may be related to some recent client troubles on Riot's side of things; could you please try again and see if the error still occurs? If yes, please let us know the steps to reproduce as precisely as possible.

**Comment by Himyu** [comment]
This issue was fixed with a recent push to this repo, please just download the newest version :)
