### ISSUE TITLE
[ Question ] How make the runes working in pick&ban?

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#330]
I cannot find the tutorial and i don't know how to make runes showing in OBS. Can you please help me? It would be amazing

Thank you very much (i tried to set it up but i was not succesful)

**Comment by sdomi4** [comment]
Prerequisites for runes to work:
- Valid API Key (and API not broken like it was yesterday)
- Game is visible in spectator-V4 (for custom games, make sure spectators are set to all)

Then add the runes overlay to OBS like any other browser source:
![image](https://user-images.githubusercontent.com/84572334/233774484-2ee46ea6-d815-44a6-892d-1013d2ba1978.png)

The buttons on the admin page control which runes (lane matchup by lane matchup) are shown. If the game isn't loaded automatically based on information from the observer tool, set a game manuall using the player lookup in Game State.
