### ISSUE TITLE
[ Question ] Order of applications?

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#331]
Hello,

i want to ask if there's any order of starting the apps. I was having one stream all things popping up and glowing and everything but on the other day nothing was popping up. Yes, there was farsight turned on or should i refresh sources all the time before broadcast? Because i did my last stream - everything was working and showing from website in my OBS but when i went to game - nothing popped up - neither herald or baron or drake. Just nothing.  Can you please help me?

Thank you. <3

**Comment by sdomi4** [comment]
The toolkit needs to be running for the observer tool to work. Make sure everything is connected + synced and the LiveEvent API is set up properly. When in doubt whether OBS shows actions, use the test buttons in the InGame Module :)
