### ISSUE TITLE
[ Question ] [In-game] Getting champions played by players

### ISSUE THREAD

**Issue by 238SAMIxD** [RCVolus/league-prod-toolkit#332]
**Is your question related to a problem? Please describe.**
I would like to use character images which are stored in `/serve/module-league-static/img/champion/tiles/${champion}_0.jpg`. The problem is I don't know if I can get champion played by summoners from `gameState` 

**Describe alternatives you've considered**
The alternative would be to make another request to LoL Live Game API to receive a champion for every player

**Additional context**
I am implementing Total Gold Graph and I need champion images for it (it is almost finished excluding that)

**Comment by sdomi4** [comment]
The information *should* be present in GameState if the active game has been loaded. The runes module loads champs and images for reference: https://github.com/rcv-prod-toolkit/module-league-runes/blob/c23ac5a34e13824cc82f9881f320aa5e0f916d13/frontend/gfx-script.js
