### ISSUE TITLE
closes itself

### ISSUE THREAD

**Issue by ManuelHenao** [RCVolus/league-prod-toolkit#34]
hi. i try to run start.bat or npm start, it start and load plugins but closes itself inmediatly.

**Comment by ManuelHenao** [comment]
i dont get any errror or warning. just it opnes and closes

**Comment by ManuelHenao** [comment]
Ok, i got an error that ist pretty dificult to see cuz it closes. i got a picture.
![error](https://user-images.githubusercontent.com/64715702/142062290-bd9c1ff5-d589-4943-9c91-5612eb4e89d0.png)

**Comment by sdomi4** [comment]
Hi Manuel

It looks like the preseason patch broke things, please bear with us while we work on a fix

**Comment by sdomi4** [comment]
The issue is with the communitydragon, for now, you can manually set the game version in the config file by adding `"gameVersion": "11.22.1"` to the static-league object in the config
