### ISSUE TITLE
[ Feature ] Creation of Tournament Codes

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#345]
**Is your feature request related to a problem? Please describe.**
Somehow incorporate the whole process to create tournament codes using your production API key,

**Describe the solution you'd like**
Maybe creating the whole process in an existing module or maybe creating a new module for it.

**Comment by sdomi4** [comment]
This is far outside our current plans for the toolkit; In our experience external providerrs work fine for this purpose. It might be something we consider far in the future if we run out of other ideas.
