### ISSUE TITLE
[ Question ] In-Game State not working/updating properly

### ISSUE THREAD

**Issue by kaprixal** [RCVolus/league-prod-toolkit#346]
I'm using the prod toolkit and when using the In-Game state, nothing is updating correctly and everything on the browser source is static (time, towers, everything). I'm not sure how to fix this, and I've also tried updating and re-installing as necessary. The only way it will update is by constantly refreshing the browser but that's not practical.

I've tried to see if others have had this problem but I haven't been able to find a solution as of yet. Is there something specific I have to do so that it works?

This is what I see in game and on the tool. I've also enabled everything on the League Observer Tool as well.

![image](https://user-images.githubusercontent.com/29721326/235837741-aa2a04a1-332f-4d5b-9da9-e6171a2400a2.png)
![image](https://user-images.githubusercontent.com/29721326/235837769-b4c7a583-685f-4b93-83d0-cd11ef70533b.png)

The timer is static at 5:43 on the tool and 5:34 on obs and does not change until i refresh. Same with other aspects of the tool like towers, drags, etc.

**Comment by sdomi4** [comment]
League just got a patch, things will resume working after offsets for Farsight are updated.

**Comment by sdomi4** [comment]
Offsets are updated, the Observer Tool got a patch as well to fix an issue with gold. Everything should work as expected after an update.
