### ISSUE TITLE
[ Bug ] Weird level-ups from Neeko when transforming

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#347]
**Describe the bug**
Neeko's level seems to change every time she transforms, making the popup appear even though she is already leveled up.

**To Reproduce**

1. Configure the level up for some levels. In my case I have Lvls 2, 3, 6, 11 and 16
2. Neeko should transform, then the level up bugs and appears repeatedly

**Expected behavior**
Neeko levelup notification should only pop up when SHE levels up.

**Screenshots**

**System:**

- OS: Win 10
- Node: 16.15.1
- Prod Tool Version: 1.5.3
- Observer Tool Version: 5.1.1
- Streaming Software & Version: OBS
- Browser: Opera GX

**Additional context**
[Video with the Neeko Bug](https://www.youtube.com/watch?v=fJ0NJN75uC0)

**Comment by sdomi4** [comment]
Looking at the video, it seems her level actually changes back to level 2 when transforming to a minion.
Should be a solvable issue thouhgh, you can expect a fix for most cases fairly soon.

**Comment by Himyu** [comment]
With the newest update to the in-game module this issue should be fixed
