### ISSUE TITLE
[ Question ] Showing dragons with ingame ?

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#365]
Hi,
i just want to ask if there is a way of showing dragons without score display on in League client.

**Comment by sdomi4** [comment]
This isn't implemented at the moment, but should be possible with the data we have – No promises on when.

**Comment by MDvorky** [comment]
Because i cannot use the active scoreboard then. I need to somehow show the dragons, but i don't know how.

**Comment by sdomi4** [comment]
At the moment, the intended usage is to just cover up the ingame scoreboard with the customised one while still showing the dragon icons below.

**Comment by MDvorky** [comment]
Thank you. We can close this ticket :)
