### ISSUE TITLE
[ Question ] Elder PP - picture instead of Baron

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#367]
I was seting up the PP's but when i push the elder timer it comes up with the baron image. Is there a way to swap images or correct the images that for elder timer would pop up timer with dragon? Is there a way to program it in the ingame.css or is it not possible and i'm stuck with the baron.png ? :D 
![obrázok_2023-05-28_032628529](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/4bc57e0b-e060-494e-821a-a69822056b8b)

**Comment by sdomi4** [comment]
I'm assuming this happens when you use the test button?
Elder powerplay is not implemented at the moment, #249 for reference.

**Comment by MDvorky** [comment]
Yeah i used the test button. Then it is fine :D I'll wait for the Elder power play
