### ISSUE TITLE
[ Bug ] Bugged gold count on second and third match on the HUD

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#373]
**Describe the bug**
After the second match start one side of the HUD go totally crazy with the gold count. As well in the third match. One side is working fine but the other one ( which is losing the series).
I tried to restart everything and refresh the HUD but it did not work.

**Comment by sdomi4** [comment]
What do you mean by "going crazy"? Is the actual number wrong, or does formatting no longer work properly once a score is set in a bo3?

**Comment by MDvorky** [comment]
Number goes crazy. Starts at 2,5 K as usual but going up without kills but on the loosing side. Difference between HUD and live score is 1K or even more. Sometimes happen this gold fever on the both sides. Restart did not work. Even with the whole shutting down the whole systems. It stucks on the golds.

**Comment by Himyu** [comment]
Yeah, I can confirm this issue. It is related to the league observer tool recognizing more elements as players as there are in the game.

**Comment by figyl** [comment]
We have observed this bug with viego and wukong so far.
### Clips:
- [Viego](https://clips.twitch.tv/DreamyInterestingJayCopyThis-v8jMULYt5HI7HBpZ) While transforming via his passive.
- [Wukong](https://clips.twitch.tv/SaltyAmazingFiddleheadsWutFace-jhLEPjbcumuBMX8_) While using W and E.
- [Unidentified 1](https://clips.twitch.tv/RenownedElegantBisonBCWarrior-qm01K_iVy2dVgLi1), [Unidentified 2](https://clips.twitch.tv/MildFurtiveCroquetteFUNgineer-8_AGx7X0JgyyCe-U) 2 clips from the same game

**Comment by Himyu** [comment]
This issue should be fixed with the newest version of the in-game module. if you reencounter any of these issues, please let us know and we will look into it again
