### ISSUE TITLE
[ Bug ] Runes not working 

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#374]
Hello (sorry for opening so many tickets),

but i have issues with runes. They don't working. You've sent me the instructions, i tried that - but it did not work either.  Or is it working only via tournament codes?

**Comment by Himyu** [comment]
Runes don't work in custom games. They only work in normal games and games created with tournament codes.

**Comment by MDvorky** [comment]
Thank you with information :)
