### ISSUE TITLE
[ Question ] Game State Module

### ISSUE THREAD

**Issue by VXLTCasts** [RCVolus/league-prod-toolkit#383]
**Is your question related to a problem? Please describe.**
I am unable to load the game state plugin with either the gameID or the Summoner name

**Describe alternatives you've considered**
attemped changing the Api Key and rebooting the system, reinstalling the toolkit, none of which seemed to work

**Additional context**
![image](https://github.com/RCVolus/league-prod-toolkit/assets/123594044/f315468f-6739-479b-b864-aed72977e94c)
I primarily notice the following error with code 403, I don't know if it's from my end or if there is a bug

**Comment by sdomi4** [comment]
I can load the matchid without issue, 403 indicates an issue with your key. Make sure your key is valid and is configured correctly. The config should look like this:
```
"plugin-webapi": {
    "apiKey": "RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
    "server": "EUW1"
  },
```

**Comment by VXLTCasts** [comment]
would you be kind enough to inform me of the specific location of the Config file?

**Comment by sdomi4** [comment]
It's in `...\prod-toolkit\modules\plugin-config\config.json`

**Comment by VXLTCasts** [comment]
seems that the issue was that the install.bat and the api.bat both weren't adding the key for some reason, adding it manually fixed all the current issues, really appreciate the support <3 have a great day
