### ISSUE TITLE
[ Bug ] This static module is causing a serious issues 

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#384]
I tried to update new static. I tried to reinstall it but nothing happened as well. I'm adding the screenshot. Please help me. 
![obrázok_2023-06-12_174545287](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/e82155c9-96a5-4c4d-9fe8-4502cb088f89)
I'm having the series tomorrow.

**Comment by sdomi4** [comment]
I am unable to reproduce this issue when installing following the [install guide.](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation). The filepaths in the screenshot don't look quite right, it seems you are running the module in isolation?
Please reinstall, make sure you download the [toolkit release](https://github.com/RCVolus/league-prod-toolkit/releases/latest) and not the source code.
