### ISSUE TITLE
[ Bug ] Module module-league-prm crashes when entring prime league group link

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#395]
**Describe the bug**
When trying to load a prime league table for example https://www.primeleague.gg/leagues/prm/3062-summer-split-2023/group/509-gruppenphase/5558-division-4-6 the server crashes with the error
`TypeError: string-strip-html/stripHtml(): [THROW_ID_01] Input must be string! Currently it's: undefined, equal to:
undefined`

**To Reproduce**

1. Go to 'League PRM Tables'
2. Add a Link to the PrimeLeague group under 'Link to Group'
3. Click on 'Get Table'
4. See crash and error in terminal

**Expected behavior**
PRM table gets shown in the preview and server does not crash

**Screenshots**
<img width="544" alt="Bildschirmfoto 2023-06-15 um 13 45 02" src="https://github.com/RCVolus/league-prod-toolkit/assets/11475491/41a35fff-3992-4121-918a-29aa6570ff3b">

**System:**

- OS: MacOS 13.4
- Node: 16.19.0
- Prod Tool Version: 15.4
- Observer Tool Version: -
- Streaming Software & Version: -
- Browser: chrome

**Comment by Himyu** [comment]
Ok, this was due to a change from the prime league on their group pages and should be now fixed with the newest update to the module itself.
