### ISSUE TITLE
[ Bug ] Caster Cockpit `Copy Action-Link` buttons copy wrong url

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#396]
**Describe the bug**

**To Reproduce**

1. Go to 'Caster Cockpick frontend'
2. Click on any 'Copy Action-Link' button
3. Paste copied link somewhere
4. See that euw instead of the webserver is used.

**Expected behavior**
Correct link is copied

**Screenshots**

**System:**

- Node: [e.g. 16.4]
- Prod Tool Version: [e.g. 1.3.0]
- Observer Tool Version: [e.g. 1.0.0]
- Streaming Software & Version: (If it is a problem while streaming or testing)
- Browser: [e.g. chrome, safari]

**Additional context**
The problem here should be that in `cockpit.js` the server is used for the op.gg link generation but then in the html it is assumed that $server is the host like in all other copy cases.

**Comment by Himyu** [comment]
This is fixed with the newest version of the caster cockpit module v0.11.0
