### ISSUE TITLE
Not showing items [ Bug ]

### ISSUE THREAD

**Issue by SacredDonJuan** [RCVolus/league-prod-toolkit#397]
I have problem with the LiveEvents, it is showing just the killed objectives but not builded items.

- OS: [W10]
- Node: [e.g. 16.7]
- Prod Tool Version: [e.g. 1.5.4]
- Observer Tool Version: [e.g. 6.2.0]
- Browser: [e.g. chrome]

**Comment by SacredDonJuan** [comment]
Fixed, you have to add OnChampionLevelUp and OnItemPurchased in to LiveEvents.ini

**Comment by sdomi4** [comment]
For the record, item purchases and level ups are not obtained through live events, there is no need for that config and using it may have unintended side effects.
The only reason for events not showing up would be the ingame api not starting up as expected (should be noticeable in the observer tool) or no triggers being configured in the ingame module.

**Comment by SacredDonJuan** [comment]
That's weird, it just worked when I added these two things to the .ini file. Where do I see the API not starting? Because everything looks normal. Do you have any other idea for a fix without side effects?
