### ISSUE TITLE
[ Bug ] Gold/XP Leaderboard does not sort correctly

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#405]
**Describe the bug**
The lists show the gold and xp values in sorted order but the names and champion icons are not correct.

**To Reproduce**

1. Spectate a game
2. Compare gold in scoreboard with the new leaderboard
3. See error

**Expected behavior**
The icons and names match

**Screenshots**
![telegram-cloud-photo-size-2-5229110159211612739-x](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/b50ff588-9346-4a0d-aaab-75935cf6cfaa)

**System:**

- OS: MacOS and Windows
- Node: 16.7.0
- Prod Tool Version: 1.5.4
- Observer Tool Version: 6.2.1
- Streaming Software & Version: OBS
- Browser: chrome

**Additional context**
I think the problem here is that `state.player` is sorted inplace when saving `sortedForGold`. When iterating over `state.player` we are already iterating over the sorted list but the goldLeaderBoard order is still the inital order so when getting the current gold div the current code expects that state.player and goldLeaderBoard match the order and after that only the gold and the position is updated. 
So either the icon and name needs to be updated here to or the state.player is never allowed to be sorted.

**Comment by Himyu** [comment]
I am not able to reproduce this issue. I noticed you use an outdated version of the prod-tool and observer-tool did you not change the information on this issue? and please also check your node version. if your information reflects the versions you use please make sure to update everything and try again.

**Comment by JanRogge** [comment]
Sorry i updated the information and everything should be up to date.

I also tried to get a few more information and i download the newest zip and tested that all with the same result.

Initalstate: state.player is in game order
![Screenshot_1047](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/fbc0d9dc-aef6-4f78-ab29-96e2324070b8)

Then sortedForGold is saved and now state.player is sorted after most gold
![Screenshot_1048](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/a5cfa126-c0bc-4f6d-b58e-ebf8c7e4c052)

Now lets look at the iteration. I skipped the first one since cho really has the most gold. Here the current player is '1' and because of that we get the second child of the goldLeaderBoard which is Reksai. But as we can see since Viego has the second most gold state.player[1] returns viego.
So then the gold value of viego is set on the second child.
![Screenshot_1049](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/079271e3-a7a7-4e17-82bb-67c9c02b9045)

In the last step the transformation is done here you look for the index of viego which as we know is the second entry in sortedForGold. But then the transformation is set again on the second child which still has the name and icon of reksai.
![Screenshot_1050](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/08bf7008-5a9c-45dc-ad0e-6250d48cd013)

I hope this helps a bit since for me that looks like a real bug. But i could miss some magic sind im currently only debugging the ingame.js

**Comment by Himyu** [comment]
Yea ok, I see what the problem is and I try to see if I can reproduce and fix this issue right away, Thanks for the detailed report.

**Comment by Himyu** [comment]
Could you please download the newest patch to the in-game module v5.0.1 and tell us if that fixes this issue?

**Comment by JanRogge** [comment]
Seems to work fine now thanks for the effort :thumbsup:

**Comment by Himyu** [comment]
Nice! thanks for letting us know
