### ISSUE TITLE
[ Bug ] Modules update pop up Java errors

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#407]
I did update new modules because my friend told me that in-game now can pop up xp and lvl and gold leaderboard. But since I've updated it, in-game doesn't work at all. I received like bunch of java processes pop up windows and in the engine or command line just showing that cannot read summoner's name and also showing that summoner name doesn't exist at all. Pickban works perfectly fine but as soon as my game load up everything crashes and pop ups jump up and everything freeze. Immediately League tool cannot connect to the server. So I don't know where the mistake is. As soon as I get to the computer I will try update java. 
I think that I updated in-game and static or prm.

**Comment by sdomi4** [comment]
The toolkit does not use any Java. If you are seeing Java errors, they are unrelated to the toolkit.

If you receive errors in the output of the prod-toolkit please post them here so we can understand what is going on.
If the toolkit window closes, you can start the toolkit in Powershell (Shift+Right Click in the toolkit folder and type `npm start`) to see the output before the crash.

**Comment by MDvorky** [comment]
So do you suggested update Java or Node?

**Comment by sdomi4** [comment]
Feel free to update Java, as said above the toolkit is entirely unrelated to Java. Do not update Node, we build and test on a specific version (16.7)

**Comment by MDvorky** [comment]
I did not update the Node. I was updating the static and ingame with new module. I will send the screenshots as soon as I'll be able.

**Comment by MDvorky** [comment]
So this is picture from friday. 
![Snímka](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/98fdb59f-650c-4d9d-966a-190d607fb340)

**Comment by sdomi4** [comment]
Can you share your LiveEvents.ini configuration file please?

**Comment by MDvorky** [comment]
Where can i find it?

**Comment by MDvorky** [comment]
Also i recieve this error - as last time. I don't know what to do.
![image](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/f00be595-43d9-4eba-9206-70ce829242e1)

**Comment by sdomi4** [comment]
The LiveEvents config is in your game folder, see the [observer tool readme](https://github.com/RCVolus/league-observer-tool#setting-up-liveevents-api).
Can you give more details about the crash above? It seems to occur when a game is starting.
- What type of game is it?
- Is the observer tool running on a spectator or player?
- How many players are in the game / are there any bots in the game?

**Comment by MDvorky** [comment]
Custom game. Observer tool is running on a spectator and there are 10 players in the game and no bots.

**Comment by MDvorky** [comment]
[LiveEvents.txt](https://github.com/RCVolus/league-prod-toolkit/files/11891535/LiveEvents.txt)

**Comment by MDvorky** [comment]
Issue is still persisting. I don't know what to do. Same issue as last time, i redownload it, fresh install but nothing working. Please help.

**Comment by sdomi4** [comment]
Can you try removing these lines from the LiveEvents config and check if it helps?
```
OnMinionKill
OnNeutralMinionKill
OnDamageGiven
```

These events are not used by the tool and might cause unexpected behaviour.

**Comment by MDvorky** [comment]
I will try it at Monday and let you know - thanks for now :)

**Comment by MDvorky** [comment]
Okay, i found the workaround - before going to match, if i got a error i restart the toolkit. It helped me in every case. Then just hit the reload in OBS and everything working just fine.
