### ISSUE TITLE
[ Bug ] Cannot run the start. bat 

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#408]
Cannot get the link - tried to reinstall few times. Still downloading dragon cache. And then press any key to continue.
![obrázok](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/6a317557-5721-41db-bf3d-2cc0617e2ad7)

**Comment by MDvorky** [comment]
And another picture 
![obrázok](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/f98db1ab-a5db-41ca-b34a-880af259b05f)

**Comment by sdomi4** [comment]
I am unable to reproduce this – the download works fine on a fresh install.
Can you try clearing `last-downloaded-version` in your config and try starting the toolkit again?
If the issue persists, check if you have any programs or permissions set that could interfere with the download and moving around of files (e.g. Antivirus/Ransomware Protection features)

**Comment by MDvorky** [comment]
Where can i clear config?

**Comment by sdomi4** [comment]
If the issue still persists, you can force a redownload by clearing the version in `...\prod-toolkit\modules\plugin-config\config.json`, for more details see [the FAQ](https://github.com/RCVolus/league-prod-toolkit/wiki/FAQ#toolkit-shows-multiple-request-timed-out-errors--missing-assets)
