### ISSUE TITLE
[ Bug ] Custom Index doesnt load .GIF files for Champ-select UI

### ISSUE THREAD

**Issue by SeddsyLive** [RCVolus/league-prod-toolkit#410]
.GIF Files are not loaded propperly, for custom themes.

**Comment by sdomi4** [comment]
This is a general issue with overwriting the default logo using themes.

As a workaround, you can rename your .gif file to `logo.png` and it should work.

**Comment by SeddsyLive** [comment]
Well, the problem is still not solved by that. :/ 
![image](https://github.com/RCVolus/league-prod-toolkit/assets/137650933/6c141bf8-0864-4feb-b741-dc566cc90f33)

**Comment by sdomi4** [comment]
Can you share the gif you are trying to use? I was able to have an animated gif load when trying it out myself.

**Comment by SeddsyLive** [comment]
https://we.tl/t-ZmHtE8Mb09

**Comment by sdomi4** [comment]
![image](https://github.com/RCVolus/league-prod-toolkit/assets/84572334/83d27cc4-030e-4988-a6c1-257d83fde7c8)
Works fine for me (although the gif doesn't have any transparency). Make sure you actually rename the file to `logo.png` including the file extension, not just to `logo.png.gif`

**Comment by SeddsyLive** [comment]
Oh now i see, missunderstood you in that way. anyway since im not using any colors i kinda dont need the transparency :D Thank you!
