### ISSUE TITLE
[ Bug ] Live events are not popping up

### ISSUE THREAD

**Issue by SeddsyLive** [RCVolus/league-prod-toolkit#411]
Live events are not popping up once they are done. F.e. Drakes/Barons doesnt pop-up if the team kill them.

**Comment by sdomi4** [comment]
Please double check you have set up the LiveEvents API properly, see the [observer tool readme](https://github.com/RCVolus/league-observer-tool/tree/main#setting-up-liveevents-api) or #250

**Comment by MDvorky** [comment]
Seddsy, we can call :D I will show you :D
