### ISSUE TITLE
[ Question ] In-game controls

### ISSUE THREAD

**Issue by SeddsyLive** [RCVolus/league-prod-toolkit#412]
![image](https://github.com/RCVolus/league-prod-toolkit/assets/137650933/1cc367de-1d1a-4d02-8021-194d2ad8bf33)
Is there a way, to make Items <div> same way as the settings panel? I mean, make it checkboxes. Mby it would be more user friendly in that way

**Comment by sdomi4** [comment]
While possible, this isn't fully trivial and not a priority.

**Comment by SeddsyLive** [comment]
Got it ^^
