### ISSUE TITLE
[ Question ] Copy Action-Links

### ISSUE THREAD

**Issue by benholness** [RCVolus/league-prod-toolkit#417]
Hey everyone, I had a question around the 'Copy Action-Links' you can use. Is there are way for me to add these to my Stream Deck so I can click on one for say the Gold Leaderboard to pop up, or the Level + XP Leaderboard to show? Would be really handy to know as I do a lot of solo casting :)

Thanks!

**Comment by sdomi4** [comment]
Yes, check out #328 :)

**Comment by benholness** [comment]
Thank you so much @sdomi4! Appreciate the speedy response ❤️

**Comment by benholness** [comment]
This is what I tried before and I ran into an issue, but I solved it! 

Something that might catch other users off guard is if you are enabled authentication, make sure to add `?apikey=YOUR_API_KEY` at the end of the action-link (or `&apikey=YOUR_API_KEY` if a ? has already been used in the query string)
