### ISSUE TITLE
[ Bug ] Cannot sync Farsight

### ISSUE THREAD

**Issue by s2candy2013** [RCVolus/league-prod-toolkit#418]

**Comment by s2candy2013** [comment]
My fasight keep standby when im joined game, so i can't get data
![Screenshot 2023-06-28 175408](https://github.com/RCVolus/league-prod-toolkit/assets/33875583/827a5b73-600f-48e4-b2fd-903d2adb7594)

**Comment by s2candy2013** [comment]
@sdomi4  can u help me

**Comment by s2candy2013** [comment]
i think game update make farsight wrong offset or somethingelse, if u fix for it tag me tks

**Comment by sdomi4** [comment]
Should now be resolved with new offsets.
