### ISSUE TITLE
[ Bug ]Ingame Data

### ISSUE THREAD

**Issue by Nexusmedia21** [RCVolus/league-prod-toolkit#420]
hey i get this error then i try to go ingame/replay of game
2023-06-29T22:39:43.051Z [info ] server      : Listening for requests on http://localhost:3003
2023-06-29T22:40:18.800Z [info ] plugin-webapi: Fetching match data for matchid=6469590330
2023-06-29T22:40:18.917Z [error] plugin-webapi: Failed to get match information for matchId=6469590330. Maybe the match is not over yet? error=AxiosError: Request failed with status code 403
2023-06-29T22:40:18.919Z [error] module-league-state: Loading match failed for gameId=6469590330

**Comment by Nexusmedia21** [comment]
![bug gold](https://github.com/RCVolus/league-prod-toolkit/assets/137824774/8246fc6c-4711-4b9f-9b80-2dc25a854c43)

**Comment by Nexusmedia21** [comment]
now i got this problem

**Comment by Nexusmedia21** [comment]
can someone help me quick :(

**Comment by sdomi4** [comment]
For the ingame data; make sure you have a valid Riot API key configured as noted in #416.

For the gold, do you see this issue when using the default theme or when using a customised version?
Do you see any errors in the browser console?

**Comment by Nexusmedia21** [comment]
no errors and riot api key? i only have the api key from the localhost site

**Comment by Nexusmedia21** [comment]
all is working fine kill feed/level up/item buy/Scorboard kills towers but the only thing is not working well is the gold tab and exp tab and platings was shown 0 but all platings was destroyed

**Comment by Himyu** [comment]
For the platings please make sure you followed all steps when installing the observer tool.
Maybe the plating event is missing from your league config files.

**Comment by Himyu** [comment]
Regarding the problems with the gold tab, we will have a look into it.

**Comment by Himyu** [comment]
Do you use any kind of custom theme or customized the CSS or HTML in any way?

**Comment by Nexusmedia21** [comment]
No Custom Things

**Comment by Himyu** [comment]
Ok then please provide us with the toolkit version you are running and the version of your in game module.

**Comment by Nexusmedia21** [comment]
my version of the toolkit is the 1.5.5 and ingame module is 5.0.1
![wqeq2](https://github.com/RCVolus/league-prod-toolkit/assets/137824774/472d9779-88b3-41ef-8d0d-c58fede90971)
![asqeqw](https://github.com/RCVolus/league-prod-toolkit/assets/137824774/f101c056-81c0-498e-90b7-ad1457ea1455)

**Comment by Himyu** [comment]
this was due to some issues with the display and the default theme and should be fixed with the newest updates to the in-game module. Please let us know if it is still a problem for you.

**Comment by Nexusmedia21** [comment]
Ok i will Look to update it and Test it

**Comment by Nexusmedia21** [comment]
short question are there any free themes for the overlay ?

**Comment by Himyu** [comment]
No there are not besides the default theme we provide.
