### ISSUE TITLE
[ Bug ] Tags Checklist Option for Scoreboard Not Working

### ISSUE THREAD

**Issue by MordredXYZ** [RCVolus/league-prod-toolkit#421]
**Describe the bug**

The tags option for the scoreboard in-game does nothing.

**To Reproduce**

1. Open In-game module
2. Uncheck Tags
3. Click Save
4. Observe the tags are still there.

**Expected behavior**

I expected the team tags to disappear when unchecking this option.

**System:**

- OS: [e.g. iOS] Windows 11 Pro
- Node: [e.g. 16.4] Unsure, I think I'm 0.2 behind current?
- Prod Tool Version: [e.g. 1.3.0] 1.5.5
- Observer Tool Version: [e.g. 1.0.0] 6.2.1

**Comment by Himyu** [comment]
This issue is fixed with the newest version of the in-game module v5.0.2
