### ISSUE TITLE
[ Feature ] Gold graph during game

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#422]
It would be awesome to have gold graph during game such as league broadcast have :D

**Comment by benholness** [comment]
this would be amazing! my viewers love seeing the gold graph change throughout the game

**Comment by Freeedooo** [comment]
+1 <3

**Comment by Himyu** [comment]
We are already working on this feature. We working to figure out some logistics regarding performance and maintaining a certain level of customization.
But we are actively working on it.

**Comment by Himyu** [comment]
This feature was added with the last major version to the ingame module

**Comment by benholness** [comment]
Hey @Himyu, thank you so much for adding this in. After playing around and using the gold graph there a couple of issues I've run into that I wanted to highlight:

1. The gold graph is squished when the output is set to 1920px x 1080px. Not entirely sure why this is the case (see attached screenshot).
2. I noticed that it is a canvas element but is there any way to use CSS to adjust the elements within the gold graph (I can't seem to target them to see what to target as a CSS selector)
3. Is there a way to add a title to the gold graph, right now it doesn't have much context without a title. The leader board slide in panels have a title to help explain to viewers what the data is showing.

![image](https://github.com/RCVolus/league-prod-toolkit/assets/28854222/95e2b54d-a5fb-4fb2-a366-719335ce6ed4)

**Comment by Himyu** [comment]
1. I will try to fix that ASAP

2. Unfortunately no not really because we are using a library to generate the graph there is no CSS way to target stuff
Although I will add some CSS variables that people can change to affect the graph itself 
(team colors are already a thing)

3.  Yes that is a good idea

**Comment by Himyu** [comment]
Ok, we fixed the resizing issue, added a heading, and fixed some minor issues.
And we added a 30-second refresh when the graph is active as well.

**Comment by benholness** [comment]
Amazing stuff @Himyu! I'll test it out on my end in a sec 👍

**Comment by Himyu** [comment]
Ok perfect, please let us know if you have any updates for us 👍

**Comment by benholness** [comment]
@Himyu seems to be all good from testing it out on my end. Also tried out some styling and different slide in animations and works a treat. Thanks again!

**Comment by Himyu** [comment]
Nice. Thank you for testing it. We will ad some minor changes to the CSS modification to the graph in the future but the base feature is done so we will close this issue.
