### ISSUE TITLE
[ Bug ] Level Up leaderboard interfere ingame graphic

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#423]
I don't know what to do. This leaderboard i cannot hide - it is still in the picture even if i press hide it. See the picture below:
![image](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/da691dfe-ac22-4acc-8777-47585eae33ee)

**Comment by Himyu** [comment]
I cannot reproduce this issue. due you use any customer them or altered the CSS or HTML in any way?

**Comment by MDvorky** [comment]
I will try redownload IT and let you know.

**Comment by MDvorky** [comment]
Today i will try new version and let you know if issue is still present or not.

**Comment by MDvorky** [comment]
Issue is gone.
