### ISSUE TITLE
[ Bug ] Cannot read property 'summonerName' of undefined

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#429]
**Describe the bug**
When trying to spectate a game sometimes in InGameState runs into an error where the player is not found on the Gamestate. The process then restarts thanks to pm2 and everything works fine. But the crash results in overlays resetting since the server is restarting.

**To Reproduce**

1. Spectate a Game
2. Check npm error log

**Expected behavior**
InGameState.js does not crash

**Screenshots**
```
/root/league-prod-toolkit/modules/module-league-in-game/dist/controller/InGameState.js:442
        if (this.gameState.player[id].summonerName === currentPlayerState.summonerName)
                                      ^

TypeError: Cannot read property 'summonerName' of undefined
    at InGameState.checkNameUpdate (/root/league-prod-toolkit/modules/module-league-in-game/dist/controller/InGameState.js:442:39)
    at /root/league-prod-toolkit/modules/module-league-in-game/dist/controller/InGameState.js:435:18
    at Array.forEach (<anonymous>)
    at InGameState.checkPlayerUpdate (/root/league-prod-toolkit/modules/module-league-in-game/dist/controller/InGameState.js:434:32)
    at Timeout._onTimeout (/root/league-prod-toolkit/modules/module-league-in-game/dist/controller/InGameState.js:177:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**System:**

- OS: Ubuntu
- Node: 16.7
- Prod Tool Version: [e.g. 1.3.0]
- Observer Tool Version: 6.2.1

**Additional context**
Currently not able to 100% reproduce the problem. But it happend 2 Games back to back yesterday while casting.
While testing before the stream it crashed for the first person i spectated but worked fine after that.

**Comment by Himyu** [comment]
yes, I also encounter this error and we will look into it.

**Comment by MDvorky** [comment]
I had also similar issue where toolkit cannot read summonerName or even doubt it if this player exists which cause my toolkit went down and i was forced to restart the whole toolkit and then it worked just fine.

**Comment by Himyu** [comment]
This is due to the observer tool sending the wrong or uncompleted date after the game start. this issue is fixed with the newest update we rolled out to the observer tool and the newest update to the in-game module. if you have any issues after the updates, please let us know.
