### ISSUE TITLE
[ Feature ] Add Copy-Action links for the End of Game toggles

### ISSUE THREAD

**Issue by benholness** [RCVolus/league-prod-toolkit#431]
For the End of Game screen, it would be amazing to make the **Show Items** and **Show Damage** have **Copy Action links** like the other elements of the app do (see screenshots).

This will enable users to switch between them via a Stream Deck button rather than going to the app page itself - makes it much easier to use.

**Location of the End of Game screen toggles**
<img width="955" alt="Capture3" src="https://github.com/RCVolus/league-prod-toolkit/assets/28854222/386ef877-937f-47c2-b688-96be6ef8d90b">

**An example of where a Copy-Action link is for the In-Game screen**
<img width="866" alt="Capture4" src="https://github.com/RCVolus/league-prod-toolkit/assets/28854222/425dbcb8-4b66-4eb6-ba70-057a3050c3b8">

**Comment by benholness** [comment]
I would go as far to say any of the buttons within the app that interact with the overlays, would be great to let them all have Copy-Action buttons :)

**Comment by Himyu** [comment]
With the newest update to the prod tool itself and update to the modules we overhauled the copy action link action everywhere and added some new ones as well.

**Comment by benholness** [comment]
Amazing @Himyu, thank you for implementing this. Helps us one-man-band shoutcasters a tonne ❤️
