### ISSUE TITLE
[ Bug ] Configs and Themes deleted after module update

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#432]
**Describe the bug**
I just updated a few modules via the web interface and after that all the configs and themes were gone.
So the "plugin-theming" module had an empty theme folder, the config.json in "plugin-config" was gone, team database with icons, the riot api key reset, etc.
That were all modules that were updated. I had a backup of those files but still not good that the files were all gone. The server couldnt even restart after the module updates since the config.json was missing and crashing the server.

**To Reproduce**

1. Update a module like "plugin-theming", "plugin-config", "plugin-database", "module-league-teams" (since that module for some reasons saves the team images :D)
2. Look for the config files of the module
4. See files are gone

**Expected behavior**
Config files should be migrated and themes should not be touched. There was no theme at all not even the default theme.

**System:**

- OS: Ubuntu 22.04
- Node: v16.7.0
- Prod Tool Version: 1.5.4
- Observer Tool Version: -
- Streaming Software & Version: -
- Browser: -

**Comment by saadbruno** [comment]
i don't know if this  is a different issue, but it seems like this also happens with the Docker image, which makes it almost impossible to use.
Every time you restart the docker image, it seems to reinstall all the modules, which in turn creates a new `modules/plugin-config/config.json`, even if it's mounted to a persistent volume.

**Comment by Himyu** [comment]
Should be fixed with the newest release [v1.7.0](https://github.com/RCVolus/league-prod-toolkit/releases/tag/v1.7.0).

**Comment by JanRogge** [comment]
Looks like the theme and configs are still there after an plugin update great ^^

**Comment by JanRogge** [comment]
On Question i have left is is there an easy way of updating the toolkit?

The module are updateable over the webinterface but i found no way to update the core itself easy.

Also since i didnt use it quite a while one module was so old that it crashed when unzipping dragontail which prevented me from using the webinterface to update the module that made a problem.

I had to fix the module myself to get into the webinterface and then get the complete update.

**Comment by Himyu** [comment]
There is currently no way to update the toolkit like the modules, there may be an installer in the future but not right now.

**Comment by Himyu** [comment]
And for the old module, there will be a minimum version of the toolkit needed for the modules themself which prohibits you from installing modules if the prod tool is too old.
if the modules are too old, there should be a feature that warns you if modules become too old.
