### ISSUE TITLE
[ Bug ] Gold leaderboard doesn't work

### ISSUE THREAD

**Issue by saadbruno** [RCVolus/league-prod-toolkit#446]
**Describe the bug**
Gold leaderboard is doesn't show anything, player data on the websockets are empty.

**To Reproduce**

1. Join lobby as spectator
2. Start the lobby

**Expected behavior**

**Screenshots**
<img width="841" alt="image" src="https://github.com/RCVolus/league-prod-toolkit/assets/23201434/36e751b7-77e9-4cda-8598-1215c34550f9">

**System:**

- OS: Observer: Windows 10, Prod Toolkit: Ubuntu 22.04
- Node: The one in the latest Docker iamge
- Prod Tool Version: 1.6.0 (docker)
- Observer Tool Version: 6.2.4
- Browser: Chrome

**Additional context**
Testing on Tournament Realm. 
In-game, Live Events and Farsight are synced and green.
TR Patch is 13.13

**Comment by sdomi4** [comment]
Is the scoreboard working fine? This data comes from Farsight, which might be using memory offsets from 13.14 as of wednesday.

**Comment by saadbruno** [comment]
Yes, the scoreboard works fine, kills, towers, timer, everything works.
The only thing that doesn't show up is the gold and xp leaderboard.

Tournament Realm is still on 13.13. Would that be the cause of it? Is there any way to force Farsight to use the 13.13 offsets?

**Comment by saadbruno** [comment]
Actually, I just noticed it's also happening on public servers, on the v13.14 patch.
I tried to test with a replay (and not as spectator on a live lobby), and got the same issue.
([this replay](https://www.leagueofgraphs.com/match/br/2773308294), if that matters)

I'm trying to figure out how exactly to reproduce. Cause I got it working on replays once, then it suddenly stopped working. Tried opening other replays, restart the observer-tool, restart my PC, nothing seems to fix it. I'll keep trying to get a consistent reproduction and I'll update this thread.

Any help would be welcome.

**Comment by Himyu** [comment]
Yes, there is currently an issue when a new game starts.
For now, you can reset the game data with the button on the in-game module page. That fixes the issue for the current game.
We are still determining where this issue originates and will fix it as soon as possible.

**Comment by saadbruno** [comment]
That indeed fixed the issue for the current game on live servers.
I'll test it on Tournament Realm this weekend and see if it fixes on TR as well.

thank you

**Comment by MDvorky** [comment]
I have a same issue, if i press the reset the game data - will everything work fine?

**Comment by sdomi4** [comment]
> I have a same issue, if i press the reset the game data - will everything work fine?

Probably, but you will have to try to know
