### ISSUE TITLE
[ Bug ] "Copy Action-Link" Button does not copy a link

### ISSUE THREAD

**Issue by casbahcasts** [RCVolus/league-prod-toolkit#447]
**Describe the bug**
Can't copy the "Action-Link". 

**To Reproduce**
1. go to any module with a "Copy Action-Link" button (e.g. in-game -> Show Runes)
2. click the "Copy Action-Link" when it folds open 
3. try to insert it anywhere (Browser, StreamDeck, notepad)
4. it has not been copied

**Expected behavior**
copy and paste

**Screenshots**

**System:**

- OS: WIN 10
- Node: [e.g. 16.4]
- Prod Tool Version: 1.6.0

**Additional context**
however just typing the "Copy-Action-Link" URL into the streamdeck fixes the issue. Just stick to the copy-action-link syntax.

**Comment by Himyu** [comment]
are you using the tool locally or hosted on a server and how do you access the tool? Since all major browsers prohibit copying to the clipboard when a website is only using HTTP, not HTTPS. Wich would make this more of an issue for our documentation.
But if you using it locally and accessing it via localhost, it would be an issue we would have to look into.

**Comment by casbahcasts** [comment]
I am using the toolkit locally and accessing it via http://localhost:3003. Same as I did before when it was still possible to copy the Action Link. Now it seems that I can't copy any Action-Links. 

I am just trying to get it to work with using the syntax from the other Links that I still have in my OBS like this: 

http://localhost:3003/api/events/shortcut/ingest/module-league-end-of-game/show-Damage

**Comment by Himyu** [comment]
Ok then we will have a look into it and come back to you as soon as possible

**Comment by casbahcasts** [comment]
Thank you. I also can't really get the show damage url to work.
Maybe http://localhost:3003/api/events/shortcut/ingest/module-league-end-of-game/show-Damage - syntax just isn't it

**Comment by Himyu** [comment]
Are you using authentication ?

And it is /module-league-end-of-game/end-of-game?state=DAMAGE

**Comment by casbahcasts** [comment]
No, I am not using authentication. Everything is running locally on my PC. 
Also the other links which I copied like weeks ago are still working. But now I am not able to copy any from the browser.  

I'll give that url a try tomorrow! Thank you very much

**Comment by Himyu** [comment]
I was not able to reproduce this issue. Please ensure you update all modules to the newest version as well.

**Comment by MordredXYZ** [comment]
> I was not able to reproduce this issue. Please ensure you update all modules to the newest version as well.

I've had this issue just now as well, with that exact page and problem.

Copy action links do not work, either accessed on the machine running the tool, or on a networked machine.

**Comment by MordredXYZ** [comment]
Tried again, and on the machine hosting the toolkit, I get a copy!

However, the tool pastes an extra : in the http:// section, so every link gets copied as http::// if that makes sense? That should make the StreamDeck GET in background web keys work.

I hope this helps @Himyu!

**Comment by Himyu** [comment]
Ok, I will have a look at that and fix that in the next patch of the toolkit. Thanks for letting me know.

**Comment by Himyu** [comment]
This issue will be finally fixed with the newest update to the prod tool kit!
