### ISSUE TITLE
[ Bug ] Syntax Error doesn't start the toolkit

### ISSUE THREAD

**Issue by casbahcasts** [RCVolus/league-prod-toolkit#462]
**Describe the bug**
The Toolkit does not start since the newest update (see screenshot). is that on my end or is it just because of the new league patch and it still is missing some updates? I even tried to re-install, but the same syntax error occured. 

I even tried to re-install, but the same syntax error occured. 

screenshot 
![image](https://github.com/RCVolus/league-prod-toolkit/assets/139663872/779cd22c-dbe2-4e94-9d5b-270a1eb6780c)

**To Reproduce**

1. start/install toolkit
2. wait till updates completed
3. See error

**Expected behavior**
start of the toolkit

**Screenshots**

screenshot 
![image](https://github.com/RCVolus/league-prod-toolkit/assets/139663872/779cd22c-dbe2-4e94-9d5b-270a1eb6780c)

**System:**

- OS: win 10
- Node: [e.g. 16.4]
- Prod Tool Version: newest

**Comment by sdomi4** [comment]
This is usually down to DataDragon not being updated/available, although it _should_ be as far as I know.
If it doesn't work by tonight we'll take a look at what might be going wrong.

As a workaround, you might be able to set `last-downloaded-version`: to `13.15` manually and the download is skipped (although you might lack some assets then).

**Comment by benholness** [comment]
Hey @sdomi4, which file do you update the `last-downloaded-version`? I'll try this now as I'm having the same issue (both existing download and fresh install)

**Comment by sdomi4** [comment]
Sorry, should have mentioned it - its in `...\prod-toolkit\modules\plugin-config\config.json`

**Comment by benholness** [comment]
No worries! Thank you :)

**Comment by benholness** [comment]
Hi @sdomi4, I've added it in, saved the file and done start.bat but it doesn't seem to be skipping over the DataDragon download and is still crashing. Any thoughts on this?

**Comment by sdomi4** [comment]
I've taken a quick look; It seems that one of the paths changed in CommunityDragon. We'll need to update the static module to fix this.

**Comment by sdomi4** [comment]
[This line](https://github.com/rcv-prod-toolkit/module-league-static/blob/cb9967adc3db4869b204ef1f0785959c86949410/StaticData.ts#L394) will need to be updated to the new filename in CDragon.
The new URL for the file is: https://raw.communitydragon.org/latest/game/items.cdtb.bin.json

The change comes from Riot changing a filename, might not be permanent.

**Comment by sdomi4** [comment]
Should be fixed with an update of module-league-static to 3.10.0. If you manually set a `last-downloaded-version` in the config, make sure to clear the value to force a full download of assets.

**Comment by MDvorky** [comment]
@sdomi4 Where can i found the value to force a full download?

**Comment by sdomi4** [comment]
> As a workaround, you might be able to set `last-downloaded-version`: to `13.15` manually and the download is skipped (although you might lack some assets then).

Here, located in the config file at `...\prod-toolkit\modules\plugin-config\config.json`

**Comment by MDvorky** [comment]
I don't have it. I cannot see it here

**Comment by benholness** [comment]
> Should be fixed with an update of module-league-static to 3.10.0. If you manually set a `last-downloaded-version` in the config, make sure to clear the value to force a full download of assets.

Quick question @sdomi4, how do you update modules? Apologies if this is super obvious

**Comment by sdomi4** [comment]
In the toolkit webpage, go to the modules page and you should have an update button for all modules where updates are available. Make sure to restart the toolkit after updating so everything works properly.

**Comment by MDvorky** [comment]
I cannot reach the webpage without updating tool.

**Comment by MDvorky** [comment]
> > As a workaround, you might be able to set `last-downloaded-version`: to `13.15` manually and the download is skipped (although you might lack some assets then).
> 
> Here, located in the config file at `...\prod-toolkit\modules\plugin-config\config.json`

![image](https://github.com/RCVolus/league-prod-toolkit/assets/104410235/939bf684-1356-4632-8766-2205bc85b4df)

**Comment by MDvorky** [comment]
I don't have it

**Comment by sdomi4** [comment]
> I cannot reach the webpage without updating tool.

Good point - You can update the module by hand by downloading the [3.10.0 release](https://github.com/rcv-prod-toolkit/module-league-static/releases/tag/v3.10.0) `module-league-static.zip` and copying everything into `...\prod-toolkit\modules\module-league-static\` and overwriting existing files.

> I don't have it

Yes you do, it's on line 10

**Comment by MDvorky** [comment]
Even if i clear the value and copied by hand new static, it is still downloading new.

**Comment by sdomi4** [comment]
That sounds like working as intended? Or is it still crashing?

**Comment by MDvorky** [comment]
It is working indeed :) Thank you very much

**Comment by benholness** [comment]
Just wanted to say it's working too @sdomi4, thank you for your help today on this. I'll let you know if I come across anything when I cast later today.
