### ISSUE TITLE
[ Bug ] After module update modulegets listed twice with the old version

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-prod-toolkit#468]
**Describe the bug**
After updating a module the module is shown twice in the list. 
![Screenshot_1058](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/bee0a388-d475-4ddc-83cd-3c75ff2cc442)

**To Reproduce**
Update a module with the new version 1.7.0

**Expected behavior**
Plugin is not displayed twice but only once and with the new version number.

**Screenshots**
![Screenshot_1057](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/a1563566-c4d9-400e-8ab0-33cc0792b80c)
![Screenshot_1058](https://github.com/RCVolus/league-prod-toolkit/assets/11475491/32d23022-f086-4618-972c-f5cf3e052c57)

**System:**

- OS: Ubuntu
- Node: v16.7.0
- Prod Tool Version: 1.7.0
- Observer Tool Version: [e.g. 1.0.0]
- Streaming Software & Version: (If it is a problem while streaming or testing)
- Browser: [e.g. chrome, safari]

**Comment by Himyu** [comment]
Fixed with [v1.7.1](https://github.com/RCVolus/league-prod-toolkit/releases/tag/v1.7.1)
