### ISSUE TITLE
[ Question ] Relating to Customizing Modules (Champ Select)

### ISSUE THREAD

**Issue by Rookie001MC** [RCVolus/league-prod-toolkit#469]
What version of Svelte for the internal modules that you guys use? 

I ask this because I intend to write a custom Champ Select for my Esports club, however the current version of Toolkit uses NodeJS v16.7, which some libraries (especially frameworks like Svelte) may not support well.

**Comment by sdomi4** [comment]
Everything runs on the latest versions of Svelte:
```json
...
"svelte": "^4.1.2",
"svelte-check": "^3.4.6",
"svelte-preprocess": "^5.0.4",
...
```
We are in the middle of moving things to Node 20 with Node 16 going out of support this year. Everything should build & run on Node 20 already :)

**Comment by Rookie001MC** [comment]
So nice to hear! Now I don't need to forget to switch versions when running all this stuff!
