### ISSUE TITLE
database error?

### ISSUE THREAD

**Issue by sod101316** [RCVolus/league-prod-toolkit#47]
![image](https://user-images.githubusercontent.com/59684822/148174684-dfbe9494-3e80-410b-a7f7-044c77488995.png)
When I run the file, it turns on, but this error pops up. I think it's about mongodb. Is there any way to solve it?

**Comment by sdomi4** [comment]
It seems the toolkit is unable to log into mongodb.
The credentials for mongodb should be contained in league-prod-toolkit/modules/config/config.json, could you double check the correct login is configured?

If you installed mongodb with standard settings, the login should default to username "root" and no password.

**Comment by sod101316** [comment]
In config.json, the password was set to 12345, so I deleted it and it was resolved. Thank you
