### ISSUE TITLE
[ Bug ] Scoreboard freezes and logo shrinks

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-prod-toolkit#470]
I have issue. Im using this software but i have issue for few weeks now. Observer tool keeps crashing me - it was good few weeks ago but since then - my scoreboard keeps freezing and my middle logo just shrinks and i have to restart observer tool while casting. Can you please help what should i do? 

I dont know if it's observer tool bad version or something else.

**Comment by Himyu** [comment]
Could you please include some more details? Which versions are you using? what happens? Include logs maybe?

**Comment by MDvorky** [comment]
Im using the newest version of both programs. Everything is working fine but suddenly it freezes at some random point in the game and when i check the task bar there is no observer tool and after that everything freezes.

**Comment by sdomi4** [comment]
Tracking in https://github.com/RCVolus/league-observer-tool/issues/21
