### ISSUE TITLE
api não imports runes and the complete end game? [ Bug ]

### ISSUE THREAD

**Issue by overkido** [RCVolus/league-prod-toolkit#476]
it imports all data and the post game too, but the drakes made both ingame and post game, the runes of each champion, the total gold of the match, it does not show or matter because it ends the match but the more information it pulls.
the drakes I'm putting manual in the obs already the problem of the post game gold I was not successful in pulling in the api

![image](https://github.com/RCVolus/league-prod-toolkit/assets/89580284/d06e939e-fe78-471f-a889-624c3c0f276f)

![image](https://github.com/RCVolus/league-prod-toolkit/assets/89580284/77de49cc-f950-434d-a36f-0bc23c0faa18)

**Comment by sdomi4** [comment]
As noted on discord, this can happen when the game isn't available in match-v5, as is the case with normal custom games. Games created with a tournament code should be available.

If you have a game ID / match ID of a custom game created with a tournament code let us know and we'll troubleshoot the issue.

Posting the same question multiple times will not get you better results, so please ask once so you don't clutter up our inboxes.

**Comment by overkido** [comment]
> 

the OSL api dev fixed his api bug and pulls all the data with the graph, it was a bug in his api
