### ISSUE TITLE
[ Feature ] Uploading casters' avatars

### ISSUE THREAD

**Issue by 238SAMIxD** [RCVolus/league-prod-toolkit#490]
**Is your feature request related to a problem? Please describe.**
There was no option to upload casters' avatars.

**Describe the solution you'd like**
Displaying custom caster avatar next to their name instead of a logo from a theme. I reused some code from `Teams` module.

**Describe alternatives you've considered**
Manually changing source code to point to avatars.

**Additional context**
I also enhanced the look of the `img` to make it a circle
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/5f93136d-f358-4a9b-84d9-51c0b863612f)
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/a0e9906f-71ac-458b-b617-086e05d36f5d)

**Important**
I added and updated platforms to use font awesome icons so in the future more could be added. **_Font Awesome_ kit needs an update then because actual version does not support new `X-Twitter` icon**
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/9bb7d9ae-c28d-494e-8211-5eca1597475d)
I think those platforms would fit as well:
- **Twitch**
- **X (Twitter)**
- *Instagram*
- *Discord*
- YouTube
- TikTok
- Telegram

**Comment by 238SAMIxD** [comment]
https://github.com/rcv-prod-toolkit/module-caster/pull/12

**Comment by Himyu** [comment]
Replied to your pull request.  A good idea but we still need the option just to display the logo for all those who don't have pictures of their caster.
