### ISSUE TITLE
[ Update ] Font Awesone 6.4.2

### ISSUE THREAD

**Issue by 238SAMIxD** [RCVolus/league-prod-toolkit#495]
**Is your feature request related to a problem? Please describe.**
X-Twitter icon is not available in the outdated kit.

**Describe the solution you'd like**
Updating kit on `fontawesome.com` or creating a new one and updating `.pug` files in `dist\core\web\views` and `frontend\gfx\gfx.html` in Caster module.

**Describe alternatives you've considered**
Keeping icons up to date.

**Additional context**
https://github.com/rcv-prod-toolkit/module-caster/pull/12 is using new X-Twitter icon.

**Comment by Himyu** [comment]
Has been updated for relevant modules and will be included in the next update for the prod tool kit as well
