### ISSUE TITLE
Help with database errors

### ISSUE THREAD

**Issue by kryxeno** [RCVolus/league-prod-toolkit#50]
Hey! I have recently tried to get the lol toolkit working to maybe use it in my own small production, but with my limited knowledge I haven't quite gotten it to work. 

I get an auth failed MongoError and a bunch of topology is closed errors. Afterwards I also get a bunch of timed out request.
I assume it is due to not setting up MongoDb correctly, not connecting with it in the right way or something similar.

I created a cluster on MongoDB, downloaded the compass app, and input the database user credentials in the config. 
If you aren't too busy, could you please assist me?

**Comment by Himyu** [comment]
So if I understand correctly you don't run MongoDB locally? is that correct?

**Comment by kryxeno** [comment]
Oh yeah that is correct. 

I thought the cloud hosting through the MongoDB Compass app was localhosting, but I was mistaken. 
I since tried to host it locally and it seems to be running smoothly!

Thanks for the tip!
