### ISSUE TITLE
[ Bug ] Download of the item.bin.json is not working

### ISSUE THREAD

**Issue by invisan** [RCVolus/league-prod-toolkit#501]
**Describe the bug**
The Download of the item.bin.json seems to be not working anymore. 
When I start the script it downloads the dragontail.tgz unpacks it then moves the Files to Frontend.
It starts downloading the centered Images and after moving and deleting the versioned folder i get the Error that the Text in the item.bin.json is not in the correct format.

**To Reproduce**

1. Go to your Installation of prod-toolkit
2. Click on start.bat
3. Wait for the Start of the Script

**Expected behavior**
Script should start without Problems.

**Screenshots**
![grafik](https://github.com/RCVolus/league-prod-toolkit/assets/6483948/ae5b64ad-05e1-49e9-a876-b786a5465273)
![grafik](https://github.com/RCVolus/league-prod-toolkit/assets/6483948/af58fa09-f618-4bbc-ada7-06036e3ef9a6)
(Cloudflare Message has been anonymized)

**System:**

- OS: Windows 10 22H2
- Node: v18.18.0
- Prod Tool Version: Current
- Observer Tool Version: Current
- Browser: Firefox 118.0.1

**Comment by sdomi4** [comment]
This looks a bit like an issue we encountered with riot renaming a file back in 13.15.
Can you check which version of `module-league-static` you have installed? The version is noted in `...\prod-toolkit\modules\module-league-static\package.json`. The issue should have been fixed from version 3.10.0 onward.

If you do indeed have an old version of the module, you should be able to just update the module by downloading the [latest version](https://github.com/rcv-prod-toolkit/module-league-static/releases/latest), and replacing the files in the module folder.

**Comment by invisan** [comment]
Indeed the module-league-static is only v. 3.9.11 
Guess this does not update automatically. 
It indeed works as expected now. Thanks for the Quick help @sdomi4

**Comment by invisan** [comment]
Indeed the module-league-static is only v. 3.9.11
Guess this does not update automatically.
It indeed works as expected now. Thanks for the Quick help @sdomi4
