### ISSUE TITLE
[Feature] Customizing the "round" dropdown in the teams module

### ISSUE THREAD

**Issue by Dommarsantiago** [RCVolus/league-prod-toolkit#508]
Hello, is it possible to customize the options in the round dropdown in the teams module? I would an option to put Week 1 or something else other than the default ones (FINAL, Quarterfinal, round of 16, etc.) since I am using the tool for a regular season game. Is that something that can be changed in a config file? Any help you can give would be great. Thank you!

**Comment by JoanJuan10** [comment]
To acomplish that you would need to edit the in game html itself and the js of the panel.

**Comment by sdomi4** [comment]
Yes, right now it's not possible to customise these beyond modifying the files directly. We'll look into making a custom option for the dropdown in the future.

**Comment by Dommarsantiago** [comment]
> Yes, right now it's not possible to customise these beyond modifying the files directly. We'll look into making a custom option for the dropdown in the future.

Thank you for the response!
