### ISSUE TITLE
[ Bug ]

### ISSUE THREAD

**Issue by overkido** [RCVolus/league-prod-toolkit#515]
**Describe the bug**

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**System:**

- Node: [e.g. 16.4]
- Prod Tool Version: [e.g. 1.3.0]
- Observer Tool Version: [e.g. 1.0.0]
- Streaming Software & Version: (If it is a problem while streaming or testing)
- Browser: [e.g. chrome, safari]

**Additional context**

![image](https://github.com/RCVolus/league-prod-toolkit/assets/89580284/e3843b5f-42a3-45ce-baae-26f6ca91d98f)

**Comment by sdomi4** [comment]
A 403 error usually indicates an issue with the API key configured.

**Comment by overkido** [comment]
![image](https://github.com/RCVolus/league-prod-toolkit/assets/89580284/87eb4e5a-106f-4dbb-be0f-c2586d265822)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/89580284/54874e8b-2b88-457d-9d21-33260eb9c922)

**Comment by Himyu** [comment]
This issue was due to an older update to the module and has been fixed.
