### ISSUE TITLE
How to put team name and score in Champselect UI and League End of Game?

### ISSUE THREAD

**Issue by sod101316** [RCVolus/league-prod-toolkit#52]
Entering the team name and score in RCVolus Teams doesn't show up. Is there a way to fix this?

**Comment by sdomi4** [comment]
This seems to be a bug, we will work on a fix and update here accordingly.

**Comment by sdomi4** [comment]
My apologies; the team names are not intended to be part of the Champselect UI and the End of Game screen, instead the talk overlay (at http://127.0.0.1:3003/pages/op-rcv-teams/talk-gfx.html) should be used.

Game scores are not part of that overlay yet, but are planned (see Issue #37)
