### ISSUE TITLE
[ Bug ] In-Game data is not working.

### ISSUE THREAD

**Issue by JustSxm** [RCVolus/league-prod-toolkit#525]
**Describe the bug**
Kills, turrets, objectives and gold is all to 0.
Same for gold of every player and xp.

**To Reproduce**

1. Spectate a game
2. Watch the score

**System:**

- OS: [e.g. iOS]: Windows
- Node: [e.g. 16.4] v18.16.0
- Prod Tool Version: [e.g. 1.3.0] v1.7.4
- Observer Tool Version: [e.g. 1.0.0] v6.5.2
- Browser: [e.g. chrome, safari] Brave

**Additional context**
When items and or players level up, that is detected though.

**Comment by JustSxm** [comment]
It could also be related to Farsight staying on "Standby" in the Observer tool

**Comment by sdomi4** [comment]
Thank you for letting us know, there was a hotfix we missed, so offsets for Farsight needed updating. I just successfully tested with new offsets.
