### ISSUE TITLE
Change font in Champ Select UI

### ISSUE THREAD

**Issue by sod101316** [RCVolus/league-prod-toolkit#53]
I want to change the font in the Champ Select UI I change the font in index.css in the theme, other plugins are applied, but the Champ Select UI does not change How can I change it

**Comment by sdomi4** [comment]
This also seems to be a bug, we will work on a fix and update here accordingly.

**Comment by Himyu** [comment]
fixed at https://github.com/rcv-prod-toolkit/module-league-champselect-ui/commit/1cd6016f652550ddd3a8a566424c31592619ca59
