### ISSUE TITLE
[ Question ] Usage of Riot ID's and scrapping of Summoner Names

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#539]
**Is your question related to a problem? Please describe.**
It may be a problem in the near future. So Riot is scrapping SummonerNames on the 20th of November and will switch to use Riot ID's. It may cause problems with the handling of every player. Is this problem considered and will there be an update to fix this?

**Describe alternatives you've considered**
Switching every player's handle from the SummonerName to use the puuid or the RiotiD + Tag.

**Additional context**
Context for said changes: [Tweet from Riot](https://twitter.com/riotgames/status/1713972250750132607)

**Comment by sdomi4** [comment]
We're checking what needs updating; we don't use summoner lookups in a lot of places so it shouldn't have a huge impact.

**Comment by Himyu** [comment]
After some testing, I could not find any issue and as far I can tell riot is only stopping to use summoner names for the tournament API, which we don't use atm. Right now everything still works as usual, if there are changes in the future we will revisit this issue.
