### ISSUE TITLE
Not sure how to install

### ISSUE THREAD

**Issue by Stjepz** [RCVolus/league-prod-toolkit#54]
First of all I don't know is this the right place to write a comment about this "problem" and I'm sorry, but here it goes. 

Like the title says I'm not sure how to install your program. I did install pick and ban UI and I love it, but I would like to use some other features but I need some help. I'm not a coder myself and I find it really hard to understand what to do while installing. Is there any video or anyone willing to help me (maybe Dominik if he is Croatian) installing it.

I'm organizing a LOL tournament and would like to use it. Thank you.

**Comment by sdomi4** [comment]
Hi Stjepz

Is there anything you are unclear on when following the [installation guide](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation)?
We are not planning to make a video for now as we are still actively developing the tool. (and I am also not Croatian :))

**Comment by Stjepz** [comment]
Hello sdomi4, 

thanks for reply. So I followed installation  of prod toolkit and it got me to http://localhost:3003/ which is League Production Toolkit and now I have some tabs Modules, Plugins, Events and Module Config. Problem is I don't know how to use it properly. I'm interested in level up system and item purchase notification and end of game statistics. I read I need to download observer tool which I did. There is only one file named LICENSE inside and don't know what to do with him or how to install it. 

I'll just leave some screenshots, as I mentioned before I'm not a coder myself and most of the things are confusing to me but hey I'm trying and I think your job is awesome and would like more then anything to use it. 

Thanks!
<img width="902" alt="Screenshot_1" src="https://user-images.githubusercontent.com/98229258/150750333-bf1a204c-779f-4117-8eba-e7b792d9b127.png">
<img width="935" alt="Screenshot_2" src="https://user-images.githubusercontent.com/98229258/150750339-93d91e7e-44b9-4a39-8152-eafbfd0e2a26.png">
<img width="961" alt="Screenshot_3" src="https://user-images.githubusercontent.com/98229258/150750341-17fcf688-c834-4ab1-a7b5-0bfc8b564071.png">
<img width="956" alt="Screenshot_4" src="https://user-images.githubusercontent.com/98229258/150750342-07f35ae9-0962-4c39-a9b0-b91687ed489f.png">

**Comment by sdomi4** [comment]
It looks like some modules aren't loading properly, at first glance I suspect an issue with the database. Could you confirm if mongoDB is running and the correct credentials are configured in modules\config\config.json?
If mongoDB is running and accessible, please post the output of the command window when launching prod-toolkit; relevant error messages should be visible there.

**Comment by sdomi4** [comment]
For the observer tool, the download/installer is under releases, we have not released the source code ([here](https://github.com/RCVolus/league-observer-tool/releases/latest)).
Once all modules are working, configuration is documented in the [wiki](https://github.com/RCVolus/league-prod-toolkit/wiki/2.-Using-Prod-Toolkit). If anything there is unclear, please let me know

**Comment by Stjepz** [comment]
I found mongoDB running in my Task Manager so I guess its fine. I've tried again same procedure but I got the same result. I checked confing.json and I think my API key is alright as well as other settings. 

I downloaded observer tool .exe and installed it. I really have no clue what do to now. He got synced I guess with Riot Client but I'm not sure how to transfer it to OBS. 

Since I'm "only" interested in Level ups, item purchase and end game statistics is it production tool just enough or do I need observer tool as well?

Anyways I'm posting a few screenshots that you've asked for and [command window text](https://github.com/RCVolus/league-prod-toolkit/files/7939721/webpack.txt). Btw. dominik are you interested in chat via Discord maybe it would be easier for you to help me. If you want, you can add me Basti#3414.

Thanks

![Screenshot_9](https://user-images.githubusercontent.com/98229258/151121925-51b9bc53-6cff-4e95-b4b3-53466d379a9d.png)
![Screenshot_7](https://user-images.githubusercontent.com/98229258/151121927-9f21c9ae-48ab-4b1c-84de-613b3070da1d.png)
![Screenshot_8](https://user-images.githubusercontent.com/98229258/151121930-12836677-238b-4955-937c-8a79329222b4.png)

**Comment by sdomi4** [comment]
It seems that a lot of modules didn't install properly.
You can either re-run the install.bat script (this will overwrite your configuration), or manually run `npm ci` and `npm run build:modules` (to open a command window, shift+right click in the prod toolkit folder and select "Open PowerShell here, then type the commands).

If the same errors (e.g. "2022-01-26T07:21:50.775Z [error] plugin-database: Uncaught error in database: Cannot find module 'C:\Users\Kenova Gaming 2\Documents\league-prod-toolkit-develop\modules\database\dist\plugin.js'") still occur, please make sure nothing like an antivirus is interfering and/or [redownload ](https://github.com/RCVolus/league-prod-toolkit/archive/refs/heads/develop.zip) the toolkit to make sure all required files are present)

For the observer tool, all you need to do is make sure the correct IP (127.0.0.1 if you are running the toolkit and the observer tool on the same PC) is configured, the steps are described in the [Readme](https://github.com/RCVolus/league-observer-tool). Once configured, you can connect the observer tool to prod-toolkit with the power button, and connect to relevant ingame APIs with the different sync buttons.

To add the overlays to OBS, just add the relevant URLs as a browser source (without any custom CSS, delete the default stuff) to your scene. The Links are all listed in the relevant modules.

We prefer keeping all questions / issues here on Github so we can later reference the troubleshooting steps :)

**Comment by Stjepz** [comment]
I've tried both manually and just by starting I would say I didn't go far. Now on second (my own) PC and I dont have any antivirus or something similar installed.

I have [2022-01-26T15_23_14_852Z-debug.log](https://github.com/RCVolus/league-prod-toolkit/files/7943012/2022-01-26T15_23_14_852Z-debug.log), and [install.txt](https://github.com/RCVolus/league-prod-toolkit/files/7943017/install.txt), [start.txt](https://github.com/RCVolus/league-prod-toolkit/files/7943018/start.txt) text files you might be interested in.

I'm not sure did I download right mongoDB. I downloaded Enterprise server, but there are some Community server and other download links. 

EDIT: I didn't installed mongoDB Compass I dont know if thats necessary?

**Comment by sdomi4** [comment]
The version of mongoDB should not matter for the toolkit (the enterprise server needs a license, if you do not have one you should use the community version). Compass is not required.

Module installation is likely either failing due to missing files or issues with permissions. Could you try running the install.bat with Administrator permissons?

**Comment by Stjepz** [comment]
Now I tried with Run as administrator option and this is [error message](https://github.com/RCVolus/league-prod-toolkit/files/7954798/install.admin.txt) I got.

**Comment by sdomi4** [comment]
Apologies, the install script can't handle running as an admin. You will need to trigger the commands manually as an admin (this way *should* work). To do that:
- Open Powershell as Administrator
- Navigate to the toolkit directory (according to your previous logs, the command should be `cd D:\Users\Vlaho\Downloads\league-prod-toolkit-develop`)
- run `npm ci` and `npm run build:modules`

**Comment by Stjepz** [comment]
Okay. I think I'm getting somewhere :)

First I reinstalled node I think I wasn't using latest version so maybe that was the issue. My friend told me that he is into coding so he saw the problem. He wasn't able to help me further because he had to go but he also mentioned it wasn't connected to server or something. Can you check on my screenshots if everything is installed properly and if yes how am I going to connect it to my LoL client? Do I need to start from champ select to test it or I can just spectate someone to check if everything is fine?

Here are my screenshots 
![Screenshot_1](https://user-images.githubusercontent.com/98229258/151575857-9f6a5431-1c0b-4d2c-95ea-f682c6bde054.png)
![Screenshot_2](https://user-images.githubusercontent.com/98229258/151575862-800b2964-37fc-4244-8a97-b74737e34327.png)
![Screenshot_3](https://user-images.githubusercontent.com/98229258/151575864-30339780-97a0-4c35-afe2-17f0c196faa6.png)
![Screenshot_4](https://user-images.githubusercontent.com/98229258/151575865-d7176c61-8bcb-4524-930e-69e08e953e19.png)

**Comment by Himyu** [comment]
Okay, that looks better and good to know that there is a version problem with node.

Can you please share the console output of the new try where nearly everything loaded?

**Comment by Stjepz** [comment]
[Here](https://github.com/RCVolus/league-prod-toolkit/files/7962681/install.cmd.txt) is a part after installation, and [here](https://github.com/RCVolus/league-prod-toolkit/files/7962683/install.cmd2.txt) is a part when I start doing something and I get some errors.

EDIT: Also do I need League Observer Tool aswell?

**Comment by sdomi4** [comment]
It looks like installation was successful; the only remaining error is related to the database. Could you confirm that the database credentials in the config are correct for your mongoDB installation? (If you installed with defaults, the login should be username "root" and an empty password).
Please also make sure to leave the toolkit running long enough for league-static to complete its downloads of ingame assets (you will need these for item purchases ingame).

You will need the observer tool ([Readme here](https://github.com/RCVolus/league-observer-tool)) to send game data to the toolkit. To test, sync all modules and spectate a game.

**Comment by Stjepz** [comment]
I'm sorry what do you mean by my credentials in the config? Do you mean this screenshot I took? And what do you mean by leaving toolkit running? Is that a cmd.exe that I open with start.exe?
![Screenshot_5](https://user-images.githubusercontent.com/98229258/151667068-8a458418-73a8-4665-8c0d-e649bc83787b.png)

**Comment by sdomi4** [comment]
Yes, I was referring to the user/password in the database object. If the error message (`[error] plugin-database: {"ok":0,"code":18,"codeName":"AuthenticationFailed","name":"MongoError"}`) is no longer present the login is working correctly.

"The toolkit" is the command window that opens when starting start.bat. You should see log messages from plugin-static-league updating you on the status of the download ([like this](https://github.com/RCVolus/league-prod-toolkit/issues/51#issuecomment-1019481853)). If the database login works and all assets are downloaded you should be up and running :)

**Comment by Stjepz** [comment]
Wow it worked! I mean the level up/item system worked but display of turrets didn't work properly. I mean I couldnt see them in my OBS yet on browser I could. Every time I refreshed source in OBS it blinked for a second then it disappeared, then after 5 mins I tried again and it stayed. 
I tested it by spectating someone and it only showed me turrets that was destroyed since I started spectating nothing before is that how it suppose to be?

And I still didn't figure out how end game (gold graph, dragon, etc..) works do I need to spectate them from begging or?

EDIT: Now turrets number is stuck, everytime I try to spectate new game its on the same number I doesn't reset.

**Comment by sdomi4** [comment]
Great to hear its up and running (mostly) :)
I will look into the issues with the towers tonight or tomorrow, for now restarting the toolkit should reset tower counts.
Due to the way the API works, it can only show towers you see falling while spectating, so it might also show more than have actually been killed.

The endgame stats are obtained through the Riot API and require an API key. To load stats for a game:
- First set the game in the LoL Game State module (either by searching for a summoner or by entering the game ID)
- Once the game has finished, load the stats with the "Load postgame" button in LoL Game State
The different stats should then show up in the end-of-game module

Edit: Manually setting the game and loading postgame is only necessary if you have not spectated the whole game (including champion select) with all modules synced in the observer tool

**Comment by sdomi4** [comment]
I am unable to reproduce the flickering issue with towers. Are you running a current version of (standard) OBS?
For reference, here is my configuration for the browser source:
![image](https://user-images.githubusercontent.com/84572334/151887702-99ca5063-bb6f-4852-a620-fd7b0800362c.png)

The tower count not resetting is a bug, restarting the toolkit resets the count (but will clear tournament tree config and similar). I have opened a separate issue to track the bug under #58
