### ISSUE TITLE
Old Champ select UI

### ISSUE THREAD

**Issue by Marunc1** [RCVolus/league-prod-toolkit#565]
Hello, i am trying to figure out how to change the ui for champselect with the old one that is on  [lol-pick-ban-ui](https://github.com/RCVolus/lol-pick-ban-ui/tree/master/layouts/layout-simple) ,  is there a simple way to do it or it can't be changed?

**Comment by sdomi4** [comment]
It can be changed, but its not plug and play, but should be mostly compatible.

Note the simple layout you linked to is not ready to use and is intended to be a starting point for creating your own design.
