### ISSUE TITLE
[ Bug ] Animations when making dragons, baron or herald, as well as leveling up and finishing items do not appear

### ISSUE THREAD

**Issue by sekaiblososm** [RCVolus/league-prod-toolkit#566]
I have configured everything about the live events following each step it has but it does not appear when they kill the dragon or a herald, much less when it reaches lvl 6 it does not appear nor when they finish their objects it does not appear. Have I tried everything, any solution?

{
  "server-ip": "127.0.0.1",
  "server-port": 3003,
  "server-api-key": "",
  "replay-sync-mode": "get",
  "live-events-port": 34243
}

EnableReplayApi=1

OnKillDragon_Spectator
OnKillRiftHerald_Spectator
OnKillWorm_Spectator
OnTurretPlateDestroyed
OnDragonSoulGiven

**Comment by sdomi4** [comment]
These are 3 different config files – can you confirm these are configured in their respectively correct file?
Also, Obs Tool config can now be done directly in the tool and doesn't require editing the config directly.

If everything is configured, all the modules in the observer tool are synced, and you still receive no events, try restarting the toolkit, obs tool, and league and see if the issue persists.

**Comment by sekaiblososm** [comment]
Hello, after hours of trying I managed to fix at least the level and the herald items, but the dragons still do not appear and the power-play is also the only thing that does not appear.


I also followed all the instructions to the letter and the league observer tool every time I start it says that the live events are not completely configured, so go to the page to fix it but there is no way to do it on the page either.

At least for now the levels, items and heralds appear to me

only the dragons, barons and powerplay do not appear to me

**Comment by sdomi4** [comment]
Are you by any chance using LeagueBroadcast alongside the toolkit? That configures LiveEvents differently than we do, so the observer tool complains – you can ignore that error without worrying.

Please post the current contents and path of your `LiveEvents.ini` file if you still see issues.

**Comment by sekaiblososm** [comment]
If I was using leaguebroadcaster what can I do then?

**Comment by sdomi4** [comment]
That shouldn't cause any issues besides the config popup which you can ignore without worrying.

Again, if you still see no events (or only herald), please restart the game, and if the issue still persists post your configs so we can take a look.

**Comment by sekaiblososm** [comment]
Sigue solo apareciendo los dragones las subidas de nivel no, que configuraciones te paso
