### ISSUE TITLE
Is there an example of fully customized theme?

### ISSUE THREAD

**Issue by ToGoodToWork** [RCVolus/league-prod-toolkit#576]
Hi I would like to customize my own theme, but I am having a struggle making any progress. I was wondering if there is maybe some default theme that I can look how its done. 

We have a small tournament with 102 teams and currently we use LeageBroadcast but we found your toolkit and we want to customize it and use it. (Here is the twitch link if you want to take a look. https://www.twitch.tv/stretvyvolavacu )

PS: Sorry I pressed Enter and the question posted without any descripton.

**Comment by FireFoXz09** [comment]
To customize your theme, You'll need two things : new icons (example, for the dragons and baron slain pop-up, or minion and tower icons for the killfeed) and new code. There is a small tutorial available in the FAQ how to create a theme and edit basic color and font to start with. After that, you can go deeper and edit the files a bit more with basic CSS and/or HTML knowledge.

**Comment by ToGoodToWork** [comment]
> To customize your theme, You'll need two things : new icons (example, for the dragons and baron slain pop-up, or minion and tower icons for the killfeed) and new code. There is a small tutorial available in the FAQ how to create a theme and edit basic color and font to start with. After that, you can go deeper and edit the files a bit more with basic CSS and/or HTML knowledge.

Yes, I read that we have icons etc... But this is new grounds for me thats why I asked for some simple default theme that I can study a little bit and understand it. I looked into the github themes there are some but they no longer exists on github.

**Comment by sdomi4** [comment]
There isn't an example theme, and I suspect it wouldn't be of any help if you are unfamiliar with CSS (as a theme is just a bunch of CSS selectors).

If you want to customize anything specific you can always ask here and I will give you examples.

A guide is somewhere in my backlog, but exams are coming up so it's probably going to take a while longer...

**Comment by ToGoodToWork** [comment]
Is there maybe a list of classes divided by plugins that I can edit? Sorry but I have no idea how to get names for the elements. I read the FAQ but how do I find other classes by name?

**Comment by sdomi4** [comment]
The list is planned as part of the guide. Manually, you can just open the overlay in a browser and use inspect element to see the class/ID of whatever UI element you want to mess with.

**Comment by ToGoodToWork** [comment]
That's a great idea, thanks! Maybe add this tip to the FAQ for now. Anyways wish me luck!
