### ISSUE TITLE
Tower kills not resetting after game end

### ISSUE THREAD

**Issue by sdomi4** [RCVolus/league-prod-toolkit#58]
**Describe the bug**
The tower kill counts don't reset after game end (with end of game synced in observer tool)

**To Reproduce**
1. Spectate Game until end with ingame + end of game synced
2. Spectate another Game, tower kills have not cleared

**Expected behavior**
Tower kills should reset when end of game is sent

**Additional context**
End of game is detected properly:
`2022-01-31T23:17:50.062Z [info ] plugin-state-league: Flow: end of game - active`

**Comment by Himyu** [comment]
Is fixed in branch spring cleanup and will be merged as soon that's ready
