### ISSUE TITLE
Summonernames not showing in Champselect[ Bug ]

### ISSUE THREAD

**Issue by Wolfspeltz** [RCVolus/league-prod-toolkit#597]
**Describe the bug**
Went into a custom game lobby to test if champ select works. Its not showing any summernornames tho.

**Expected behavior**
The Summoner Names should be showing in champ select

**Screenshots**
![image](https://github.com/RCVolus/league-prod-toolkit/assets/68478161/613cfb9c-309f-4ea2-9d54-91b161171aa1)

**System:**

- OS: [Windows 11]
- Node: [e.g. 16.4]
- Prod Tool Version: [e.g. 1.9.1]
- Observer Tool Version: [6.9.1]
- Streaming Software & Version: (OBS)
- Browser: [Chrome and Opera]

**Additional context**
Both in the Toolkit preview and in the OBS Browser-scene as well in Opera and Chrome this issue was present

**Comment by Himyu** [comment]
Do you have Champselect and Lobby sync in the observer tool?

**Comment by Wolfspeltz** [comment]
yes. is there any thing that has to be done before pressing these?
I synced lobby oce i was in lobby and syced champ selct once it startet.
but i will try again today maybe it just didnt want to yesterday xD

**Comment by Wolfspeltz** [comment]
ok so i updates my nodejs and now it  worked.
