### ISSUE TITLE
[ Question ] Will Vanguard affect the toolkit and related observer tools?

### ISSUE THREAD

**Issue by paulhlschr** [RCVolus/league-prod-toolkit#614]
This question is not related to any occurring problem, but just out of interest. 

Is there any indication right now that the introduction of Vanguard in League of Legends will break any modules of the toolkit or the Observer tool/Farsight? 

I would heavily appreciate an update in that matter, as I don't want to ask my fellows to try it and get their accounts penalized.

Thank you very much!

**Comment by JoanJuan10** [comment]
Well. I think it's pretty clear by Riot's side when Vanguard joins the game.

![image](https://github.com/RCVolus/league-prod-toolkit/assets/37046841/1de26f7e-acc2-42af-9025-dfb818fba0ad)

Source: [https://www.riotgames.com/en/DevRel/vanguard](https://www.riotgames.com/en/DevRel/vanguard)

**Comment by M1chal179** [comment]
so toolkit rip ?

**Comment by Himyu** [comment]
We are still in discussions with Riot Games but at the moment it looks like the toolkit might take a hit from the changes unfortunately
