### ISSUE TITLE
[ Question ] I'm just wondering how to update gameoffsets. Can we do it ourselves?

### ISSUE THREAD

**Issue by EagleLOL** [RCVolus/league-prod-toolkit#615]
Currently in game features such as gold, level+xp and gold graph modules are not working. This is probably happening because farsight is not updated. Can we update it ourselves? How can we do it?

**Comment by paulhlschr** [comment]
There is a tutorial by the LeagueBroadcast and Farsight developer [here](https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight).

**Comment by EagleLOL** [comment]
> There is a tutorial by the LeagueBroadcast and Farsight developer [here](https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight).

I meant how to change offsets for league-prod-toolkit. Which file do I have to edit in order to get ingame features working

**Comment by sdomi4** [comment]
Unfortunately, we don't have a manual update mechanism at the moment, and I haven't been great at keeping the repo up to date the past couple of patches. Things should improve until Vanguard hits (for which the future is still uncertain).
