### ISSUE TITLE
[ Question ] HUD not updating

### ISSUE THREAD

**Issue by castinggrounds** [RCVolus/league-prod-toolkit#616]
Hello, i just set up everything, but running in the Problem that the HUD (timer, gold, kills,...) is not working. It stays always on 0 and does not update...

I also have the Observer tool and set everything on "sync", but still not updating (everything else then this is working, like herold taken, inhibs taken,...)

Also a picture, of how it 24/7 looks like:
![Unbenannt](https://github.com/RCVolus/league-prod-toolkit/assets/159646265/65611f4c-770e-4cd6-9788-bf80418e9c80)

i would be happy to get some help here... i really love this tool and would like to use it :(

**Comment by paulhlschr** [comment]
This happens due to missing offsets for the current live patch 14.3.1.
You can update the offsets yourselves using the guide [here](https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight). Otherwise you will have to wait for Farsight to update their offsets.

**Comment by ThorsPanzer** [comment]
i have the offset from farsight, but where to put it?

**Comment by sdomi4** [comment]
Unfortunately, we don't have a manual update mechanism at the moment, and I haven't been great at keeping the repo up to date the past couple of patches. Things should improve until Vanguard hits (for which the future is still uncertain).
