### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Syntetikk** [RCVolus/league-prod-toolkit#62]
**Good evening, I am coming to you because of a problem with the installation and operation of league-pro-toolkit & League Observer Tool.**
Sorry if I'm not precise at all, I don't know it at all, it's the first time I'm working on it, I've never used RIOT APIs, I'm a manager for a structure that organizes a league, we would like to use the features available in your toolkit, so I downloaded the version of Node, League Observer Tool, also MongoDB, I took my Riot API Key and I followed the following steps 
1. Download the full source from github
2. Extract the folder to the directory you want to run the tool from
3. run install.bat
4. Enter the configuration values in the script:
5. Navigate to [...]\league-prod-toolkit-develop\modules\config and edit config.json:
6. run start.bat (or run npm start)

![eror1](https://user-images.githubusercontent.com/52052819/152826814-dedf473a-0c8f-401f-8b4e-2425dfd85580.PNG)

_If you need more info don't hesitate! I would really like to be able to use it because it seems to me really complete._

**Comment by sdomi4** [comment]
Hi Syntetikk

The error messages indicate an issue when connecting to the database. Could you make sure mongoDB is running, and that the config holds correct info for the database?

Assuming your mongoDB instance is running locally with default credentials, the config should look like this:
```
  "database": {
    "user": "root",
    "password": "",
    "clusterUrl": "localhost",
    "port": 27017
  },
```

**Comment by Syntetikk** [comment]
Thank you for your quick response! 
I actually have MongoDB running but I don't know how to activate it, or make a database with

![mongodb](https://user-images.githubusercontent.com/52052819/152840033-9ec4f9bc-ff3a-4707-aef2-c986543e188f.PNG)

As for the configuration in the config file, it' s correct

**Comment by Syntetikk** [comment]
In the config file I had a small error, now I have less error but I still have some

![image](https://user-images.githubusercontent.com/52052819/152840572-5e8ccd02-38a4-475c-8c02-1311f32c3ee6.png)

**Comment by sdomi4** [comment]
I am able to reproduce the error message if mongoDB (the server itself, Compass is just a GUI for accessing the server) is not running.
To check if mongoDB is running, you can try connecting with Compass by clicking connect without filling out any info.
Alternatively (or if Compass shows the error `connect ECONNREFUSED 127.0.0.1:27017`), check if mongoDB has registered as a service and is running (open "Services", look for a service named "MongoDB Server (MongoDB)", and make sure the status is "Running")

**Comment by Syntetikk** [comment]
i have : `connect ECONNREFUSED 127.0.0.1:27017`
and MongoDB does not appear in the services, I deduce that it is not started, how can I start it?

**Comment by sdomi4** [comment]
If the service is not present something went wrong during installation.
Could you confirm both Compass and mongoDB server are installed?
They should both show up in Apps and Features:
![image](https://user-images.githubusercontent.com/84572334/152846914-d30e7eff-7d06-4bbf-8830-8c29488a80ef.png)

**Comment by Syntetikk** [comment]
![image](https://user-images.githubusercontent.com/52052819/152851161-ad3accf3-278c-4b19-98d9-f4a7cddc53a9.png)

**Comment by sdomi4** [comment]
Interesting, mongoDB *should* register itself as a service when installing with default values.
Could you try uninstalling mongoDB and reinstalling it in an Administrator context? There may be some issues with the service not registering properly due to permissions/security

**Comment by Syntetikk** [comment]
i can't run it in Administrator, i don't know if the problem is me but when i right click on him i can run it administrator

**Comment by Syntetikk** [comment]
All good ? 
![image](https://user-images.githubusercontent.com/52052819/152863735-323a13c7-adcb-4ee4-b076-50ec324af42c.png)
![image](https://user-images.githubusercontent.com/52052819/152863808-3b0e66d7-8bc3-4b6f-b26d-448dd48e87df.png)

**Comment by sdomi4** [comment]
Yes, these settings look fine. Please be on the lookout for any error messages or windows popups in case the issue persists.

**Comment by Syntetikk** [comment]
Installation completed, 0 errors or messages from Windows

**Comment by Syntetikk** [comment]
And now i can go on data base xD

**Comment by Syntetikk** [comment]
![image](https://user-images.githubusercontent.com/52052819/152864580-4a27aff4-d916-455f-afd5-2df7b60626f2.png)

**Comment by sdomi4** [comment]
In that case, the toolkit should now start without the database errors :)
The toolkit itself takes care of everything in the database.

**Comment by Syntetikk** [comment]
Ok i will try, after the toolkit running, i need to run the league observer right ?

**Comment by Syntetikk** [comment]
I still have a small question, at the level of overlays, they are not at all colored and without logo ect... I had used before the Pick & Ban UI independently of the toolkit and I had already a ready thing, is it possible to have the same parameters on the toolkit ?

**Comment by sdomi4** [comment]
Depending on what you want the toolkit to do, the observer tool and an API key is required, the [Wiki](https://github.com/RCVolus/league-prod-toolkit/wiki/2.-Using-Prod-Toolkit) (should) list which modules require what.

Unfortunately, there is no easy way to port settings from P&B UI. The Wiki has an introduction to customisation [here](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation).

**Comment by Syntetikk** [comment]
When I had downloaded the first Pick & Ban UI without the toolkit I had the team names as well as the coach and the score under the picks with their colored band, now I don't have it with the P&B UI of the toolkit, how to add them?

Before:
![image](https://user-images.githubusercontent.com/52052819/152872084-184c8ebd-5f5e-4d0f-b6fa-7afcf9316877.png)

Now: 
![image](https://user-images.githubusercontent.com/52052819/152872002-e0833a8b-f120-413d-b4fb-a10f111ab8ab.png)

**Comment by sdomi4** [comment]
Team names are not directly implemented in champ select, we add them separately with the talk overlay from rcv-teams. Example from one of our streams:
![image](https://user-images.githubusercontent.com/84572334/152873583-a34bb85c-1ebd-4ac7-8d86-8dab89f5f8fb.png)

(game score is not displayed in that overlay, although it will be added in the future)

**Comment by Syntetikk** [comment]
Thank you for the time you gave me and all the help you gave me!

**Comment by sdomi4** [comment]
Updated FAQ to list this database error; updated wiki to clarify team names in champ select overlay
