### ISSUE TITLE
Discord or any other resources (for themes for example?)

### ISSUE THREAD

**Issue by ThorsPanzer** [RCVolus/league-prod-toolkit#622]
Is there a discord for discussion and fast help? If so where?
And is there some custom made themes for one to download to start with?

**Comment by sdomi4** [comment]
There isn't, the best way to reach out is here. Keep in mind we do this in our free time as a passion project, so fast help is not something we can promise.

There aren't any fully made custom themes beyond the default theme and a few pointers in the wiki. A full customisation guide is long overdue, but I won't put any work into it until we hear more from Riot about the future with Vanguard. If you have specific customisation questions, you can always ask here, there's also a bunch already answered in closed issues.

**Comment by ThorsPanzer** [comment]
I get that and I appreciate that you still put in the work.
I just need some snippets so I can ask ChatGPT to help me with the rest. You wouldn't know anybody that did some changes to the themes? Don't have to be fully customized, just some changes.

**Comment by sdomi4** [comment]
You can find some customizations in closed issues, for example:
https://github.com/RCVolus/league-prod-toolkit/issues/264
https://github.com/RCVolus/league-prod-toolkit/issues/170

In theory, you can just throw any module webpage at chatgpt and ask it to modify the CSS – your mileage on actually usable CSS may vary.

**Comment by ThorsPanzer** [comment]
I'm sorry, this confuses me. I know you don't want to do a full guide on customisation since Vanguard will come but I wanna configurate the appearance for the stream on sunday.
I know in the 3. Customisation Guide you wrote to use "Inspect" to identify CSS classes and/or IDs, but I don't know what to look out for when I press inspect since I'm a beginner. Can you maybe but a screenshot?

What also confuses me is the fact that in the examples you gave me (#264 and #170) and the Guide the call is varying all the time.
In #264 you use `.scoreboard {` in #160 `.module-teams-talk-gfx .vs {` and in the Guide you use `.rcv-teams-ingame-gfx #score-container {` (which is a different color, why is that?) How can I differentiate between them, when to use what, and how to use the inspect?

**Comment by ThorsPanzer** [comment]
I managed to figure it out on my own. It's really not that hard. I might consider making a video to help others
