### ISSUE TITLE
Standby

### ISSUE THREAD

**Issue by AzureAstral** [RCVolus/league-prod-toolkit#633]
Hi, 

I start to use Prod Toolkit today and I have 2 questions : 

- Why my LiveEvent is on STANDBY ? We need to do something ?
- Dragon Event (kill), and Nashor doesnt work too.

Thx for ur answer !
![standby](https://github.com/RCVolus/league-prod-toolkit/assets/82313405/bed81127-be4e-4f73-82dd-3cb6652e1c77)

**Comment by sdomi4** [comment]
The LiveEvents API was removed by Riot and no longer works, we just haven't removed it from the tool yet since we are still uncertain about the future with Vanguard. The objective kill events were from the LiveEvents API and don't work anymore as a result of the removal.
