### ISSUE TITLE
Postgame stat names off center with different number lengths

### ISSUE THREAD

**Issue by sdomi4** [RCVolus/league-prod-toolkit#65]
**Describe the bug**
In the all-in-one postgame stats screen, stat names don't align to center properly when the stats have different amount of digits (see screenshots)

**To Reproduce**
1. Load any postgame where a stat ends up in different lengths (e.g. blue team with 12 towers, red team with 1 tower)

**Expected behavior**
The center stat name should remain aligned to the center

**Screenshots**
"Tours" misaligned with unequal amounts of digits in towers taken:
![image](https://user-images.githubusercontent.com/84572334/153172425-b1702972-8290-45e5-ac7d-43893fa8a2ab.png)

Properly aligned when amount of digits is the same:
![image](https://user-images.githubusercontent.com/84572334/153172542-ede3a0b5-b1e5-437e-a53c-3f84783eecf4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, OBS
 - Toolkit version: latest develop branch

**Comment by Himyu** [comment]
Fixed that and some misalignment with damage graphs and banns and resized ban icons to fit damage graph icons
