### ISSUE TITLE
[ Question ] Vanguard and possible changes

### ISSUE THREAD

**Issue by Antos99999** [RCVolus/league-prod-toolkit#658]
Hi, I haven't found this question anywhere, let alone the answer. 
I know that the introduction of Vanguard greatly complicates the full use of the application and all add-ons, but are you able to determine the probability that you will be able to modify the current plugins to work the same or similarly after the applying Vanguard? 
I must admit, your work is great and I would love for everything to work the same even after the anti-cheat was applied

**Comment by sdomi4** [comment]
How hard did you look? ;) #649 #615 #633 https://github.com/RCVolus/league-observer-tool/issues/132 https://github.com/RCVolus/league-observer-tool/issues/77

The "only" features impacted by Vanguard are ingame, where most things will break. It might be possible to memory read still, but it's fairly unclear and risky.

**Comment by Antos99999** [comment]
I must have missed these threads somewhere.  
Thanks a lot for your answer!  
I have one more question. Are you able to say what exactly things might stop working?
