### ISSUE TITLE
I really need help D:

### ISSUE THREAD

**Issue by reicepontes** [RCVolus/league-prod-toolkit#66]
![Screenshot (14)](https://user-images.githubusercontent.com/98736727/153382134-d32f5a79-e75d-4c21-b2b4-05d6c5b7f960.png)
![Screenshot (13)](https://user-images.githubusercontent.com/98736727/153382138-ac5a413e-c639-4fbb-937a-69776d2925b0.png)

**Comment by reicepontes** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/98736727/153382520-c3b0d883-3854-4a49-a44c-b0e0322c5298.png)

[Removed screenshot with api key]

**Comment by sdomi4** [comment]
Config with api key redacted
![153382524-8a40116a-1e02-4517-a52e-db3861d0e1e3~3](https://user-images.githubusercontent.com/84572334/153395584-5912bd94-7905-4f3f-847d-0f41143d0800.png)

**Comment by sdomi4** [comment]
Could you try manually building the modules and see if any errors/warnings occur?
To do this, open powershell in the toolkit directory with shift+right-click -> "open PowerShell here". 
Then type `npm run build:modules` and watch the output for any error messages

**Comment by Himyu** [comment]
This is related to issue #64 this happens when it takes a lot of time to download the static data.

**Comment by reicepontes** [comment]
I npm run build:modules with administrator privilege but its giving the same output when I do npm start

![Screenshot (18)](https://user-images.githubusercontent.com/98736727/153481870-16cc5e86-25fb-4721-ad76-0d9ac58c486b.png)

**Comment by reicepontes** [comment]
Just want to check my config and config.dist are supposed to be like the above right?

**Comment by reicepontes** [comment]
nvm it changed the output now it looks like this when I npm start 
![Screenshot (20)](https://user-images.githubusercontent.com/98736727/153484301-022c1786-1b91-4627-ac2e-5b95aaff228b.png)

**Comment by sdomi4** [comment]
That error message indicates an issue with the database credentials in the config. On the screenshot, the config itself looks correct. Could you doublecheck that the config is saved as config.json?

**Comment by reicepontes** [comment]
Its saved as config.dist  but the type is json
![Screenshot (23)](https://user-images.githubusercontent.com/98736727/153484963-2878213e-9638-4d3e-bb39-1d90965f7213.png)

**Comment by sdomi4** [comment]
Just to confirm, did you set any non-default credentials during mongoDB installation?

**Comment by reicepontes** [comment]
Im pretty sure I did Im gonna dowload it again and screenshot it

**Comment by reicepontes** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/98736727/153488824-af6daf4c-2d2b-407c-aabd-244e588eb248.png)
![Screenshot (26)](https://user-images.githubusercontent.com/98736727/153488826-14710d07-5d44-4390-b6f5-56c3fd7a2dbc.png)
![Screenshot (25)](https://user-images.githubusercontent.com/98736727/153488829-ebdd2751-7a4b-411c-84e3-3b31c97820ba.png)
![Screenshot (24)](https://user-images.githubusercontent.com/98736727/153488833-55e28deb-2500-4339-b740-483fc5c780ca.png)

**Comment by sdomi4** [comment]
And the toolkit is still showing the same authentication error?
If yes, please check that config.json is still the same as posted above, those settings should be correct

**Comment by reicepontes** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/98736727/153491500-c2db9a91-c7bf-41b6-a8da-2cd737886ab3.png)

**Comment by reicepontes** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/98736727/153491608-a4483b76-7873-46d1-b8d7-e81b2d1daa8b.png)

**Comment by sdomi4** [comment]
If you post your config, please remove/redact your API key, it should not be posted publically.
Could you try clearing the last-downloaded-version value to force a redownload of assets?

- Stop the toolkit
- Edit the config and remove the value in static-league:
```
  "static-league": {
    "last-downloaded-version": ""
  },
```
- Run `npm start` and look for lines from plugin-static-league

**Comment by reicepontes** [comment]
right here 
![Screenshot (32)](https://user-images.githubusercontent.com/98736727/153494937-a258c958-eb4f-4d4a-9a0d-343af6afa56b.png)
![Screenshot (31)](https://user-images.githubusercontent.com/98736727/153494939-9772acf3-1ab3-489f-9298-8ed93a667d5b.png)

**Comment by reicepontes** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/98736727/153495331-f5d24536-24eb-4548-baa8-d2880f32297c.png)

**Comment by sdomi4** [comment]
Are the errors still appearing (after a toolkit restart)?
As far as I can tell, all modules should be up and running :)

**Comment by reicepontes** [comment]
Yes, I crlt c to stop running the toolkit and npm start again but it gives me the same errors
![Screenshot (35)](https://user-images.githubusercontent.com/98736727/153496988-9942228b-5b2d-4302-8200-f3889fec4bb9.png)

**Comment by reicepontes** [comment]
also the league observer tool was giving me this error while running a sec time
![Screenshot (36)](https://user-images.githubusercontent.com/98736727/153499133-9a0bf773-6084-44e8-a66c-74dd5b9b7b1e.png)

**Comment by sdomi4** [comment]
There might still be some problems with the config. Could you copy paste your config.json with the API key removed so we can take a look and try to reproduce the issue?

The observer tool sometimes crashes when the toolkit is restarted while connected, nothing to worry about there :)
