### ISSUE TITLE
( DUVIDAS DOUBTS)module-league-in-game

### ISSUE THREAD

**Issue by ghost** [RCVolus/league-prod-toolkit#661]
I would like to understand when I start serve and give npm start I open localhost in the in-game tab together with lol not a dynamic update. different from champselect.html which is working normally.

**Comment by ghost** [comment]
with the module-league-in-game not updating. As soon as I open lol in spectator mode it doesn't load time, gold, xp.....

**Comment by sdomi4** [comment]
I don't fully understand your question. A lot of the ingame functionality (primarily the custom scoreboard) is impacted by the introduction of Vanguard, which removes our ability to obtain a lot of the data needed. In addition, Riot removed LiveEvents, which impacts things like objective kills.
