### ISSUE TITLE
How can i have the overlay on? I need some help

### ISSUE THREAD

**Issue by int1008** [RCVolus/league-prod-toolkit#669]
Hello, I do not know how to have the overlay on obs. Can you guys help me pls! I read the guides but i do not understand it! I am not a programmer to understand what should i do. PLease help! I used the link of the module in-game http://localhost:3003/pages/op-module-league-in-game/gfx/ingame.html. Can someone help me pls

![Screenshot 2024-05-11 191241](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/183d8a63-e419-4fe6-b370-fb21c0b395ea)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/c51d2a2e-1e23-498e-8090-29b463cec708)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/0c60f45c-38ac-4180-b260-bc13373d3776)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/5017e0a8-4e1f-4340-a9e1-24dd0b2d74a5)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/15f408d6-2133-459a-bcc2-5a0d848dd5e8)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/2fa9b518-6d4d-4277-a797-740367a05fc8)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/be0e4fd0-4377-4181-9fb6-19a966720901)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/89c19007-74e2-4350-bfc0-98105fc5fe64)
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/5deedd5a-2673-423e-90d5-3b7cb0e0b441)

**Comment by sdomi4** [comment]
Add the embed link as a browser source in OBS. Note that most of the ingame features are broken because Riot killed our data sources for them.
Set the browser source size to 1920x1080 and remove the default CSS OBS places in there.

**Comment by int1008** [comment]
> Add the embed link as a browser source in OBS. Note that most of the ingame features are broken because Riot killed our data sources for them. Set the browser source size to 1920x1080 and remove the default CSS OBS places in there.

omg thank you i just did it but how can i have the real time overlay match? THANK YOU SO MUCH
![image](https://github.com/RCVolus/league-prod-toolkit/assets/105333075/13760f86-2e90-44b7-bc03-7e571aba851d)

**Comment by int1008** [comment]
> Add the embed link as a browser source in OBS. Note that most of the ingame features are broken because Riot killed our data sources for them. Set the browser source size to 1920x1080 and remove the default CSS OBS places in there.

oh so when will we can have the real time data again man because of vanguard? Do u think that everything would be ok on December because i want to create a tournament for my Vietnamese friends :( please make a video about this scoreboard overlay a lot of people would watch your video and i will support u guys :3

**Comment by sdomi4** [comment]
We don't expect to get access to real time data again for the moment. Riot has not been helpful and told us to go away (not in those words exactly) when we tried to find a way forward.

There may be news in the future, but expect this tool to receive only a minimum of updates if any for the moment.

**Comment by int1008** [comment]
> We don't expect to get access to real time data again for the moment. Riot has not been helpful and told us to go away (not in those words exactly) when we tried to find a way forward.
> 
> There may be news in the future, but expect this tool to receive only a minimum of updates if any for the moment.

thank you so much and i hope that u guys can have the void grubs timer and how many did the teams have as well too. Thank you so much for ur work :3

**Comment by 238SAMIxD** [comment]
> i hope that u guys can have the void grubs timer and how many did the teams have as well too. 

I have probably made it and it would be ready to create a PR. But for now it is impossible to test and even get events information so this change is pointless :/
