### ISSUE TITLE
[ Bug ] In game Module don't working and live events module too 

### ISSUE THREAD

**Issue by Reec0ns13** [RCVolus/league-prod-toolkit#726]
Hello i got some probleme with toolkit 
The module Ingame don't working, i started spectate game and the module didn't work, live events too i try to restart them but the console say this

However module games state working 

2024-09-07T20:41:29.721Z [error] plugin-webapi: Failed to get information for summoner=UK GenkoKun. Maybe this summoner does not exist? error=GenericError: Request failed with status code 400
2024-09-07T20:41:29.725Z [error] module-league-state: Loading livegame failed for summoner=UK GenkoKun

![Capture d'écran 2024-09-07 230250](https://github.com/user-attachments/assets/188762bb-4f4c-4995-be10-217e9ce698d6)
![image](https://github.com/user-attachments/assets/1731dc9f-c52b-4acc-aaa5-abd7a85afdb8)

Could you Help me please ? 

**System:**

- OS Windows 11
- Node:v18.16.0.
- Prod Tool Version: 1.9.1
- Observer Tool Version:  6.12.0
- Streaming Software & Version: OBS 30.2.2
- Browser: Chrome

**Comment by sdomi4** [comment]
Ingame and LiveEvents are no longer working since Riot removed them, and we can no longer get that data.
