### ISSUE TITLE
[ Question ] How can i access the new champselect modes?

### ISSUE THREAD

**Issue by Wolfspeltz** [RCVolus/league-prod-toolkit#778]
Hey,
I saw that in the lastest big version bump you added a new champselect mode ( https://github.com/RCVolus/league-prod-toolkit/commit/e820718cb79f9398aa895df10d5a46fd8dba86d0) 
is this still in development or is there a way to access this and also the fearless modes for campselect?

**Comment by Himyu** [comment]
These modules are still in development and will probably be released by the end of the year.
