### ISSUE TITLE
[ Question ] are farsight files removed?

### ISSUE THREAD

**Issue by Iliketomobit** [RCVolus/league-prod-toolkit#793]
Does the latest zip file downloadable from the GitHub page exclude the farsight features? I am trying to use the in game overlay or at least the post match results page for a private tournament on the live server.

**Comment by sdomi4** [comment]
No, Farsight is still contained in the observer tool, although disabled by default as it doesn't work on live servers and isn't vanguard compliant. Due to this, most of the ingame overlay will not work, as noted in the readme.

Post match results should be (somewhat) functional.
