### ISSUE TITLE
End-game doesn't work

### ISSUE THREAD

**Issue by Syntetikk** [RCVolus/league-prod-toolkit#83]
Good evening, I come to you again because I have a problem with the End-Game statistics, indeed, I thought I understood that if the module was working well then the statistics should appear alone, it is not the case, moreover when I try to enter manually the name of a player during a game in progress or the id of the game at the end of this one to be able to have the statistics it also does not work, I do not do what to do, if you have solutions I'm a taker thanks.
**All modules are ON**
![fsdfsfsf](https://user-images.githubusercontent.com/52052819/157276566-f1145f4e-74d7-4be0-858d-e326880a6719.PNG)
![dfsdfsdfsf](https://user-images.githubusercontent.com/52052819/157276565-fbb2ec35-25e3-4099-b237-931b7546f591.PNG)
**After Match with Game ID error:**
![error](https://user-images.githubusercontent.com/52052819/157276558-7b39abef-72fd-405e-b586-5f5aaf658b49.PNG)
**During Match with summoner name error:**
![error2](https://user-images.githubusercontent.com/52052819/157277167-afe054c4-f0fe-4121-9d13-2a045bc879f5.PNG)

**Comment by Himyu** [comment]
This looks to me like your API key is either invalid or expired. If you are using a development key, that can be found on the riot API dashboard page, please note that this expires after 24 hours and therefore need to be renewed and replaced in the config when needed.
If your key is valid and not expired, please check in with us again :)
