### ISSUE TITLE
Ingame Overlay not working properly

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#86]
**Describe the bug**
Ingame animations don't work properly, (level up, item bought) + typo in embedded link in the ingame module (ingmae.html instead of ingame.html)

**To Reproduce**
1. Connect league production tool to league observer tool
2. Sync observer tool with ingame
3. start spectator mode ingame
4. Wait for a player to reach set level or until item is bought
5. wait for animation not to appear :(

**Expected behavior**
Expecting animation to appear properly, just like the inhibitor information do.

**Additional context**
Tried it on the current development branch, as on the state of the "update the ingame and teams module" issue. Neither does work

**Comment by sdomi4** [comment]
Do you have the same issue with the newest version of the ingame module (the typo is also fixed there...)? Steps to install are in #81 

If you still have nothing showing up, could you run the tool in debug mode (as instructed [here](https://github.com/RCVolus/league-prod-toolkit/issues/77#issuecomment-1058109091)) and post your output? This might be the same issue happening as in #77

**Comment by MaximilianRu** [comment]
Tried it now a second time with the new modules from #81, sadly it didn't work. I still had the typo in the link. But I had a new Layout in the Teams section. 

I will try to debug and keep it up to date here

**Comment by MaximilianRu** [comment]
Installing the production tool fresh made the animations work again. The bug came from some own adjustments of the ingame overlay. Deleting the div for the towers seems to break something.
