### ISSUE TITLE
Cannot read 'items' of undefined

### ISSUE THREAD

**Issue by derianchow** [RCVolus/league-prod-toolkit#88]
Whenever I start up the toolkit, this error always pops up, and will pop up again if I try to save settings for League-In-Game. Wondering what the fix would be since I already clean installed Toolkit and updated the modules for it. 

![image](https://user-images.githubusercontent.com/71459818/158488790-43f40130-c3a1-43d0-9348-b57e15883588.png)

**Comment by sdomi4** [comment]
This error message can occur when there are issues with the config (specifically syntax errors in or completely missing the module-league-in-game config). Could you post your config.json with your API key redacted?

For reference, the config should look something like this:
```
{
  "provider-webapi": {
    "apiKey": "RGAPI-SECRETKEY",
    "region": "ASIA",
    "server": "KR"
  },
  "rcv-pickban": {
    "backend": "ws://localhost:8999"
  },
  "static-league": {
    "last-downloaded-version": "12.5.1"
  },
  "database": {
    "user": "root",
    "password": "",
    "clusterUrl": "localhost",
    "port": 27017
  },
  "module-league-in-game": {
    "items": [
      "Legendary",
      "Mythic"
    ],
    "level": [
      "6",
      "11",
      "16"
    ]
  }
}
```

**Comment by derianchow** [comment]
```
{
  "provider-webapi": {
    "apiKey": "",
    "region": "AMERICAS",
    "server": "NA1"
  },
  "rcv-pickban": {
    "backend": "ws://localhost:8999"
  },
  "static-league": {
    "last-downloaded-version": "12.5.1"
  },
  "database": {
    "user": "root",
    "password": "",
    "clusterUrl": "localhost",
    "port": 27017
  },
  "league-in-game": {
    "items": [
      "Starter",
      "Consumable",
      "Epic",
      "Legendary",
      "Mythic"
    ],
    "level": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18"
    ]
  }
}

```
I had it set to this. I fixed it by doing a clean install of it and using the stock files, it works but Level Up and Buying Items are misaligned with Champ Portraits. I updated to the newer in game files and it was a bit finicky. I can most likely give a proper update later in the day when I can test with the newer files.

**Comment by sdomi4** [comment]
If you rename `league-in-game` to `module-league-in-game`, the error should be fixed.
This is due to us renaming some modules in the new versions, which isn't yet changed in the default config for the develop branch.

**Comment by derianchow** [comment]
Oh ok. For all updated modules, do I rename the folder to the zip name. For example if I update the rcv-teams files to the newer ones, should I rename the folder to module-teams-main since that's what the new zip was called.

**Comment by sdomi4** [comment]
You can leave the folder names as they are (or rename them to whatever you want, it shouldn't make any difference)

**Comment by sdomi4** [comment]
Oh, I missed the alignment issue above – please make sure to remove the default custom css in the OBS browser source, this likes to eat margins and colors.

**Comment by derianchow** [comment]
Another issue I ran into is if I update the files for League Static, it shows up as a blank on the Modules tab, and as Degraded in Plugins.

**Comment by sdomi4** [comment]
This is likely the same issue as before; the static module has been renamed to `module-league-static`. If you update the config accordingly, it should work as expected (although league-static does not have any substantial updates, you should be fine using the version in the develop branch until we merge the newer versions).
