### ISSUE TITLE
"npm run setuphooks" doesnt work

### ISSUE THREAD

**Issue by VeightV8** [RCVolus/league-prod-toolkit#89]
![image](https://user-images.githubusercontent.com/78297837/158804597-9d3ff6e7-50d1-4b7e-848b-d3aa1adf8be2.png)

?

**Comment by sdomi4** [comment]
Hi there :)
The `npm run setuphooks` command is only needed for development-related things. I assume you are just trying to install the toolkit? To install, all you need to run is `npm install` and `npm run build:modules` (head over to the [wiki ](https://github.com/RCVolus/league-prod-toolkit/wiki)for a more comprehensive guide).

If you are looking to contribute, please make sure to take a look at the Auth and spring-cleanup branches, these contain some substantial changes to the general structure of the toolkit :)
