### ISSUE TITLE
A lot of styling isnt working

### ISSUE THREAD

**Issue by VeightV8** [RCVolus/league-prod-toolkit#90]
![image](https://user-images.githubusercontent.com/78297837/159112098-ef1995cc-6646-43a6-a180-1c5fcb985342.png)
![image](https://user-images.githubusercontent.com/78297837/159112170-75d62b11-2546-48ad-8bd2-6ff9d3b5a187.png)

![image](https://user-images.githubusercontent.com/78297837/159111995-ec45ff91-f157-42cf-b0cc-212e9e0b4ac1.png)
![image](https://user-images.githubusercontent.com/78297837/159112068-6b0cd0b1-481f-402f-a985-eb1899b71137.png)

https://pastebin.com/PtRmtZ96

**Comment by sdomi4** [comment]
It looks like there are multiple issues at play here.
First off, the tool is unable to load the configuration. Could you make sure that config.json is present in `...\league-prod-toolkit-develop\modules\config` and doesn't contain any syntax errors? (feel free to post your config here with the API key redacted and I will take a look.)

The theming not working probably isn't config-related. Please try manually reapplying the default (or your) theme in the theming module. If you are using a customised theme, please post your index.scss here so I can take a look :)

**Comment by VeightV8** [comment]
So I reapplied the theme and it works now, thanks for that. And I also somehow without actually doing anything fixed the modules/plugins:
![image](https://user-images.githubusercontent.com/78297837/159130606-3a301529-3e9e-45b3-a94c-aee4285d909c.png)
![image](https://user-images.githubusercontent.com/78297837/159130598-cc3022ae-977f-49fd-afd1-0ed5a6ea9b2f.png)

However, I've found out that saving doesn't work for me; in rcv-teams I set the names and tags for the teams but when I go to the page it says Its still plain white (except for the yellow VS etc.) (Also applies rcv-tournament-tree, rcv-caster (When I click add it doesn't do anything)

![image](https://user-images.githubusercontent.com/78297837/159130704-cb598df9-4e9e-4c22-99d2-a5f1249f2140.png)
![image](https://user-images.githubusercontent.com/78297837/159130717-e5789205-9e08-443a-a355-9adce9ac07b9.png)
![image](https://user-images.githubusercontent.com/78297837/159130724-b2b19928-4b7b-4d62-9ea5-df7605b0c2ba.png)

Also, there are some errors happening in the console:
https://pastebin.com/HV5DN1NT

**Comment by VeightV8** [comment]
**UPDATE: It all works now :D**
