### ISSUE TITLE
Objective (Dragon/Baron/Herald) Overlay

### ISSUE THREAD

**Issue by VeightV8** [RCVolus/league-prod-toolkit#92]
It would be really nice to have something like that because the one league has in-game is just horrible:
![image](https://user-images.githubusercontent.com/78297837/159304324-0728fbe6-5000-4159-95d0-c7b9ecc2d3fb.png)

Something like LEC has would be super cool:
![image](https://user-images.githubusercontent.com/78297837/159304836-b4b3536f-6bdf-476d-b462-2962bd23119f.png)

**Comment by sdomi4** [comment]
Unfortunately, the ingame APIs don't offer a (practical) way to get at spawn timers.
You can enable the "esports" style of timers by adding this to game.cfg:
```
[Spectator]
eSportsNeutralTimers=1
```
(screenshot from old scoreboard)
![image](https://user-images.githubusercontent.com/84572334/159308920-93ea977b-2845-4b24-a0a5-c02ccaf58fd9.png)
