### ISSUE TITLE
Tool running but not working after installation, can't find the error.

### ISSUE THREAD

**Issue by jonasj95** [RCVolus/league-prod-toolkit#97]
After following the installation process from the wiki,
i can open the dashboard.

When i run
`npm run build:modules`
in Powershell window, i get following error and the build process is stuck after building prod-clock:

![image](https://user-images.githubusercontent.com/80636605/162634084-635436a7-118d-4338-a090-ef96c94deab7.png)

When starting with start.bat, i get multiple errors like this:

`[error] plugin-database: Uncaught error in database: Cannot find module 'C:\LOL Toolkit\league-prod-toolkit-develop\modules\database\dist\plugin.js'
{ Error: Cannot find module 'C:\LOL Toolkit\league-prod-toolkit-develop\modules\database\dist\plugin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Plugin.initialize (C:\LOL Toolkit\league-prod-toolkit-develop\dist\core\modules\Module.js:103:20)
    at activePlugins.forEach (C:\LOL Toolkit\league-prod-toolkit-develop\dist\core\modules\ModuleService.js:63:20)
    at Array.forEach (<anonymous>)
    at ModuleService.initialize (C:\LOL Toolkit\league-prod-toolkit-develop\dist\core\modules\ModuleService.js:62:28) code: 'MODULE_NOT_FOUND' }`

For every error, it cant find the plugin.js in the respective folder. There are plugin.ts files, but not in the respective \dist folder.

**Comment by sdomi4** [comment]
Hi there

These errors are due to missing dependencies and/or an incomplete build.
Please try manually running `npm install` and then `npm run build:modules` in the toolkit directory. If these commands throw any errors (outside of deprecation warnings), please post them here.

**Comment by jonasj95** [comment]
ran npm install which seemed to work, only giving some warnings.
then npm build and it threw following errors:

![image](https://user-images.githubusercontent.com/80636605/162643114-5000d91f-80a9-4713-a39b-a62f02696a77.png)


BTW thanks for the help!

**Comment by sdomi4** [comment]
This still looks like a dependency issue. Which version of node and npm do you have installed? You can check with `node -v` and `npm -version`.

**Comment by jonasj95** [comment]
managed to almost get it running, i still had an old version of node.js and npm, updating it fixed these issues.
Everything seems to run now, but the dragontail.tgz download seems to malfunction. Its monday so i dont think it has anything to do with patch day. I run npm start and wait for 2-3 minutes, and the dragontail download doesnt finish:
![image](https://user-images.githubusercontent.com/80636605/162816498-4f48b3e5-7da1-40a0-add9-25c1a7b11e7d.png)

I get these errors instead:
![image](https://user-images.githubusercontent.com/80636605/162816566-ad632e6c-48ea-420a-bcaf-8c09637197e6.png)

**Comment by sdomi4** [comment]
Please give the download more than a few minutes, depending on your connection this might take a while (all the assets are about a GB in size). You can ignore the error messages from other modules, these are just being impatient with the download :)

You can see all the outputs plugin-static-league should output while downloading [here](https://github.com/RCVolus/league-prod-toolkit/wiki/FAQ#toolkit-shows-multiple-request-timed-out-errors--missing-assets).

**Comment by jonasj95** [comment]
Ah, i always closed it too early. Now its working like it should after finishing the download. One last question: if i dont have an API key, can i use the 24h temporary API key that you can generate in the riot development portal?

**Comment by sdomi4** [comment]
All features work with a development key, but these are supposed to be used for testing only.
